### ISSUE TITLE
The "Icons" page on the wiki seems messed up

### ISSUE THREAD

**Issue by Jeff-411** [gokcehan/lf#1007]
When I clicked on the "Icons" menu entry on the wiki page, all I got was a message saying, "whyyyy"

**Comment by p-ouellette** [comment]
The history shows the Icons page was [deleted](https://github.com/gokcehan/lf/wiki/_compare/aa4ef272b51908f4aa6d65df6daab6228514240b) a while back because it was outdated. Someone recently re-added it with contents "whyyy". I reverted that change. The icons documentation is here: https://pkg.go.dev/github.com/gokcehan/lf#hdr-Icons.

**Comment by Jeff-411** [comment]
Ok, thanks.

**Comment by fastfading** [comment]
but how to use this 
https://github.com/gokcehan/lf/blob/master/etc/icons.example
and the color 
could you give  an  example ?

**Comment by niveK77pur** [comment]
@fastfading I had my head scratching on how to use it as well; luckily my brother pointed out to me that there is a section in the man page about it. You might wanna put the contents of the `icons.example` into a file called `~/.config/lf/icons`, and add `set icons` in your lfrc. Then everything worked for me! Hope it helps~

https://github.com/gokcehan/lf/blob/4440a15a8c8c460716c475ae109026b6689840af/lf.1#L285

**Comment by nasu-oldhand** [comment]
I use lf on Windows PowerShell Core.

put `icons.example` in `C:\Users\<User>\AppData\Local\lf\icons`

it does not work

![image](https://user-images.githubusercontent.com/81901297/221364314-041a98c4-57ed-4020-99d1-e146866e0f78.png)
[describe icons file location](https://pkg.go.dev/github.com/gokcehan/lf#section-readme)

shell
- PowerShell core 7.3.2
