### ISSUE TITLE
Using commands from lfrc.example is unsafe

### ISSUE THREAD

**Issue by mgoral** [gokcehan/lf#102]
Hi,

default configuration in `etc/lfrc.example` is unsafe to use because of frequent usage of unescaped `$f`, `$fs` and `$fx` variables.

For example, if I had a single file named `*` (just a star), running `remove` on it asks whether to remove this file only (because $fx is escaped in a printf command). However, when user accepts, the underlying shell will expand this as a globbing expression and recursively remove all not hidden files and directories under current `$PWD` which is probably not what user meant to do (because $fx is no longer escaped in a for loop).

Because new users will blindly copy useful commands from example configuration, I believe that each command in should at least notify user about its real result and protect them from possibly destroying their computers.

For example I rewrote the `remove` command to something like this:

```
set shell sh

# required, but we could set IFS inside remove command itself
set ifs "\n"

cmd remove ${{
    set -f

    # expand $fx so user knows what will happen.
    # we could also use `echo $fx`, but it's less readable
    for f in $fx; do
        printf "rm -rf \"%s\"\n" "$f"
    done

    printf "Continue? [y/n] "
    read ans
    test "$ans" = "y" || exit

    for f in $fx; do
        rm -rf "$f"
    done
}}
map <delete> remove
```

I think that `set -f` (disabling globbing in shell) is expected default behaviour - most users won't expect that $fs will contain more files than the ones they selected. Other thing is handling spaces and other special characters in commands like `vi $fx`, which is problematic without a shell supporting arrays (like Bash).

**Comment by TeddyDD** [comment]
It might be a good idea to check etc/lfrc.example with [shellcheck](https://www.shellcheck.net/)

**Comment by gokcehan** [comment]
@mgoral I haven't thought about this one, nice catch indeed, though this should be rare in practice. Unless I'm missing something, simply adding `set -f` seems to work for this problem. This is in almost all shell commands in the example configuration, though some of them fails accordingly when this happens.

There are also other problems in these shell examples. For example, `compress` command tries to create a directory with the given name. This can become a problem if there is already a directory with the given name. Extraction itself can also overwrite files or put files in unexpected places. There is also the case that filenames with `IFS` variables in them are separated unintentionally. For example, setting `ifs` to `\n` becomes a problem with filenames having newline characters. This is tracked in one of the open issues without much progress as the solution requires getting rid of the use of `IFS` mechanism altogether.

For these exceptional cases, I'm open to all suggestions that does not make things more complicated for the majority of the use case. At some point, I was thinking maybe there should be a way to add a standard prelude to all shell commands in addition to `ifs` option. Adding `set -eu` is the common standard recommendation these days to make shell scripts safer. For bash, this sometimes becomes `set -eu -o pipefail` and so on. Maybe we can add a `prelude` option which takes a string value for this purpose.

Note that when we set something as default for shell commands, it also effects shell commands interactively typed from the command line. I myself frequently use globbing with interactive shell commands. Having to type `$set +f; rm *` instead of `$rm *` may become annoying at some point. So I'm not sure if `set -f` should be the default behavior.

So for this issue, I think we have a few possibilities:

1. Add `set -f` to the example.
2. Ignore this exceptional case and pray it never happens.
3. Add `prelude` option and `set -euf` in the example configuration.
4. Comment out all shell commands to force people to explicitly accept using these commands.
5. Check `$f`, `$fs` and `$fx` filenames for some special characters (i.e. '\n' and '*') and refuse to run shell commands when they have these characters.

I'm personally inclined to option 2, though I can also live with option 1 as it does not complicate the example much. We can still implement `prelude` option for `set -eu` even if we don't go with option 3. Option 4 may annoy some people. Option 5 can also be interesting choice since it also handles the newline case. I will think about this for a while. Feel free to leave comments and ideas.

@TeddyDD Shellcheck seems nice although it does not find this exceptional case. I will try using it to clean up things in the example configuration.

**Comment by mgoral** [comment]
I agree that having a command which users are able to both type and map is useful. For example, my initial version of `remove` was something like this:

```
cmd remove ${{
    if [ $# -gt 0 ]; then
        rm -rf "$@"
        exit
    fi

    set -f

    # expand $fx so user knows what will happen.
    for f in $fx; do
        printf "rm -rf \"%s\"\n" "$f"
    done

    printf "Continue? [y/n] "
    read ans
    test "$ans" = "y" || exit

    for f in $fx; do
        rm -rf "$f"
    done
}}
map <delete> remove
```

This way I could both use remove from a command line (e.g. via `remove foo* bar *baz*` and from a mapping (sorry if these aren't correct terms in world of lf, I'm still fairly new to it :)). It is more complicated, but these are complicated cases ;)

There's also another option. Instead of exporting `fx`, `fs` and `f`, lf could call scripts with selected files passed to them as positional arguments. From end-user perspective this is a simpler and more straightforward than having to remember the meaning of several variables and one simply use the array of passed args via `rm -rf "$@"`, which properly escapes these variables in all shells that I know. If no file is selected, then currently focused one should be passed or the arguments provided by a user (although in this case lf would have to handle globbing and splitting).

Then the scripts become super-simple again:

```
cmd remove ${{
    printf "Continue? [y/n] "
    read ans
    test "$ans" = "y" || exit
    rm -rf "$@"
}}
```

**Comment by gokcehan** [comment]
I'm new to lf too :) I don't think there is an establish terminology for most things yet. Let's use the following names:

- (custom) shell command w/o argument as in `:remove`
- (custom) shell command with argument as in `:remove foo bar`
- interactive shell command as in `$rm foo bar` (literally typing this while `lf` is running instead of defining a command in the configuration file beforehand)

By the way, it is possible to map custom shell commands with some arguments so there is not really a distinction between command line use and mappings. For example:

    cmd say !echo "$@"
    map S say hello world

Your suggestion to pass selections as positional parameters may work well for this example, but then shell commmands can not take arguments. For example, our rename example uses both the current file and the argument:

    cmd rename %[ -e $1 ] && printf "file exists" || mv $f $1

I think this would not be possible to implement.

**Comment by mgoral** [comment]
Darn, I didn't think about rename case. :/ In that case I think that set -f should be good for most cases, at least until someone figures out a better way which would work with most shells.

**Comment by gokcehan** [comment]
I have now added a `shellopts` option which works by adding its value as command line flags (e.g. `sh {shellopts} -c {cmd} -- {args}`). I have added `set shellopts '-eu'` to the example configuration. I have also added `set -f` individually to the dangerous commands. Closing this issue for now.
