### ISSUE TITLE
using read in shell-pipe without waiting for enter

### ISSUE THREAD

**Issue by Susensio** [gokcehan/lf#1035]
I have this command 
```
cmd trash %{{
  set -f
  count=$(echo "$fx" | wc -l)
  if [[ $count == "1" ]]; then
    prompt="delete ${fx}? [y/N] "
  else
    prompt="delete $count files [y/N] "
  fi
  printf "$prompt"
  read -n1 ans
  [[ $ans == "y" ]] && rmv "$fx" && echo "deleted" || echo "deletion cancelled"
}}
```

I'm calling a custom script `rmv` that does the trash magic happen.
When `lf` is waiting for my yes or no, i have to do `y<enter>` despite having the `read -n1` flag.
This does not happen if using `${{` instead of `%{{`, but I would like to remain inside `lf` and not have to press `<enter>`.

What am I missing here? I think it has something to do with the way `lf` handles piping...

**Comment by vizcay** [comment]
I was going to ask the exact same question.. 🤔

**Comment by SeekingBlues** [comment]
`lf` only sends the input to the shell when you press enter. So although the shell is waiting for only one character, it doesn't get anything until enter is pressed. I think this is fairly reasonable since it allows you to do line editing on the input.

**Comment by Susensio** [comment]
But the default `:delete` command somehow manages to get the `[y/N]` without enter. Is there any way we could mimic that behaviour?

**Comment by SeekingBlues** [comment]
Unfortunately, I don't think that's possible.

**Comment by joelim-work** [comment]
As mentioned above, input to `%` commands are line-buffered, so you must press `enter` to send it to the shell. This is stated in the documentation (scroll to the very bottom):

https://github.com/gokcehan/lf/blob/dc2627de23647b0a0d1fa13d4c039ac075db175c/doc.go#L1309-L1328

I don't think there are any plans to change this so I will close this issue.

However I will add that you can alternatively treat pressing `enter` (instead of `y`) as confirmation by checking that the string being `read` is blank. This was discussed in #1078
