### ISSUE TITLE
Directory colors are too dim by default

### ISSUE THREAD

**Issue by flw-cn** [gokcehan/lf#104]
`lf` is really a great idea! I really like it. But it looks very dim on my terminal. So I hope that please to support TrueColor if possible.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/5546718/42129978-5fa62304-7d07-11e8-95d0-97e0233fbe56.png">

**Comment by flw-cn** [comment]
Thank you for explaining patiently to me. I have found a way under your guidance.
I understand that my problem is the blue color does look good when it is reversed.
The contrast of black on blue is not obvious enough.
So I just made a shell alias to avoid this problem simply: `alias lf='LSCOLORS=GxfxcxdxCxegedabagacad lf'`.

**Comment by gokcehan** [comment]
@flw-cn That sounds like a simple solution. I'm glad to hear it worked out for you. Sorry for my long response by the way. I had taken a look at this a few times before and I keep forgetting why this happens. So I wanted to document this somewhere to work on it later on.

**Comment by gokcehan** [comment]
@seifferth Thanks for the solution and pinging me again for this issue. I fully agree with sensible/readable defaults. It seems to me that the easiest solution for now is to use 8-bit mode in termbox and hide 256 color mode behind an option. In 8-bit mode `lf` should behave mostly like `ls` and most terminals can't afford to make `ls` output unreadable so we should be fine. People who wants to spare time configuring colors can simply turn on 256 color mode option before they start tweaking.

**Comment by gokcehan** [comment]
I have now changed the ui to use 8 colors by default (i.e. sgr 3-bit codes). There is now an option named `color256` which is disabled by default to change this to 256 colors (i.e. sgr 8-bit codes). If you already customized the colorscheme previously and don't want any changes you can set `color256` option to get the old behavior. For new users, lf should now use the same escape codes by ls which is likely readable in most terminals.

Closing this issue now. Feel free to report here any issues you have.

**Comment by roachsinai** [comment]
Hi, @gokcehan I got same issue this time (maybe be different reason):

![image](https://user-images.githubusercontent.com/9500049/112755340-cf7fc380-9012-11eb-9c7f-e0fa09022b73.png)

But seems the reason is the terminal colorscheme I used, I'm on Konsole using Gruvbox Dark colorscheme from here: https://github.com/morhetz/gruvbox-contrib/blob/master/konsole/Gruvbox_dark.colorscheme

The error message is very hard to figure out.

![image](https://user-images.githubusercontent.com/9500049/112755377-02c25280-9013-11eb-93d1-0eabc1ccc691.png)

After change to another colorscheme the text message is distinct.

Any suggestion will be appreciated!!!

**Comment by gokcehan** [comment]
@roachsinai You should be able to customize error message colors with `errorfmt` option without changing the terminal colorscheme.

**Comment by roachsinai** [comment]
@gokcehan thanks for quick reply, I'll check it!

**Comment by roachsinai** [comment]
Change it by `set errorfmt "\033[1;37;41m%s\033[0m"`, thanks again.
