### ISSUE TITLE
ueberzug image preview not refresh when resizing terminal after r28

### ISSUE THREAD

**Issue by eeeXun** [gokcehan/lf#1055]
This is r28

https://user-images.githubusercontent.com/58657914/209513090-32d42500-ffd6-40b8-a44e-b84521252eaa.mp4

This is r27

https://user-images.githubusercontent.com/58657914/209513151-4cca5a44-8bdb-4b5b-8b4e-119b92aeba3c.mp4

I use this [script](https://github.com/neeshy/lfimg/blob/master/pv) with ueberzug to preview image.

**Comment by DusanLesan** [comment]
I have the same issue with [ctpv](https://github.com/NikitaIvanovV/ctpv) after updating to r28

**Comment by SeekingBlues** [comment]
This regression seems to be introduced in e10ef91. Specifically:
https://github.com/gokcehan/lf/blob/b47cf6d5a525c39db268c2f7b77e2b7497843b17/ui.go#L682-L684
where the preview won't reload since the selected file did not change.

**Comment by ilyagr** [comment]
@laktak If you are around, please take a look.

**Comment by joelim-work** [comment]
After upgrading to version r28, I also noticed that running `$true` (or any other shell command) in the command line would cause an image preview to disappear.

When a shell command is run, the `cleaner` script is invoked to clear the preview. Prior to this version, the `previewer` script would also be invoked afterwards to restore the preview. However, because of the regression mentioned by @SeekingBlues, the `previewer` script is not invoked anymore because the current file hasn't changed and the function `return`s early.

If the current file hasn't changed, then I think the correct behaviour is to not call the `on-select` command and continue executing the rest of the function. Something like this:

```diff
diff --git a/ui.go b/ui.go
index 2ed56c8..c49a7db 100644
--- a/ui.go
+++ b/ui.go
@@ -679,11 +679,10 @@ func (ui *ui) loadFile(app *app, volatile bool) {
 		return
 	}
 
-	if curr.path == ui.currentFile {
-		return
+	if curr.path != ui.currentFile {
+		ui.currentFile = curr.path
+		onSelect(app)
 	}
-	ui.currentFile = curr.path
-	onSelect(app)
 
 	if !gOpts.preview {
 		return
```
