### ISSUE TITLE
See all mappings

### ISSUE THREAD

**Issue by iStagnant** [gokcehan/lf#1076]
It would be nice to have a command that shows all the mappings and what they do like the `:nmap` command in vim.

**Comment by ilyagr** [comment]
You can use `:doc` for the default mappings. You can also patch in https://github.com/gokcehan/lf/pull/918. There are some more workarounds discussed in that PR.

**Comment by ilyagr** [comment]
See also https://github.com/gokcehan/lf/wiki/Community-forks#ilyagrs-fork. I'm not sure  whether the amount of support I can provide for that fork would be sufficient for many people, but perhaps you'll find it useful.

**Comment by jackielii** [comment]
I think it's particularly useful for beginners to learn.

I recently started to pick up terminal file managers. Initially tried ranger for a few days but because of various bugs and searching forum led me to lf. Using `?` to show all mappings to know what to press.

Also, the cheatsheet is very useful, I kept going back to it: https://github.com/ranger/ranger/blob/master/doc/cheatsheet.svg

**Comment by joelim-work** [comment]
This is already implemented as of 1e1486f (`maps` and `cmaps` commands) and can be closed.
