### ISSUE TITLE
Script runs differently in lf and in zsh, also looking to improve the default delete command

### ISSUE THREAD

**Issue by jpmvferreira** [gokcehan/lf#1078]
On my attempt to create a command that deletes files without asking for confirmation, or better by just pressing enter after the prompt which would be equivalent to writing an 'y' (as it is the default in pacman for example), I have created the following command for lf:
```
cmd delete %{{
	set -f
	echo "Delete $(echo -e $fx | wc -l) file(s)? [Y/n] "
	read ans
	[[ $ans = "y" || $ans = "Y" || $ans = "" ]] && echo "File(s) deleted" || echo ""
}}
```

However, I have encounter the following issues:
1. The number of files it displays is wrong when run in lf, but right on the shell;
2. When running the command the file(s) which are selected vanish visually, although it still has them written in `$fx`
3. Most importantly, it doesn't allow for me to enter an empty prompt

I'm starting to think that the reason why the default delete command doesn't accept an empty prompt is due to lf itself, and not the way the command is written.
Is anybody able to find a workaround to this issue? 
It's not like it's a groundbreaking bug or a major quality of life improvement, but I really enjoy pressing enter when deleting something instead of writing an 'y' beforehand :).

**Comment by DusanLesan** [comment]
I do not know how to get empty strings to work. 
You can avoid numbering issue by getting the count separately, then adding that var to echo string. 
Clearing of the selected items looks to be called after you use delete function so you can avoid that by just creating a new function and calling that instead of delete.

**Comment by amelielavender** [comment]
i decided to try and play around with the confirmation bit and using `[ "$ans" != "n" ] && rm -rf $fx` worked only when i wasn't using the `shell-pipe` prefix. additionally, i couldn't get it to iterate over multiple selected files, so it only worked for one file at a time.

i tried to use the trash command from the example config and couldn't get it to mv multiple files to ~/.trash either.

**Comment by joelim-work** [comment]
To answer your questions:

> 1. The number of files it displays is wrong when run in lf, but right on the shell;

You need to quote `fx`, or else it will be split and passed as separate arguments to `echo`, which will then print them in a single line and resulting in a count of 1. You probably want something like `echo "$fx" | wc -l)`.

> 2. When running the command the file(s) which are selected vanish visually, although it still has them written in `$fx`

The `unselect` happens here: https://github.com/gokcehan/lf/blob/e885abe1a3f6a0a6a795f7f75f601c80566a3de2/eval.go#L1676-L1678

This works nicely for `$` commands because they are synchronous, but your example uses `%` which is asynchronous and is handled by a separate thread, allowing the execution to continue and unselect the files immediately. I do not know if there is a good way to fix this though, since it's not really possible to determine when an asynchronous shell command finishes. Actually, I think the best solution would be to rename the command to something other than `delete`, and handle the unselect yourself (e.g. `lf -remote "send $id unselect"`).

> 3. Most importantly, it doesn't allow for me to enter an empty prompt

The relevant code is here: https://github.com/gokcehan/lf/blob/e885abe1a3f6a0a6a795f7f75f601c80566a3de2/eval.go#L2143-L2147

Note that `cmd-enter` does nothing if the input is blank. The exception is if you are currently filtering for files, although perhaps this could be extended for `%` prompts too.

The following patch should solve your problem:

```diff
diff --git a/eval.go b/eval.go
index 24975c3..a92dc43 100644
--- a/eval.go
+++ b/eval.go
@@ -2142,7 +2142,7 @@ func (e *callExpr) eval(app *app, args []string) {
 		app.menuCompActive = false
 	case "cmd-enter":
 		s := string(append(app.ui.cmdAccLeft, app.ui.cmdAccRight...))
-		if len(s) == 0 && app.ui.cmdPrefix != "filter: " {
+		if len(s) == 0 && app.ui.cmdPrefix != "filter: " && app.ui.cmdPrefix != ">" {
 			return
 		}
```

I'm not sure if the original behavior is intended or simply a bug though.
