### ISSUE TITLE
Opening almost anything with l will use firefox

### ISSUE THREAD

**Issue by RoryNesbitt** [gokcehan/lf#1085]
Whenever I fine any variation of a text file, whatever the extension is doesn't matter, and I open it with <kbd>l</kbd> I get a new tab in firefox and a popup asking me to download the file.

opening with <kbd>e</kbd> correctly opens it in Neovim and `xdg-open filename` works fine, it's only <kbd>l</kbd> that has an issue.

Seems similar to #434 except I'm not sure what they done to solve it, the files aren't empty

**Comment by memchr** [comment]
Add configuration below to your `lfrc` and try again.

```
cmd open &{{
	mimetype=$(file --brief --dereference --mime-type $f)
	defapp=$(xdg-mime query default $mimetype)
	case "$defapp" in 
	nvim.desktop)
        lf -remote "send $id \$nvim $f"
		;;
	vim.desktop)
        lf -remote "send $id \$vim $f"
		;;
	*)
		xdg-open $f
	esac
}}
```
---

By default, `lf` run `xdg-open` asynchronously without access to stdin. Then `xdg-open` starts nvim, which fails because it can't read inputs from stdin, this caused `xdg-open` resort to open the file with your default browser (firefox) instead.

`xdg-open` is actually a shell script, which you can read to get a better understanding what it does behind the scenes.

**Comment by memchr** [comment]
Or use `&gio open $fs` as the file opener, which does not have this kind of issues. It also supports open multiple files.

`gio` command is part of `glib2` library, which should be installed on most distributions.

**Comment by RoryNesbitt** [comment]
Thanks for taking the time to explain this. I actually have a pretty well working script I got via one of the linked repos (I think it might have been lf gadgets) although this does look more concise so I'll try it out at some point
