### ISSUE TITLE
Jump to the nearest neighbor in the list in case some items disappeared

### ISSUE THREAD

**Issue by dumblob** [gokcehan/lf#109]
Steps to reproduce:
a) open a directory **D** with several files/dirs
b) put the cursor to a file/dir of your choice
c) delete this file/dir and some others in this directory **D** at the same time (e.g. from a command line)
d) the listing refreshes and puts the cursor to the very first file

Intuitively though (especially for larger number of items in a directory) one would expect `lf` in the step (4) to put the cursor to the nearest item to the item which was originally focused, but disappeared. This is especially useful when deleting files directly in `lf` using a key stroke.

**Comment by gokcehan** [comment]
@dumblob I thought this was already working but I think I was confusing this with something else.

I have pushed a commit to keep the old cached index for selection as a fallback. This only works for the behavior of `load` but not for `reload`. Since cache is cleared on `reload`, it is difficult to implement this if not impossible. But we are using `load` internally whereever possible, so this should not become much of an issue.

As an exception, apparently `shell-pipe` was triggering `reload` after the command. This was not intentional, so I chanced it back to `load`.

Closing this issue now. Thanks for reporting.
