### ISSUE TITLE
(Re)map prefixes

### ISSUE THREAD

**Issue by KenjiTakahashi** [gokcehan/lf#11]
I'd like to be able to do
```
map ; :
```
since it's mapped like this in ranger and I'm too used to not having to press Shift :-).
Personally, I'm fine with just hardcoding `;` as alias for `:`, but maybe a more generic solution would be nice?

**Comment by gokcehan** [comment]
You can map it by mapping the `read` command as such:

    map ; read

When I tried it now, I thought it wasn't going to work since `;` is used as the statement separator but it seems to work somehow, kind of accidental though :)

At some point I will clean the parser code. I will try to remember not to break this behaviour but if something changes you can reopen this issue.
