### ISSUE TITLE
Unexpected error 

### ISSUE THREAD

**Issue by ask1234560** [gokcehan/lf#1120]
Hi, thanks for the lf project. I am new to lf and getting the following error. 

```
alacritty -e lf
visit a directory 
then press w to open in that directory
after that ctrl-d to exit 
but instead of returning to lf, lf is exited
```

Attaching the screencast of the issue, don't know where to look to solve this issue. Thanks in advance. 

https://user-images.githubusercontent.com/25929911/220682315-507454bf-85f7-4d36-9df5-4e551aeec411.mp4

**Comment by Joyje** [comment]
Why is this unexpected? Ctrl-d will close your terminal, just as it happens in your video.
Maybe you are confusing Ctrl-d with Ctrl-c? Try using Ctrl-c instead.

**Comment by ask1234560** [comment]
Hi @Joyje,

Here find the expected behaviour, 

https://user-images.githubusercontent.com/25929911/229356508-cc85f9bd-0548-4b15-b11c-6baaa1921446.mp4

**Comment by Joyje** [comment]
I never use that feature you are using, so I never looked in to exactly how that feature work, but I tried it in my terminal (rxvt) and I can see that my results are different from yours. I get the result you want to have, so it seems like it is related to either your terminal (alacritty) or your terminal settings.

After a quick test I can see that running `tty` gives me the same result before opening lf, as it will after using the feature mapped to "w" by default, meaning that feature won't open a new terminal process.
I do see however after running `ps` that a new bash session has started, and as such Ctrl-d should shut down the current bash session first, and thus returning to lf, which it does for me but not for you for some reason.

What version of lf are you running? `lf -version`

After pressing `w` run `ps` and show the results here.

Also you can try pressing `$` to enter a shell command in lf, and type `bash` instead of pressing `w` and see if your result is different.

**Comment by ask1234560** [comment]
I tried `urxvt -e lf` but after exiting the spawned terminal with ctrl+d the `lf` becomes unresponsive. 

> What version of lf are you running? `lf -version`
```
lf --version
28
```
 
> Also you can try pressing `$` to enter a shell command in lf, and type `bash` instead of pressing `w` and see if your result is different.

I tried `alacritty -e lf`. Here it is working correctly if `$bash` is spawned. And for `$zsh` the issue comes. 

1. `$bash`
![image](https://user-images.githubusercontent.com/25929911/229363931-5975a38a-a389-4be3-a6db-aba6f6159ace.png)

2. '$zsh'
![image](https://user-images.githubusercontent.com/25929911/229363863-5d7ab20d-81aa-4553-9e45-502c1f03eb55.png)

 > After pressing w run ps and show the results here.

1.  `alacritty -e lf`
![image](https://user-images.githubusercontent.com/25929911/229363688-ce6a73f5-3f18-42cb-96d6-c52db3741697.png)

2. normal 
![image](https://user-images.githubusercontent.com/25929911/229363727-affd5e26-3fff-4df2-a42c-ff9d19f39f7b.png)

**Comment by Joyje** [comment]
I don't use zsh so I cant tell you for sure, but zsh might handle nesting differently from bash. In bash, Ctrl-d will perform an `exit` command which will close the current session taking you one level up through the nesting.

If you run `bash` and `bash` and `bash` again, you will need to do `Ctrl-d` `Ctrl-d` `Ctrl-d` to get back to where you started.
Maybe doing `Ctrl-d` in a nested zsh session will close all zsh shells instead? You can test it without running lf and just running shells to see the results. If this is the case, this has to do with zsh, not lf, and switching to bash solves the issue.

**Comment by ask1234560** [comment]
I also think it is due to shells. I created 3 extra shells for each shell. 

`zsh`
![image](https://user-images.githubusercontent.com/25929911/229365901-7e671438-2c06-40a1-9993-5bfac17895cb.png)

`bash`
![image](https://user-images.githubusercontent.com/25929911/229366656-a088f0c0-f47c-4f82-aad9-b9e8e8c07579.png)

Anyway thanks @Joyje . I found the direction to look for.

**Comment by Joyje** [comment]
No problem! I'm glad I could help!
