### ISSUE TITLE
Regression causing flashing lf with each selection

### ISSUE THREAD

**Issue by bluesuncat** [gokcehan/lf#1133]
The current git version of lf redraws the screen each time a file is opened (when a previewer is used)
This causes the right pane to flash and display a "loading..." message for a split second each time a file is opened, making this very annoying.

It looks like this was introduced by this https://github.com/gokcehan/lf/commit/4a443cae58ffe417c4aebedd88aeae6380bf190c
Please revert the commit causing the regression

**Comment by ilyagr** [comment]
Any thoughts, @joelim-work? See also https://github.com/gokcehan/lf/issues/414#issuecomment-1445295342

**Comment by ilyagr** [comment]
I'm also leaning towards the opinion that reverting that commit would do more harm than good. However, I don't want to state that too strongly, since while the flicker doesn't bother me, maybe that's just the way I use `lf`.

**Comment by joelim-work** [comment]
I should point out that reverting 4a443ca will only prevent flickering when a file is opened - the flickering will still occur for all the other actions where the selected file does change (e.g. navigating with `up`/`down`). Given that the flickering already occurs while navigating, I don't think the user experience is impacted by much if the flickering occurs when opening a file as well.

---

BTW the act of opening a file by default runs a shell command, which causes the file to be reloaded: https://github.com/gokcehan/lf/blob/3fc1db5d1426d417869857d4b6cf090f05d73d26/app.go#L543

I believe this is by design, since theoretically a shell command can change the nature of a file.

**Comment by bluesuncat** [comment]
> @bluesuncat In my opinion this is really just a duplicate of #414, since that issue highlights the real problem where `loading...` is displayed whenever any file is selected.

This issue is about the flickering that occurs when opening files, not for previews like in #414

I do not see any reason why the preview would need to be refreshed when a file is opened since the preview would never change just because it is rendered twice, but maybe Im overlooking something here?

In any case, this change is very annoying and made lf nearly useless for me because I found it way too distracting. This may be a personal preference but I hope we can agree that it would be ideal to avoid any flickering at all like ranger does for example.

**Comment by joelim-work** [comment]
I can reproduce the issue with a minimal config example:

`lfrc` config file:

```
cmd open $true
set previewer 'preview'
```

`preview` script:

```sh
#!/bin/sh

sleep 1
cat "$1"
exit 1; # exit 0 means the preview will be cached
```

With this example, opening a file does nothing, but `lf` will reload the file (as I have mentioned in my previous comment), causing the `preview` script to run. The `preview` script sleeps long enough for the `loading...` message to display, and then outputs the contents of the file.

> I do not see any reason why the preview would need to be refreshed when a file is opened since the preview would never change just because it is rendered twice, but maybe Im overlooking something here?

I assume your issue here is that `lf` is reloading a file (and as a result refreshing the preview) when you try to open it?

I think that it is reasonable to make the assumption that opening a file is a 'read-only' operation, and there would be no need to reload the file or refresh the preview since nothing has changed. But this is not necessarily true, since `lf` allows you to configure your own `open` command, which can in theory make any arbitrary changes. `lf` implements opening a file by calling a generic `app.runShell` function, which assumes the file can be changed and reloads it.

For example it is possible to define the `open` command to append some text (nonsensical, but valid from `lf`'s perspective):

```
cmd open $echo some text >> $f
```

The current behaviour of `lf` is that the preview will be refreshed, but also cause a flicker. If the commit 4a443ca is reverted, then there will be no flicker, but this also means the preview shown will be stale because it doesn't update at all.

---

As an afterthought, I suppose it is technically possible to add logic to the `app.runShell` function to not reload the file for certain scenarios, such as opening a file.  But this introduces extra complexity, especially when the problem can be addressed by fixing #414. @ilyagr I'm not sure what your opinion on this might be.

**Comment by bluesuncat** [comment]
Ok I see why https://github.com/gokcehan/lf/commit/4a443cae58ffe417c4aebedd88aeae6380bf190c was implemented, but the reason sounds like it would be useful for a very narrow edge case.

Instead of reloading the preview every time and adding an option to not reload the preview, wouldn't it make more sense to add a custom option to allow reloading a file for specific scenarios like opening a file?

If I understand the use case for this change correctly, most users wont need this which makes it a valid option for a costume configuration option, especially since the features that require the reload would also need to be configured first anyway.

**Comment by joelim-work** [comment]
> Ok I see why https://github.com/gokcehan/lf/commit/4a443cae58ffe417c4aebedd88aeae6380bf190c was implemented, but the reason sounds like it would be useful for a very narrow edge case.

By "very narrow edge case", if you mean allowing for the possibility of defining the `open` command to modify a file, then no that is not the intention of 4a443ca. Nobody writes code to deliberately allow for weird edge cases like that. I'm not sure if I 100% understood what you were trying to say here, apologies if I got that wrong.

The reason why opening a file ultimately ends up refreshing a preview is not to accommodate for users with weird edge cases. It an effect that is naturally caused by splitting the code into modular, reusable components to make development easier.

When you open a file, `lf` by default invokes `$OPENER`, which is a shell command. This is handled by calling [`app.runShell`](https://github.com/gokcehan/lf/blob/3fc1db5d1426d417869857d4b6cf090f05d73d26/app.go#L481), which is a generic function used to invoke a shell command. In order to be reusable, `app.runShell` tries to make as little assumptions as possible, such as whether the current file has changed and needs to be reloaded or not - it just reloads the file unconditionally.

Reloading the file is handled by calling [`ui.loadFile`](https://github.com/gokcehan/lf/blob/3fc1db5d1426d417869857d4b6cf090f05d73d26/ui.go#L697), which is another generic function. Similarly, `ui.loadFile` does not make any assumptions about whether the user has selected a different file or not for the purposes of refreshing the preview. In fact if you look at the original code in version r27, you'll see that there is no check to determine if a new file has been selected or not - the rest of the function is executed. All commit 4a443ca does is to restore that design choice because someone had accidentally changed this and it was causing issues for other users. https://github.com/gokcehan/lf/blob/50f11ad3dee6f01cd4847771eef5103319f2680f/ui.go#L635-L658

If you really think that opening a file shouldn't cause this kind of flicker, then maybe you can play around with the code to see if you can prevent `ui.loadFile` from being called, or at least pass `volatile = false` so that the file gets reloaded but the preview is not refreshed (I think that should work, but I haven't tested it myself). But in my opinion it shouldn't matter because refreshing a preview should be a smooth process anyway, which is why #414 exists.

**Comment by bluesuncat** [comment]
> But in my opinion it shouldn't matter because refreshing a preview should be a smooth process anyway, which is why #414 exists.

Agreed! Assuming that fixing #414 will indeed resolve this issue as well, I will close this for now.
