### ISSUE TITLE
Ability to have rifle to include autocompletion using tab?

### ISSUE THREAD

**Issue by thepenguinthatwants** [gokcehan/lf#1155]
Hi,
I am using this to open files, but sometimes I need to specify specific programs. 

```
cmd rifle ${{
    set -f
    rifle -l $f
    read -p "Select runner: " runner
    rifle -p $runner $f
}}
```

Is there any way to make pressing <tab>  to use autocomplete to get the program name? Insted of writing full name of the program that can be used to open the file?

**Comment by joelim-work** [comment]
This is not handled by `lf`, and what you're currently asking for would require Bash `read` to support custom autocompletions, which I'm not sure if it does.

As a suggestion you could pipe the output of `rifle -l` into [`fzf`](https://github.com/junegunn/fzf) and save the result as `runner`, something like:

```shell
runner=$(rifle -l $f | fzf)
rifle -p $runner $f
```

You may have to do some processing on the output text, but I don't know since I don't use `rifle`.

**Comment by thepenguinthatwants** [comment]
Hi @joelim-work , thanks for the reply.

How do you handle the situation where you want to open a file but with non default software? Do u just type the name of whole program?

**Comment by joelim-work** [comment]
`fzf` by default constrains its output to the choices that were originally provided. For instance, the following command allows you to select a number between 1 and 10 (and nothing else):

```shell
seq 10 | fzf
```

I have found that by using the `--print-query` option, it is possible to get `fzf` to output the original query if it doesn't match anything:
```shell
seq 10 | fzf --print-query | tail -n 1
```

`tail` is required here to extract only the last line of the ouptut, because `fzf` will print both the query and the selection if there is a match.

Would this be sufficient for your purposes?

Again, I'm not sure if you want to go for this `fzf` route, but I can tell you that this kind of completion behaviour doesn't really have anything to do with `lf` itself - all `lf` does is start a shell and leaves that shell to handle everything.

**Comment by Joyje** [comment]
Typically you would add `-e` to enable autocomplete in bash when using readline. For some reason I can't get it to work in `lf` though. I asked a question about it under discussions. Maybe we can solve this together if we can find out some more details about how `lf` runs the commands specified in custom shell functions.

You could try it and see if it works for you though since I might have some specific issue with my system. Simply change your code to:

`cmd rifle ${{`
`    set -f`
`    rifle -l $f`
`    read -e -p "Select runner: " runner`
`    rifle -p $runner $f`
`}}`

Test it and see if it works. If you get the error: `read: Illegal option -e`, the issue isn't specific for my system and there is something I need to learn about how `lf` runs the commands in order to find a way to fix it.

**Comment by joelim-work** [comment]
@Joyje Correct me if I'm wrong, but I thought `read -e` could only complete filenames and there's no support for providing custom completions (e.g. the output of `rifle`). That's why I suggested the use of `fzf`, but it's not exactly the same and I'm not sure if there's a better way of achieving this.

**Comment by Joyje** [comment]
@joelim-work It seems you are absolutely right! I read somewhere that `-e` gives access to your terminal history among other things, but after testing it just now that information seems to be inaccurate.
