### ISSUE TITLE
Search with ignore diacritic?

### ISSUE THREAD

**Issue by martinlebeda** [gokcehan/lf#116]
Search with ignorecase is great idea, but in my filename is casually names with not only different case, but with dicritics too (I'm not native english). For me is better find this with ignore diacritics. ie. when I search "prilis" want in result "příliš" too.

I'm change search function for transliterate dicritics to ascii before compare ( https://github.com/martinlebeda/lf/commit/1a47e4d88ea9bf914a874eecb8472b81d444a4b1 ). 

Is it good idea?

**Comment by gokcehan** [comment]
@martinlebeda Thanks for working on this. I think my native language also has diacritics as well though they all exists on my keyboard layout as keys so I just type them when necessary. Anyway, this could be an interesting feature though I have a few things on my mind:

1. In your patch, I think you should be using `lpattern := normalizeString(pattern)` instead of `lpattern := strings.ToLower(pattern)` or otherwise `smartcase` may not work as expected when comparing `pattern == lpattern`. I haven't tried this though so I might be wrong.

2. I'm not sure if this should be done automatically for `ignorecase` and `smartcase`. It can be confusing for some users since this is not about cases. Maybe there should be separate options for this behavior like `ignorediacritics` and `smartdiacritics` though I'm still not sure about this.

3. Does it also handle string normalization as discussed [here](https://blog.golang.org/normalization). This could be a problem when dealing with diacritics.

4. The [text](https://godoc.org/golang.org/x/text) package seems like a big dependency for this task. Is there a simpler library for only diacritics? Also, is this package properly maintained? I'm asking because at some point we used it to calculate rune widths but it wasn't working properly so we had to replace it with [go-runewidth](github.com/mattn/go-runewidth) instead.

**Comment by martinlebeda** [comment]
@gokcehan Thanks for reaction. I can type all needed character from keyboard, but files are named randomly with or without accents (different authors, uses different conventions... it is mess, but it is status quo and origin my need).

add 1., 2. - you're right, use separate options like `ignorediacritics` and `smartdiacritics` is much better.

add 3., 4. - I have a distorted view to normalization, for subset of UTF-8 used by me this works well, but it can be a general problem and package text is too general and big for this.
I look for another solution. I found 3 types of solutions, package text as I try, iconv and static maps. [Iconv](https://golanglibs.com/search?q=iconv&sort=top) is standard library in *nix - but this usually need GCO and system dependency which is not acceptable. Several libraries use own solution mostly based on static mapping. I finally looked to [fzf](https://github.com/junegunn/fzf), which is stable and widely used, and found [static map](https://github.com/junegunn/fzf/blob/master/src/algo/normalize.go). This solution is quick and no dependency, but solve only latin script letters. It is enough for me, I use fzf often and works well. But is this acceptable?

**Comment by gokcehan** [comment]
@martinlebeda To be honest, I don't feel confident to have an opinion on what is acceptable or not for this topic. I guess I need to be doing some reading about this. Static mapping as in fzf seems like a simple solution we can adopt though I have no idea how comprehensive it is for different languages. It may be better to implement something complete in the first place rather than having a half-baked solution. I was thinking, maybe we can also check how they do this normalization in the text package as well. Maybe there might be a reason why they pack all those functionalities in a single package. In that case, it might be better to use that library for this purpose.

In the meantime, I don't want to block this issue. If you like, we can merge your patch with the text package. Or you can implement static mapping as you mention but I'm guessing that will require copy pasting things from other repositories which I'm not really a fan of. Also, if you are going to implement options for this, maybe we can leave them off by default for now.
