### ISSUE TITLE
Support for alt + arrow keys

### ISSUE THREAD

**Issue by avidseeker** [gokcehan/lf#1163]
Shell escape sequence for:
*  Alt+Up: ^[[1;3A] 
* Up: ^[[A]

Yet `lf` recognizes both as `<up>`

**Comment by Joyje** [comment]
I'm not fully certain, but it could be due to this [issue](https://github.com/gokcehan/lf/issues/1186)

**Comment by ilyagr** [comment]
That's not quite right in the sense that the terminal programs do get different inputs on `<up>` and `<a-up>`, and lf doesn't distinguish them (even though it could). I've been thinking of adding support for more Alt keybinding, but I'm not sure when I get to it, and there could be some obstacles.

Most importantly, I think different terminals can send Alt keybindings in different ways. Different window managers and operating systems differ in which Alt keybindings get captured by the system and which do get passed to the program. I'm worried that supporting Alt keybindings would cause people to more run into snippets that work on one machine not working on another machine, and send us bugs that would be difficult to diagnose.

**Comment by avidseeker** [comment]
Regardless of different terminals and keybinding systems, all lf would care about is receiving `^[[1;3A]` on its side.

On the users side, debugging would be as simple as enabling verbatim mode (i.e `ctrl+v`) to see what is being sent.

I checked `konsole`, `xfce4-terminal`, and `st` and both send the same sequence.

**Comment by avidseeker** [comment]
It would be nice to add `Shift + arrowkeys` too. This will enable multi-selecting similar to GUI file managers with `Shift + up` or `Shift + down` and `shift + pgup,pgdn`.

**Comment by joelim-work** [comment]
The `tcell` library does detect modifiers, it's just that `lf` doesn't check for them. Actually I found it fairly trivial to implement, the change is quite small and I have already submitted a PR: #1248

I do feel that some users will run into problems because of their personal setups, but TBH these issues already exist (e.g. #1186 ), and usually the user will just end up picking some other keybinding. In any case the documentation does make it clear that certain key combinations just simply will not work, and how to check for those scenarios:

https://github.com/gokcehan/lf/blob/88b3c999afb7cab8e8ca61da3c9063f0cc348c10/doc.go#L1145-L1146
