### ISSUE TITLE
Local settings for folders like 'downloads'

### ISSUE THREAD

**Issue by aidam38** [gokcehan/lf#117]
Hi, newbie here. I love lf, but the last piece I'm missing is local settings for directories, in ranger it was:
``
setlocal path=/home/adam/downloads sort mtime
``
Is this going to be implemented, or is there a simple way to code this in myself? 
Thanks.

**Comment by yanzhang0219** [comment]
Hello,
Any thoughts and updates on this? This feature is really necessary, especially for the download folder where we can sort by "time added" so that the newly downloaded item will be the first entry.
Thank you very much.

**Comment by gokcehan** [comment]
@yanzhang0219 There are some thoughts for implementation ideas in #71 but there are no updates. I don't particularly find it difficult to set sorting to time manually in downloads folder when necessary which already has a default binding anyways. That's why I haven't worked on this myself. Maybe you can come up with a workaround to do this automatically for you by setting a custom `on-cd` command.

**Comment by yanzhang0219** [comment]
Got it. Thank you for your advice. 
My desire is when I enter the Downloads folder, the sort will be "sort by date added" automatically and the sorts for other directories will retain "sort by natural". Currently, when I enter the Downloads folder and manually use like`sa` to sort, all other directories are sorted by `atime` together, so when I go out of the Downloads folder, I have to use `sn` manually to make other directories being sort by natural. It's not that convenient. 

I am kinda new to lf, so I have no idea on the `on-cd` command. I will dig into it later. Thanks a lot.

**Comment by gokcehan** [comment]
This is added in #1381.
