### ISSUE TITLE
Path doesn't preserve when reload in a symbolic linked directory

### ISSUE THREAD

**Issue by ahshum** [gokcehan/lf#1185]
## Description

1. create a symbolic link to a folder, e.g. `mkdir testdir && ln -s testdir linkdir`
2. open `lf` and navigate to `linkdir`
3. do a reload by `Ctrl+r` and the path location at the top will be changed

I think it should make sense to preserve the path location after reload?

## Version
r28

**Comment by joelim-work** [comment]
The relevant code is here: https://github.com/gokcehan/lf/blob/e885abe1a3f6a0a6a795f7f75f601c80566a3de2/nav.go#L620-L627

The problem is that [`os.Getwd`](https://pkg.go.dev/os#Getwd) has trouble with symbolic links:

> If the current directory can be reached via multiple paths (due to symbolic links), Getwd may return any one of them.

---

That being said, I think it would be possible to fix this, by not calling `os.Getwd` and just using the current path that is stored internally.

```diff
diff --git a/nav.go b/nav.go
index d491237..2cad699 100644
--- a/nav.go
+++ b/nav.go
@@ -621,13 +621,8 @@ func (nav *nav) reload() error {
 	nav.dirCache = make(map[string]*dir)
 	nav.regCache = make(map[string]*reg)
 
-	wd, err := os.Getwd()
-	if err != nil {
-		return fmt.Errorf("getting current directory: %s", err)
-	}
-
 	curr, err := nav.currFile()
-	nav.getDirs(wd)
+	nav.getDirs(nav.currDir().path)
 	if err == nil {
 		last := nav.dirs[len(nav.dirs)-1]
 		last.files = append(last.files, curr)
```

Although this kind of goes against the idea of 'reloading' - generally you would expect the state to be loaded from scratch instead of relying on the previous state. I'll tag @gokcehan to see if the idea is OK first before submitting a PR.

**Comment by gokcehan** [comment]
@joelim-work Thanks for the investigation. I think it makes sense to do this change so I would accept such a patch.
