### ISSUE TITLE
Does not change to partition D: In Windows

### ISSUE THREAD

**Issue by lucasmsoares96** [gokcehan/lf#1216]
When I type the command `D:` In Windows CMD, the root directory changes from C: To D:. But when I do `$D:`` In lf it doesn't happen.

**Comment by joelim-work** [comment]
In general `$cd /to/some/path` doesn't work because `$` starts a child shell process, and `cd` will change the CWD of that process and not the CWD of `lf` itself. To change directories inside `lf`, the *builtin* `cd` command needs to be used.

For your specific case, you should type the following:

```
:cd 'D:\'
```

Note that the `\` is required at the end or else it won't be treated as an absolute path, and the quotes are required to escape the `\`.

**Comment by lucasmsoares96** [comment]
It works! Thanks.
