### ISSUE TITLE
is there way to rename files

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [gokcehan/lf#122]
i looking at the doc and could find anyway to do it is there
and if it is not there is there anyone working/planning to work on :rename?

**Comment by TeddyDD** [comment]
https://github.com/gokcehan/lf/blob/master/etc/lfrc.example#L45

**Comment by Kallinteris-Andreas** [comment]
is there shell scripts are used instead of built-in commands

**Comment by TeddyDD** [comment]
LF doesn't have built-in rename command I'd suggest you to read docs `lf -doc` and example lfrc I linked.

**Comment by gokcehan** [comment]
@Kallinteris-Andreas There is one provided in the example configuration as @TeddyDD mentioned. I think you also meant to ask if there is a reason this is implemented as a custom command rather than a builtin and the answer is yes. When it is implemented as a custom command, users can change it to their liking such as making it overwriting or prompting and such. When we make a builtin command, we need to decide it for all users beforehand and it will make some people unhappy. Counter argument is to have something by default and make it configurable so users can use it without any configuration. Renaming is a common basic operation so I'm not against adding a builtin `rename` command we should find a proper way to get the input from the users in builtin commands first.

**Comment by gokcehan** [comment]
By the way, if we add a builtin command for `rename`, we can add the name of the current file to the prompt to help with #120.

**Comment by Kallinteris-Andreas** [comment]
the reason i wanted to add :rename if because i want the functionality from ranger where pressing the keys `I`, `a`, `A` which puts the cursor in a different place

**Comment by doronbehar** [comment]
Hey guys, going over old issues in this repo. I noticed Lf does have a built in `rename` command. @Kallinteris-Andreas as for the `I`, `a` and `A` functionality from ranger, I've added a [section on that](https://github.com/gokcehan/lf/wiki/Tips#rename-commands-similar-to-those-of-ranger) on the WiKi's Tips page. Please tell me if you have comments or better - improve it your self.

**Comment by JurisMajors** [comment]
@gokcehan do we still want to implement this as a built-in? If so, are there any specific requirements (except auto complete for current file), because I could work on this.

**Comment by gokcehan** [comment]
@JurisMajors I'm still in favor of adding this so that we could have a rename command that works in windows by default. On the top of my head, I think the following requirements should apply:

- It should add the current filename to the execution line with the cursor at the end
- It should work with filenames with spaces without the need for quotes
- It should use the underlying operating system call with [os.Rename](https://golang.org/pkg/os/#Rename)
- It should move the current file selection to the same file if its position is changed

I believe these should make most people happy. It will still be possible to add some custom commands for specific needs as discussed above.

**Comment by JurisMajors** [comment]
@gokcehan 

> It should add the current filename to the execution line with the cursor at the end
I would personally prefer it not being automatic, but on a button press (like TAB). In case you want to entirely change a long file name, deleting the whole name is annoying. 

> It should move the current file selection to the same file if its position is changed

This happens in case of file `myfile` being renamed to `dir/myfile` and in this case its moved to directory `dir` ? Then we should cd in that directory or also add it to the selection?

Also, if `dir` does not exist, should prompt for error or make a new directory.

**Comment by gokcehan** [comment]
@JurisMajors 

> I would personally prefer it not being automatic, but on a button press (like TAB). In case you want to entirely change a long file name, deleting the whole name is annoying.

I would be ok to with not having the current file name on the line but it is usually a common request by users and this was originally one of the reasons we tried to add this as a builtin. I was thinking, if we implement this command as a modal command, you could simply get rid of the current file name with <kbd>C-u</kbd>. If we implement it the other way around, that is having empty line by default, we need to invent a new way to add the current file name to the line. In the former case, users can also overwrite the default behavior with a custom binding as such:

    map r :rename; cmd-delete-home  # rename with a blank prompt

In addition, it would be possible to define other requested variants of the rename command mentioned above:

    map A rename             # cursor at the end
    map I :rename; cmd-home  # cursor at the beginning

I'm not quite sure if it will be possible to define a variant that would exclude the file extension (i.e. `a` in ranger).

> This happens in case of file myfile being renamed to dir/myfile and in this case its moved to directory dir ? Then we should cd in that directory or also add it to the selection?

I was just thinking of operations in the current directory when I said this but if it moves to a different directory then I guess we can also change to that directory and move the selection to that file in that directory.

> Nevermind, looks like os.Rename creates the directory in that case.

On my linux machine, I think it does not create the directory if it does not exists. They simply use the underlying operating system call which can behave in different ways on different platforms I guess. At this point, I'm not sure if we should simply use the `os.Rename` call or try to behave consistently on different platforms.

Also I forgot to mention about overwriting behavior which again seems to be platform dependent in `os.Rename`. We should ideally check the destination file existence before and prompt user for an overwrite for safety, kind of like the same prompt mechanism as `delete`. If we implement this as a prompt, maybe we can also add parent directory creation as a prompt as well.

**Comment by JurisMajors** [comment]
@gokcehan 

> I was thinking, if we implement this command as a modal command, you could simply get rid of the current file name with `C-u`

I believe this will work just as well in that case.

> I think it does not create the directory if it does not exists.

I will do some testing of course, however, the documentation implied otherwise.

> At this point, I'm not sure if we should simply use the `os.Rename` call or try to behave consistently on different platforms.

I think having a `os.Rename` call initially is definetely better. And if requested or when the base around `:rename` is built, changing the `os.Rename` call should not be much of a problem.

> We should ideally check the destination file existence before and prompt user for an overwrite for safety, kind of like the same prompt mechanism as `delete`

Sounds good to me.

Not sure when I get to work on this, but when I do, I will probably be providing you with part of the functionality, to get some feedback. Hopefully, sometime next week!

**Comment by JurisMajors** [comment]
This can be closed now I think
