### ISSUE TITLE
wezterm image preview

### ISSUE THREAD

**Issue by moisestohias** [gokcehan/lf#1230]
Wezterm is the only terminal that support image preveiwing in Windows. 
But lf dones't have proper config for wezterm imgcat. please add propper config support
I tried invoking "wezterm imgcat" from external script but didn't work.

[This seems to be an issue with the lf not wezterm](https://github.com/wez/wezterm/discussions/2423)

**Comment by gokcehan** [comment]
@moisestohias There are some instructions in the [Previews](https://github.com/gokcehan/lf/wiki/Previews) wiki page for wezterm though I'm not sure if it works or not.

**Comment by moisestohias** [comment]
@gokcehan No unfortunately it doesn't work, and this seems to be an issue with lf not wezterm. I hope you took a look at the thread I've linked above, even with "tput cup" this still doesn't work on linux.
Wezterm is the only terminal that support image preview on windows and doesn't suck. So please fix this. I am like most people I guess trying to have consistent workflow when switching between linux and windows.

**Comment by lkhphuc** [comment]
FWIW, I followed the [instruction for kitty](https://github.com/gokcehan/lf/wiki/Previews#with-kitty-and-pistol) on Wiki guide and it works fine on wezterm on Mac for me.

**Comment by ryanmsnyder** [comment]
@lkhphuc do you mind sharing your `lf` cleanup and preview scripts? I would appreciate it

**Comment by moisestohias** [comment]
@lkhphuc we are talking about wezterm not kitty here, I know it works fine in kitty

**Comment by lkhphuc** [comment]
> @lkhphuc do you mind sharing your `lf` cleanup and preview scripts? I would appreciate it

@ryanmsnyder it's literally the script down below, calling the kitty +kitten
```
#!/usr/bin/env bash

kitty +kitten icat --clear --stdin no --silent --transfer-mode file < /dev/null > /dev/tty
```

I am running this kitten command on wezterm, because it has support for kitty image protocol. I'm not sure if that requires the install of kitty on your system or not, or if it works on Linux or not. It just that my system has wezterm and kitty installed, I can execute the command kitty +kitten in wezterm and the instruction for kitty in the wiki work fine for wezterm.

 
<img width="965" alt="Screenshot 2023-07-15 at 16 26 21" src="https://github.com/gokcehan/lf/assets/12573521/688a375e-28b4-4944-b034-8f93707b391d">

**Comment by ryanmsnyder** [comment]
@lkhphuc thanks for confirming - that's what I assumed. I wonder if there's a native way to utilize the kitty image protocol within wezterm? Similar to how wezterm has the subcommand `wezterm imgcat` but that that can handle coordinates like the `kitty +kitten icat` command.

@moisestohias, did you get `wezterm imgcat` working with `lf`? The command works for me when I pass it an image outside of `lf` but I'm wondering if the reason it doesn't work in `lf` as a previewer is because it can't take coordinates like the `kitty +kitten icat` command or `ueberzug` does. Looks like it can only take width and height:

<img width="1324" alt="image" src="https://github.com/gokcehan/lf/assets/41448219/8b50d79c-2d4a-4387-943f-9c186b50a505">

**Comment by ryanmsnyder** [comment]
Just found this [discussion](https://github.com/wez/wezterm/discussions/2423) on wezterm's GH discussing the same thing. And here's a [feature request](https://github.com/wez/wezterm/issues/3716) to enhance the `wezterm imgcat` command to accept a position flag as well as a clear flag when navigating away from the file. Go give it an upvote.

**Comment by pbogut** [comment]
So wezterm now accept position, but if I try to use it with lf it opens image in my editor, here is a command I'm using:
`wezterm imgcat "$file" --width "$w" --height "$h" --position "$x,$y"`
