### ISSUE TITLE
Feature Request: view directory left and right side

### ISSUE THREAD

**Issue by og900aero** [gokcehan/lf#1235]
Any chance for new view for 2 tabs at once? 

The other day I saw a solution in the joshuto file manager, according to which there is a view where the other page does not have the preview image, but the same one as on the first page can be turned on, so it's like mc, vifm. When you don't need it, you can go back to the original view. I think this is a very good solution, because basically the view of the lf is great, but sometimes the double view is useful for certain copies, and then one button could restore the view to the original. This would save space much more than opening another lf or using tmux.

Example:

![hsplit](https://github.com/gokcehan/lf/assets/49487376/a5b7b4b1-0bec-4a21-ad0b-5ecf4d2fe534)

**Comment by joelim-work** [comment]
I couldn't quite determine whether you're asking about views or tabs, so I'll just explain both.

If you're asking about tabs, where each tab can be at a different location (e.g. tab 1 at `/etc` and tab 2 at `/var/log`), then no, tabs aren't supported in `lf`. This has been asked before in #153 and the author is against supporting it.

If you just simply want to change the view (i.e. the number of columns), then you can just define some mappings to change certain settings in your config file:

```
map <a-1> :set preview true; set ratios 1:2:3
map <a-2> :set preview false; set ratios 1:1
```

**Comment by og900aero** [comment]
> map <a-1> :set preview true; set ratios 1:2:3
> map <a-2> :set preview false; set ratios 1:1

No, I don't mean tabs. Look at the picture. You can see there is the same file browser window on the left and right side, which you can copy between them. Lf doesn't know this. The ratio and preview values is not the same.

**Comment by joelim-work** [comment]
OK I understand what you mean now. This is the `mode = "hsplit"` setting in `joshuto`, where you essentially have two contexts (each represented by a 'tab'), and you want to show both of them at the same time.

Although I don't make the decisions in the project, judging from what I have seen, I would say that `lf` is designed to support only one context at a time, and the author's advice would be something like use `tmux` to run two instances of `lf` with the setting `set ratios 1`.

**Comment by og900aero** [comment]
> OK I understand what you mean now. This is the `mode = "hsplit"` setting in `joshuto`, where you essentially have two contexts (each represented by a 'tab'), and you want to show both of them at the same time.
> 
> Although I don't make the decisions in the project, judging from what I have seen, I would say that `lf` is designed to support only one context at a time, and the author's advice would be something like use `tmux` to run two instances of `lf` with the setting `set ratios 1`.

Thx. Would be nice this solution (like joshuto),Tmux is not good, because it lowers the current window, so the visible area will be small. It would be a good solution on a 24" monitor, but I work on a 15" notebook, so using tmux is not enjoyable.

**Comment by joelim-work** [comment]
I'll tag @gokcehan to see if he's willing to reconsider or at least share some thoughts, but I can't promise you anything.

**Comment by ilyagr** [comment]
> Tmux is not good, because it lowers the current window, so the visible area will be small.

There are plenty of reasons one might dislike tmux, but I'm not sure I understand what you mean here. In the README, there's an example screenshot with tmux, and I wouldn't say it takes up a lot of space. You lose one line for tmux's status bar, and that's pretty much it.

![tmux-lf](https://camo.githubusercontent.com/af7b8a53ce9800b37151befa25634ea16f8d8a451af3b25e454c9656c1d2d2ee/687474703a2f2f692e696d6775722e636f6d2f703935787a556a2e706e67)

You could argue that space would be used a bit more efficiently if the two lf windows shared the command-line line (so you would have the entire screen width to enter `$` commands), but that doesn't seem like a huge issue.

**Comment by og900aero** [comment]
> > Tmux is not good, because it lowers the current window, so the visible area will be small.
> 
> There are plenty of reasons one might dislike tmux, but I'm not sure I understand what you mean here. In the README, there's an example screenshot with tmux, and I wouldn't say it takes up a lot of space. You lose one line for tmux's status bar, and that's pretty much it.
> 
> ![tmux-lf](https://camo.githubusercontent.com/af7b8a53ce9800b37151befa25634ea16f8d8a451af3b25e454c9656c1d2d2ee/687474703a2f2f692e696d6775722e636f6d2f703935787a556a2e706e67)
> 
> You could argue that space would be used a bit more efficiently if the two lf windows shared the command-line line (so you would have the entire screen width to enter `$` commands), but that doesn't seem like a huge issue.

The only problem is where tmux works and where it doesn't. After a simple Debian Stable installation, it always says "no server running on /tmp/tmux-1000/default" as an error, when run tmux lf, or tmux other command. And as I look at the net, a lot of people run into this mistake. It would be much better if lf knew it by default, and didn't need a separate program that either works on the given distro or stock system, or it doesn't.

**Comment by ilyagr** [comment]
I think this criticism of tmux is quite fair -- it has an annoying learning curve.

For a whirlwind tour:

- Put `set -g mouse on` in ~/.config/tmux/tmux.conf
- Run `tmux`
- Press *either* `<c-b> "` or `<c-b> %` to split the window vertically/horizontally
- Run `lf` in one of the panes, click the other, run `lf` again. You can also use `<c-b> up/down/left/right` to move between panes.

Alternatively, you can try https://www.byobu.org/ for a config of tmux that's intended to have an easier learning curve.

I'm not sure if there are convenient ways to use `lf` without being familiar with `tmux` or an equivalent. Wishing for that makes sense, but I'm not sure we'll ever get to implementing it.

**Comment by og900aero** [comment]
> I think this criticism of tmux is quite fair -- it has an annoying learning curve.
> 
> For a whirlwind tour:
> 
> * Put `set -g mouse on` in `~/.config/tmux/tmux.conf` (this has some downsides, but more upsides IMO. You'll need to either learn tmux's way of selecting text or hold down either shift or ctrl -- depending on your terminal -- to select text).
> * Run `tmux` without arguments
> * Press _either_ `<c-b> "` or `<c-b> %` to split the window vertically/horizontally
> * Run `lf` in one of the panes, click the other, run `lf` again. You can also use `<c-b> up/down/left/right` to move between panes.
> 
> See also https://github.com/tmux/tmux/wiki/Getting-Started.
> 
> Alternatively, you can try https://www.byobu.org/ for a config of tmux that's intended to have an easier learning curve. I never used it, but I'm hopeful that it may have succeeded at that goal.
> 
> I'm not sure if there are convenient ways to use `lf` without being familiar with `tmux` or an equivalent. Wishing for that makes sense, but I'm not sure we'll ever get to implementing it.

As you can see from your example, tmux is anything but not an easy and quick solution. That is why it is not a solution to the problem, That is why I thought that such a solution could be implemented in the way mentioned above.
Of course, I understand that you don't want to solve this, but I think it would be a more important solution, because it cannot be programmed by the users, like the different types of the rename command, for example.

**Comment by gokcehan** [comment]
> Tmux is not good, because it lowers the current window, so the visible area will be small. It would be a good solution on a 24" monitor, but I work on a 15" notebook, so using tmux is not enjoyable.

@og900aero I think you can disable the status bar if it bothers you.

> As you can see from your example, tmux is anything but not an easy and quick solution (thats why implemented this in joshuto, vifm, ranger too). That is why it is not a solution to the problem, That is why I thought that such a solution could be implemented in the way mentioned above.

@og900aero The last time I used `ranger`, I don't think it was possible to copy some files in one instance and paste them to another instance. This was one of my original motivations to create `lf` in the first place. I don't know if things have changed recently but I suspect the reason tabs are implemented in other file managers might be the lack of support for such multiple client use cases otherwise. `lf` is designed to be independent of the multiplexing approach so you can use whatever you feel like (e.g. tmux, i3, terminal splits/tabs). Therefore I still think tabs/views are an anti-pattern in `lf`.

To be honest, I don't think this is even worth discussing at this point because it would be such a big undertaking to implement this in `lf`. So far we have mostly assumed there is only a single ui/nav in the program so I don't think the code can handle such a major change at this point. It is ok to use other programs if they match your expectations better. Not every use case should be handled in the same program.

**Comment by og900aero** [comment]
> To be honest, I don't think this is even worth discussing at this point because it would be such a big undertaking to implement this in `lf`. So far we have mostly assumed there is only a single ui/nav in the program so I don't think the code can handle such a major change at this point. It is ok to use other programs if they match your expectations better. Not every use case should be handled in the same program.

Ok. Thx your response.

**Comment by og900aero** [comment]
.

**Comment by og900aero** [comment]
> Gökçehan mentioned that some terminals support splits and tabs (a.k.a. panes). I'd like to emphasize that point -- this might actually work very well with `lf`. I use Kitty (https://sw.kovidgoyal.net/kitty/) often and, though I barely use those specific features, I know that Kitty has very good support for them and they are quite easy to use. Moreover, I think one of the specific design goals the author of Kitty has is to make `tmux` unnecessary.
> 
> There are other recent terminals with similarly good support for splits (wezterm, I think?), but I haven't used them much.

The problem with Kitty, wezterm, and most terminals is that they are bloatware. I built a Debian Linux that is very-very light (run only 195MB memory). Therefore, for example, the terminal is suckless terminal (st terminal). Quarter consumes as much as wezterm e.g. That's why I wouldn't want to install x number of programs for one function because of the problems. Now I'm configuring ranger because it can do that, even though I hate python.
Regardless, **I have all the respect for you guys**, because you have created and developed such a near-perfect file manager that fills the gap. In addition, it is easy to configure. Unfortunately, this 1 function is very important for me (I programmed many other functions with bash scripts, or I can tolerate its absence).

**Comment by alejoguitar** [comment]
Hi, maybe a little late to the party. I just "tweaked" a kitty-nc mode with tmux,  custom configs and some shell alias. Main guide was LF wiki. 
(I'm quite new to github in general and never contributed to any project, as programming is not on my skills, please excuse if this is not the right place to do it)

Maybe this might be an easy solution to this problem. 

So: I aliased lfnc like this

	lfnc ()
	{
		if { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } then
			tmux \
				source-file ~/.tmux-nc.conf \; \
				split -h lf -config ~/.config/lf/lfnc.conf ; lf -config ~/.config/lf/lfnc.conf
		else
			tmux -f ~/.tmux-nc.conf \
				new-session lf -config ~/.config/lf/lfnc.conf \; \
				split -h lf -config ~/.config/lf/lfnc.conf \; \
				selectp -L \; \
				attach 
				
		fi
	}

So it checks if there's a tmux server or starts a new one with a custom config file. I don't use tmux regularly (tiling WM is enough for my use case) so I don't know if this might collide with other configs.

custom tmux config (tmux-nc.conf):
	set -g status off
	bind-key -n tab select-pane -t + 

So the status bar on the bottom is gone and you can switch panes with tab, just like in NC/MC. Other NC/MC hotkeys might be easy to implement like quit with F10 by adding: 
	unbind-key F10
	bind-key -n F10 kill-session

But I think this is not so clean, as it could kill the window while pasting files. Maybe there's a better idea. I tried with some lf -remote commands, but I don't get it. Maybe someone can improve it.

lf-nc.conf :
	source ~/.config/lf/lfrc
	set nopreview
	set ratios 1
	set info size:time
	set drawbox false

More things could be copied of nc/mc hotkeys but I think the idea is not to fully clone it, otherwise mabye just putting cmd mc $mc on the config would be enough :laughing: 
No, seriously, I think especially the F5 and F6 functions of MC are some of the one if makes it worthy to have dual panels. But well... tab + paste is not bad either.

Also, the shell alias could be also built in the main lfrc, so you can just call the whole tmux split from a hotkey within lf. 
Another option could be just write a script and put it into $PATH and, in lf, just create a hotkey like map nc $lfnc

Anyways, hope it helps. And would very much appreciate any improvements to it.
