### ISSUE TITLE
how can auto-set colunm , auto set 2 colunm and auto set 3 colunm

### ISSUE THREAD

**Issue by newyorkthink** [gokcehan/lf#1238]
when i run lf the sv like this:

they show have 6 colunm
![image](https://github.com/gokcehan/lf/assets/87791643/7b0d0509-a1c1-4e7f-8d8d-62f2362f34f7)

i want lf run sv, it can auto set the 2 colum
![image](https://github.com/gokcehan/lf/assets/87791643/7b094343-ffa4-4419-91df-f23b8c7af899)

**Comment by joelim-work** [comment]
I don't fully understand your problem, what does 'sv' mean?

If it helps you, you can manually change the columns even after `lf` has started, by typing something like `:set ratios 1:2`.

**Comment by og900aero** [comment]
I dont understand what is sv, but I use this code in lf.rc, when I opened more than one lf:

```
# Run on open lf
&{{
	lf -remote 'send %if [ $lf_width -le 120 ]; then lf -remote "send $id no_preview"; else lf -remote "send $id yes_preview"; fi'
}}

cmd no_preview :{{
    set nopreview
    set ratios 1
    set info size:time
    map mm yes_preview
    $ctpvclear
}}

cmd yes_preview :{{
    set ratios 1:1
    set preview
    set info size:time
    map mm no_preview
}}
```
I did this so that if I open it in 2 copies, it will only have 1 window, so that it can be clearly seen on the small display, and it can be switched with the mm combination (that's why there are two commands: yes preview, no preview). ctpvclear is only for clearing the image preview

**Comment by joelim-work** [comment]
I think I figured it out, `sv` is just the desired keybinding, which can be changed to anything else.

Anyway the example configuration given by @og900aero looks good to me, so I think this issue can be closed.
