### ISSUE TITLE
Confirmation message when using trash-cli?

### ISSUE THREAD

**Issue by PowerMan2206** [gokcehan/lf#1244]
When using the built-in `delete` command to delete files, it asks for a confirmation in lf itself. Is this possible when using a trash command like `trash-cli`?
![2023-05-13_22:48:44](https://github.com/gokcehan/lf/assets/61635519/636304b8-abd0-4d38-9273-052298c77aac)

**Comment by PowerMan2206** [comment]
To clarify, I know that a confirmation is possible with a `read` and an `if` in the trash function, but it isn't displayed *in* lf itself

**Comment by joelim-work** [comment]
If you want to have shell commands read from and write to the bottom status line, then you need to use shell-pipe (`%`) commands instead of shell (`$`) commands:

Here is a very quick and dirty example:

```shell
cmd trash %{{
    printf "Trash '%s'? [y/n] " "$f"
    read -r ans
    if [ "$ans" = "y" ]; then
        trash-put "$f"
    else
        echo "aborting"
    fi
}}

map t trash
```

This isn't supposed to be a final solution, and I have only tested it briefly, but it is proof that you can mimic the confirmation in the builtin `delete` command. I believe one of the reasons that `delete` was added as a builtin command was for convenience, so users wouldn't have to implement confirmation input themselves.

**Comment by PowerMan2206** [comment]
Thanks, I didn't really know the difference between $ and %. After a bunch of fiddling around I got to
```bash
# trash items
cmd trash %{{
	# put items into array that we can count them
	files=()
	while read -r line; do files+=("$line"); done <<< "$fx"
	
	# count how many items there are
	len=${#files[@]}
	
	# confirm trashing
	if [[ $len == 1 ]]; then
		echo -n "trash '$fx' ?"
	else
		echo -n "trash $len items?"
	fi
	echo -n " [y/N] "
	
	# read answer
	read -n 1 ans
	# make it lowercase
	ans="${ans,,}" 
	
	echo
	
	# nuke
	if [[ $ans == y ]]; then
		trash-put $fx
		if [[ $len == 1 ]]; then
			echo "trashed '$files'"
		else
			echo "trashed $len items"
		fi
	else
		# needed to clear the bottom row
		echo
	fi
}}
```

It's not perfect (for some reason the `-n 1` in `read` doesn't work, and `-p` does nothing), but it works. I also decided to put in a thingy for detecting how many files there are and printing the correct message. That's most of the code, really.
