### ISSUE TITLE
[Feature] Direnv integration

### ISSUE THREAD

**Issue by colin-heffernan** [gokcehan/lf#1283]
I use [Direnv](https://direnv.net/) to load and unload virtual environments, but I don't know if I can integrate it with LF. Having this as a feature (or having an example on the wiki for doing it yourself) would be useful. Other tools such as [Emacs](https://github.com/wbolster/emacs-direnv) and [Vim](https://github.com/direnv/direnv.vim) have existing integrations.

**Comment by joelim-work** [comment]
I believe that won't be possible unless `lf` is modified to expose a `setenv` command to set its own environment variables so that it can pass them to any shell it spawns. The reason why other tools work is because they provide methods for updating their environment variables from external sources (in this case the output of `direnv export json`/`direnv export vim`).

**Comment by colin-heffernan** [comment]
Closing this as I no longer need it, though it was never implemented.

**Comment by colin-heffernan** [comment]
Wrong closed, it should be not completed.
