### ISSUE TITLE
How do I unescape the space when passing $fx?

### ISSUE THREAD

**Issue by AvianY** [gokcehan/lf#129]
I have a command:
`$mimeopen $fx`
and, say, I have multiple files selected and I want to edit them in vim. I cannot make this work, because $fx will pass newline between filenames. If I change filesep to something like space (" "), it still won't work, because the space is escaped and vim thinks all the filenames is one long name.
What am I doing wrong? How can I make this work?

**Comment by AvianY** [comment]
it still doesn't work... no matter what I set for ifs and filesep

**Comment by gokcehan** [comment]
@AvianY What shell do you use? And do you set these values in between double quotes?

    set ifs "\n"
    set filesep "\n"  # this is default so you don't need it

You can post your configuration somewhere if you like and I can take a look at it.

**Comment by AvianY** [comment]
Yes, I just noticed... argh.. I am so angry. I changed shell to zsh and after that it stopped working. Now it's ok when it's back to sh.... but why doesn zsh work as it should??

**Comment by AvianY** [comment]
I am talking about the `set shell ...` option. I changed that from sh to zsh.

**Comment by gokcehan** [comment]
@AvianY Shells don't pass `IFS` value to children processes because of security issues so we have to set this by hardcoding a prefix like `IFS='<newline>'; ...` to each command. I haven't tried this in `zsh` so maybe there is some incompatibility there. There are times like this that we have to assume a posix compatible shell and I don't know the current state with `zsh` in this regard. In fact, this was one of the reasons we still don't set `ifs` option by default, to be compatible with other shells if possible. For example, the way we set this option value is not even compatible with `fish` syntax. I guess apparently `zsh` does not work well with `ifs` option as well. This is unfortunate, but I can't think of anything to solve this if it does not work.

**Comment by gokcehan** [comment]
I had kept this issue open just in case we change the default `ifs` to `\n` but I guess we don't need to track this here. By the way, it seems that I forgot to mention `shellopts` option is a string separated by `:` so you can include other useful options with `--shwordsplit` as such:

    set shell zsh
    set shellopts '-eu:--shwordsplit'
    set ifs "\n"
    set filesep "\n"  # default already

I have added to our tips wiki. Closing this issue now.

**Comment by Goosegit11** [comment]
When pressing 'w' and spawning children shell with $f and $fx variables, it spawn a normal zsh, without these options, and something like `cp $fx myfolder` doesn't work:

```
$ cp $fx myfolder
cp: cannot stat '/home/user/test/file1'$'\n''/home/user/test/file2': No such file
or directory
```
