### ISSUE TITLE
"cannot use stat.Nlink as uint64" when install lf

### ISSUE THREAD

**Issue by rockyzhang24** [gokcehan/lf#1294]
When I tried to install `lf` via `env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest`, I got an erorr. Please refer to pic below

<img width="1590" alt="image" src="https://github.com/gokcehan/lf/assets/11582667/b2616b30-1c51-4657-b404-5f17ec9b2993">

My OS: macOS 13.3. I am not sure whether the issue is OS specific.

Thank you.

**Comment by ilyagr** [comment]
What does `go version` output?

**Comment by rockyzhang24** [comment]
`go version go1.20.5 darwin/arm64`

**Comment by ilyagr** [comment]
I can't reproduce it, but I'm on linux/amd64. It would be great if somebody using darwin/arm64 looked at this.

**Comment by rockyzhang24** [comment]
Thank you anyway. I almost reinstall (update) lf and brew update eveyday. This issue just happened today. I'm not sure whether it is caused by lf, go, or other lf's dependencies.

**Comment by ilyagr** [comment]
That's very helpful.

The line the error refers to is

https://github.com/gokcehan/lf/blame/2ab4b14e883f7d989fbe1e0a193223263bfeeed1/os.go#L213

It was changed by #1288. @joelim-work, I have no idea why that change caused a problem, but perhaps we should change that call back to a `fmt.Sprintf`?

**Comment by ilyagr** [comment]
Also, I could reproduce the problem:

```
$ env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go install -ldflags="-s -w" github.com/gokcehan/lf@latest
# github.com/gokcehan/lf
../pkg/mod/github.com/gokcehan/lf@v0.0.0-20230609114535-2ab4b14e883f/os.go:213:29: cannot use stat.Nlink (variable of type uint16) as uint64 value in argument to strconv.FormatUint
```

**Comment by joelim-work** [comment]
Thanks for reporting, I am fixing it now, @ilyagr is indeed correct.

**Comment by ilyagr** [comment]
Do you have any idea why the problem appeared? If you figure it out, you could report it on the Go bugtracker -- it seems to be a bug in their stdlib.

**Comment by ilyagr** [comment]
I'm also surprised the Github CI didn't catch this. @gokcehan, is that still on?

**Comment by joelim-work** [comment]
It's not a bug in Go, it's just simply because `stat.Nlink` has a different type depending on the platform. For [Darwin ARM 64-bit](https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/syscall/ztypes_darwin_arm64.go;l=68) it is `uint16`, but on my platform [Linux AMD 64-bit](https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/syscall/ztypes_linux_amd64.go;l=104) it is `uint64`.

My apologies for causing this bug, I only thought to test this locally and didn't consider other platforms.

**Comment by joelim-work** [comment]
@rockyzhang24 I'm not sure if `go install` can build from a PR, but if it's not too much trouble could you please checkout the code in #1295 and see if it works for you?

**Comment by joelim-work** [comment]
@ilyagr I checked the CI pipeline, it only builds on Ubuntu and Windows, so that explains the issue was not caught earlier: https://github.com/gokcehan/lf/blob/2ab4b14e883f7d989fbe1e0a193223263bfeeed1/.github/workflows/go.yml#L11-L30

Building for all the other platforms happens in a different pipeline, which I suspect is only triggered manually whenever a new release is to be created: https://github.com/gokcehan/lf/blob/2ab4b14e883f7d989fbe1e0a193223263bfeeed1/.github/workflows/release.yml#L10-L21

**Comment by rockyzhang24** [comment]
Thank you guys for the quick response and hard work. I have no idea how to `go install` with a PR. Probably you could merge it into a separate branch and then I could run `env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@<branch>`?

**Comment by ilyagr** [comment]
You can clone it and run

    env CGO_ENABLED=0 go build -ldflags="-s -w"

@joelim-work , if you can run gen/xbuild.sh (if I remember the name correctly), it should be pretty safe.

**Comment by rockyzhang24** [comment]
@ilyagr Thanks. I just tested it. The `build` worked well and launched `lf` by `./lf` perfectly.

**Comment by ilyagr** [comment]
Also, @rockyzhang24 can try

    env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/joelim-work/lf@fix-nlink-format

**Comment by rockyzhang24** [comment]
> Also, @rockyzhang24 can try
> 
> ```
> env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/joelim-work/lf@fix-nlink-format
> ```

I already tried this command at the beginning but got an error.

<img width="1085" alt="image" src="https://github.com/gokcehan/lf/assets/11582667/fd978c47-3471-4f36-849b-b3bbb236275d">
