### ISSUE TITLE
Random crash deleting selected files

### ISSUE THREAD

**Issue by jneidel** [gokcehan/lf#1314]
lf version: `30.r12.ga9d90bc`

## What happend

I selected some files and wanted to mass rename them. I triggered my binding for `qmv -f do -d $fx`, but before that could execute (i.e. show the files to be renamed in vim) lf crashed and somehow took the selected files with it (i.e. removed them).

## Error

```
main.(*nav).currSelections(0xc0004de000)
        github.com/gokcehan/lf/nav.go:1936 +0x1a5
main.(*nav).exportFiles(0xc0004de000)
        github.com/gokcehan/lf/nav.go:661 +0x4e
main.(*nav).preview(0xc0004de000, {0xc0003207c0, 0x35}, 0xc0000ea020)
        github.com/gokcehan/lf/nav.go:803 +0x165
main.(*nav).previewLoop(0xc0004de000, 0xc0004c0000)
        github.com/gokcehan/lf/nav.go:711 +0x33a
created by main.(*app).loop
        github.com/gokcehan/lf/app.go:244 +0xaa

goroutine 1 [runnable]:
syscall.Syscall6(0xc00028a690?, 0x49?, 0x7f1bd4f44848?, 0x7f1bfc2d6f18?, 0xd0?, 0xc000080800?, 0xc00057ec30?)
        syscall/syscall_linux.go:91 +0x36
syscall.fstatat(0xffffffffffffffff?, {0xc00028a690?, 0x768a60?}, 0xc00057ec68, 0xffffffffffffffff?)
        syscall/zsyscall_linux_amd64.go:1443 +0x9a
syscall.Lstat(...)
        syscall/syscall_linux_amd64.go:74
os.lstatNolog.func1(...)
        os/stat_unix.go:45
os.ignoringEINTR(...)
        os/file_posix.go:245
os.lstatNolog({0xc00028a690, 0x49})
        os/stat_unix.go:44 +0x5b
os.Lstat({0xc00028a690, 0x49})
        os/stat.go:22 +0x34
main.(*nav).renew(0xc0004de000)
        github.com/gokcehan/lf/nav.go:610 +0xd1
main.(*app).runCmdSync(0xc0004e0000, 0xe?, 0x0)
        github.com/gokcehan/lf/app.go:500 +0x16c
main.(*app).runShell(0xc0004e0000, {0xc0002383f0, 0xe}, {0xc000478680, 0x2, 0x2}, {0xc0002383e8, 0x1})
        github.com/gokcehan/lf/app.go:525 +0x15e
main.(*execExpr).eval(0xc0004782a0, 0xc0000a5e60?, {0xc000478680, 0x2, 0x2})
        github.com/gokcehan/lf/eval.go:2548 +0x110
main.(*callExpr).eval(0xc00023a360, 0xc0004e0000, {0xc0000c7400?, 0x0?, 0xc00021c240?})
        github.com/gokcehan/lf/eval.go:2540 +0x82fe
main.(*app).loop(0xc0004e0000)
        github.com/gokcehan/lf/app.go:446 +0xc33
main.run()
        github.com/gokcehan/lf/client.go:61 +0x33b
main.main()
        github.com/gokcehan/lf/main.go:331 +0x7af

goroutine 33 [syscall, 8 minutes]:
os/signal.signal_recv()
        runtime/sigqueue.go:152 +0x2f
os/signal.loop()
        os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
        os/signal/signal.go:151 +0x2a

goroutine 50 [select]:
github.com/gdamore/tcell/v2.(*tScreen).PollEvent(0x0?)
        github.com/gdamore/tcell/v2@v2.6.0/tscreen.go:1105 +0x6a
main.(*ui).pollEvents(0xc0004c0000)
        github.com/gokcehan/lf/ui.go:626 +0x4d
created by main.newUI
        github.com/gokcehan/lf/ui.go:608 +0x345

goroutine 5 [chan receive, 434 minutes]:
main.newApp.func1()
        github.com/gokcehan/lf/app.go:51 +0x35
created by main.newApp
        github.com/gokcehan/lf/app.go:50 +0x1cd

goroutine 7 [chan receive]:
main.(*nav).dirPreviewLoop(0xc0004de000, 0xc0004c0000)
        github.com/gokcehan/lf/nav.go:668 +0x5f
created by main.(*app).loop
        github.com/gokcehan/lf/app.go:245 +0x12a

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x7f1bd4f5f998, 0x72)
        runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0000d2000?, 0xc0004ee080?, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0000d2000, {0xc0004ee080, 0xf80, 0xf80})
        internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc0000d2000, {0xc0004ee080?, 0xc00050ede0?, 0x7f1bfc2d6a68?})
        net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000012008, {0xc0004ee080?, 0x0?, 0x7f1bfc2d6a00?})
        net/net.go:183 +0x45
bufio.(*Scanner).Scan(0xc00050ef50)
        bufio/scan.go:214 +0x876
main.readExpr.func1()
        github.com/gokcehan/lf/client.go:85 +0x210
created by main.readExpr
        github.com/gokcehan/lf/client.go:69 +0x6a

goroutine 9 [select]:
main.(*ui).pollEvent(0xc0004c0000)
        github.com/gokcehan/lf/ui.go:1120 +0xab
main.(*ui).readExpr.func1()
        github.com/gokcehan/lf/ui.go:1403 +0x25
created by main.(*ui).readExpr
        github.com/gokcehan/lf/ui.go:1401 +0x56

goroutine 225 [runnable]:
syscall.ByteSliceFromString({0xc00046a240, 0x1b})
        syscall/syscall.go:48 +0xb3
syscall.BytePtrFromString(...)
        syscall/syscall.go:68
syscall.openat(0x4b68fb?, {0xc00046a240?, 0xc00041eae0?}, 0x0?, 0x0)
        syscall/zsyscall_linux_amd64.go:79 +0x3c
syscall.Open(...)
        syscall/syscall_linux.go:272
os.openFileNolog({0xc00046a240, 0x1b}, 0x0, 0x0)
        os/file_unix.go:226 +0x9b
os.OpenFile({0xc00046a240, 0x1b}, 0x0, 0x0?)
        os/file.go:326 +0x45
os.Open(...)
        os/file.go:306
main.readdir({0xc00046a240, 0x1b})
        github.com/gokcehan/lf/nav.go:52 +0x45
main.newDir({0xc00046a240, 0x1b})
        github.com/gokcehan/lf/nav.go:159 +0x5f
main.(*nav).checkDir.func1()
        github.com/gokcehan/lf/nav.go:504 +0x37
created by main.(*nav).checkDir
        github.com/gokcehan/lf/nav.go:503 +0x33e
```

**Comment by ilyagr** [comment]
I think the first error points to this line:

https://github.com/gokcehan/lf/blob/a9d90bc56044aa5edeb2b45c161af3c0099a3bed/nav.go#L1936

This is entirely a guess, but perhaps another goroutine changed the selection as the loop was running?

**Comment by ilyagr** [comment]
Also, judging by the threads that are running, it might be some interaction between the previewer script and `qmv`. Again, this is a wild guess; I don't really know how to debug this.

**Comment by joelim-work** [comment]
I did some investigation, file previews are handled by a separate thread which runs the following code:

https://github.com/gokcehan/lf/blob/e885abe1a3f6a0a6a795f7f75f601c80566a3de2/nav.go#L683-L715

Before invoking the `cleaner` and `previewer` scripts, the thread calls `nav.exportFiles` which exports the current selections (and some other information) as environment variables so they can be accessed by the scripts. Unfortunately, the selections are supposed to be managed by the main thread (e.g. the user `toggle`s a file), which means the design isn't thread-safe.

I wasn't really sure why the file selections had to be exported - you only really need the path of the current file to be cleaned/previewed plus the window coordinates, and these are already provided as positional arguments. Apparently this was requested in #626. I only briefly looked through the issue, but it did seem kind of strange because the user simply just wanted to know the path of the next file to be previewed in the `cleaner` script, and that could have been solved by just passing in `path` variable.

TBH I don't think the use case in #626 makes much sense anyway. If you're currently displaying an image preview, and the image for the next file is *smaller*, then you have to clean up the old preview or else you will now see both images with one on top of the other.

**Comment by gokcehan** [comment]
@joelim-work Thank you very much for investigating this issue. To add on top of what you say, it seems that #626 was intended for `ueberzug` which is not maintained anymore. I'm not sure if exporting is useful for other image preview methods or not. If it is not useful, then I think we can consider removing it, especially if it causes severe issues such as this one.

**Comment by joelim-work** [comment]
> @joelim-work it seems that #626 was intended for `ueberzug` which is not maintained anymore. I'm not sure if exporting is useful for other image preview methods or not.

That is not completely true - `ueberzug` only requires the image dimensions (x, y, h, w) and the path of the image file, which is the same as any other image preview method., and what you would expect. The idea of #626 is to export additional information to customize the logic for the cleaner script (in this case whether to clear the existing preview or not), and is not specific to `ueberzug` or any particular method.

I am leaning towards removing the export since the current implementation isn't thread-safe, but this is sort of technically removing a (somewhat broken) feature and I'm worried there may be users that depend on this. Hopefully there aren't too many users though, since this does sound like a rather niche use-case. I'm happy to leave it to your judgement.

BTW although it's true that the original `ueberzug` project is no longer maintained, there are a couple of forks that are active - I have updated this information in the [wiki](https://github.com/gokcehan/lf/wiki/Previews).

**Comment by gokcehan** [comment]
@joelim-work I have taken a look at this again and I agree we should simply remove the export at this point. As much as I hate to make a breaking change, this issue too important to pass since deleting a random file is the worst thing imaginable for a file manager.

I'm not too familiar with image previews myself but I have looked through the examples and linked projects in our preview wiki page and I haven't seen any use of `$f` anywhere. So hopefully it is indeed a niche use case that won't effect many users. Nevertheless, I'll ping the previous users involved with this change in case they are still around (cc @build2stone @lucas-mior).

I'll also pin the issue for a while for more visibility.

One thing I'm not sure is that do we also need to remove the export of the options? It seems that this was introduced in #468 by @gotroyb127

**Comment by build2stone** [comment]
Thanks for the ping.
I use this feature here: https://github.com/build2stone/voidrice/blob/21dd3974aec2d942df4d62538deba91e74992a54/.config/lf/clear_img.sh#L16
It's quite handy to avoid preview flicker, but I don't have the impression that it's widely used.
I agree that it should be removed rather than risk deleting random files.

**Comment by joelim-work** [comment]
@build2stone I can see the use case for exporting the current file to prevent flickering. However I think there's no need to do this by calling `nav.exportFiles`. The current file to be previewed is already passed to the `nav.previewChan`, so we can just use that instead of `$f`.

Below is what I would propose, but I haven't tested this yet. We would also need to check directory previews as well.

```diff
diff --git a/nav.go b/nav.go
index 4d3fc3f..cc39fce 100644
--- a/nav.go
+++ b/nav.go
@@ -702,13 +702,13 @@ func (nav *nav) previewLoop(ui *ui) {
 		}
 		win := ui.wins[len(ui.wins)-1]
 		if clear && len(gOpts.previewer) != 0 && len(gOpts.cleaner) != 0 && nav.volatilePreview {
-			nav.exportFiles()
 			exportOpts()
 			cmd := exec.Command(gOpts.cleaner, prev,
 				strconv.Itoa(win.w),
 				strconv.Itoa(win.h),
 				strconv.Itoa(win.x),
-				strconv.Itoa(win.y))
+				strconv.Itoa(win.y),
+				path)
 			if err := cmd.Run(); err != nil {
 				log.Printf("cleaning preview: %s", err)
 			}
```

Regarding the exporting of options, I guess that is also technically not thread-safe, but I guess options are less likely to be an issue since they change less frequently than file selections. Also, I'm still not actually sure how the crash would cause files to be deleted, I'm not sure whether it's a problem with `lf` or the user's configuration.

In any case, I'm happy to leave this discussion around for a bit in case anyone else wants to comment, before I make any changes.

**Comment by joelim-work** [comment]
I finally got around to submitting a PR for this, see #1354. I was going to wait for a bit, but it looks like there isn't much updates in this discussion, and a similar discussion is taking place in #674.
