### ISSUE TITLE
Is it possible to disable default status info?

### ISSUE THREAD

**Issue by tex** [gokcehan/lf#1330]
I mean, the line showing file rights, file size, ...

I am trying to use on-select to get custom status info and as it is now it is not very aesthetic (refreshing line two times doesn't look nice).

**Comment by og900aero** [comment]
I built from source with this command on Debian 12:
env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest

When run lf, I get error message in log -> error: unknown option: fileinfofmt

**Comment by joelim-work** [comment]
@og900aero That means you have defined `fileinfofmt` somewhere in your config file, which isn't valid. `fileinfofmt` was the originally proposed name for this option when #1288 was under development, but this has now been renamed to `statfmt`.

**Comment by og900aero** [comment]
> @og900aero That means you have defined `fileinfofmt` somewhere in your config file, which isn't valid. `fileinfofmt` was the originally proposed name for this option when #1288 was under development, but this has now been renamed to `statfmt`.

I renamed to statfmt:

`set statfmt "\033[7;31m %p \033[32m %c \033[33m %u %g \033[34m %s \033[35m %t \033[36m %L \033[0m"`

And now working great. Thx!

**Comment by tex** [comment]
Thanks!

**Comment by joelim-work** [comment]
@og900aero To be clear, the `statfmt` option just uses simple string substitution, and `%l`/`%L` actually expand to just the link target without any surrounding spaces if present, otherwise an empty string. In your case the statline gets converted from `\033[36m %L \033[0m` to `\033[36m  \033[0m` because `%L` is replaced with an empty string, hence the visible background color.
