### ISSUE TITLE
on-select is not triggered when cursor on last line

### ISSUE THREAD

**Issue by tex** [gokcehan/lf#1332]
Hello, $SUBJ.

**Comment by joelim-work** [comment]
@tex `on-select` seems to trigger fine for me, at least when I test with something simple like `cmd on-select %echo "$f"`. Can you provide things like config files and steps to reproduce?

**Comment by tex** [comment]
You are correct. on-select is not triggered when I mark (with space) a file on last line.
My on-select cmd computes total size of $fx files.
Any workaround? Or triggering on-select on marking a file too?
I just need a visual indication of total size of selected files, automatically. With my script preferably.

**Comment by tex** [comment]
And the same for 'v' (mark all)...

**Comment by joelim-work** [comment]
OK I see your problem.

The name `on-select` is somewhat misleading, it is actually triggered when you move the cursor to a different file (e.g. up/down using `j` and `k`), not when you change the list of selected files using `space` and `v`. This means that when you are on  the last file, pressing `space` will add it to the selection list, but because the cursor hasn't moved, `on-select` isn't triggered.

There's currently no hook for when the selection list changes, I don't recall anyone requesting such a feature before. Anyway, I guess you can work around this by altering your keybindings to additionally trigger your script:

```
set statfmt ""

cmd sum-files %{{
    s=$(find $fx -type f -maxdepth 1 -ls | awk '{total += $7} END {print total}' | numfmt --to=iec --format='%.2fB')
    printf "> $s"
}}

map <space> :toggle; down; sum-files
map v :invert; sum-files
```

**Comment by tex** [comment]
I solved it with;

```
set statfmt ""

cmd on-select %{{
    s=$(find $fx -type f -maxdepth 1 -ls | awk '{total += $7} END {print total}' | numfmt --to=iec --format='%.2fB')
    printf "> $s"
}}

map <space> :toggle; on-select; down;
map v :invert; on-select;
```

Works for me, yes I know the size of files is computed twice when <space> but statfmt is draw always so I can't have only 'something' instead of on-select as any move would place empty on status line...

**Comment by tex** [comment]
I wrote my answer at the same time as you :)

I tried your solution but when I move cursor the sum of files is replaced with "". I want to keep that info when moving too.
