### ISSUE TITLE
custom on-select triggers file preview twice

### ISSUE THREAD

**Issue by tex** [gokcehan/lf#1333]
I have this in lfrc

```
set statfmt ""

cmd on-select %{{
    s=$(find $fx -type f -maxdepth 1 -ls | awk '{total += $7} END {print total}' | numfmt --to=iec --format='%.2fB')
    printf "> $s"
}}
```

and I am using kitty to preview images, movies, ...

```
set previewer ~/.config/lf/lf_kitty_preview
```

```
#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

filetype="$(file -Lb --mime-type "$file")"

if [[ "$filetype" =~ ^image ]]; then
    kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"
    exit 1
fi
```

When I have on-select enabled, then lf shows image preview twice. It causes not pleasant flickering.
Wehn I disable this on-select, then lf shows image preview only once as it should.

**Comment by joelim-work** [comment]
Thanks, I managed to reproduce the issue. The problem is that after a `%` command finishes, it triggers a `load` command which ends up refreshing the image preview: https://github.com/gokcehan/lf/blob/dc2627de23647b0a0d1fa13d4c039ac075db175c/app.go#L587

This is the implementation of the `load` command: https://github.com/gokcehan/lf/blob/dc2627de23647b0a0d1fa13d4c039ac075db175c/eval.go#L1755-L1760

Note that the `true` argument for `app.ui.loadFile` means 'volatile' which will cause the image preview to refresh. I'm very tempted to change this to `false`, but  the `load` command is used in other places and I'm not sure whether it will break something. At the very least the `load` following a `%` command should be non-volatile in my opinion, this has actually been discussed previously in https://github.com/gokcehan/lf/pull/1281#issuecomment-1575444672.

**Comment by tex** [comment]
That makes sense.

If % command wants to refresh it can issue lf -remote "reload/redraw"...
