### ISSUE TITLE
open does not always pass a $f

### ISSUE THREAD

**Issue by jneidel** [gokcehan/lf#1364]
## Setup

I have this `fzf_file` command mapped:
```sh
cmd fzf_file ${{
  pick() {
    fzf
  }
  local picked=$(pick)
  echo "\$picked=$picked"
  lf -remote "send $id :select '~/$picked'; open"
}}
```

And this open command:
```sh
cmd open ${{
  echo "\$f='$f' \$fx='$fx'"
  ~/scripts/mime/mime -e lf open "$f" || lf -remote "send $id open"
}}
```

## How it fails

Calling `fzf_file` I get inconsistent results. Sometimes the file will open, sometimes not (the [ERR] msg). As you can see the `$picked` is correct, but `$f` and `$fx` are empty, until they are not. The amount of retries it takes varies (I've seen 0 to 7). 

```sh
# calling fzf_file via binding
$picked=org/3_resources/rücken.norg
$f='' $fx=''
[ERR] file does not exist: /home/jneidel/org/3_resources/open
$f='' $fx=''
[ERR] file does not exist: /home/jneidel/org/3_resources/open
$f='' $fx=''
[ERR] file does not exist: /home/jneidel/org/3_resources/open
$f='' $fx=''
[ERR] file does not exist: /home/jneidel/org/3_resources/open
$f='' $fx=''
[ERR] file does not exist: /home/jneidel/org/3_resources/open
$f='' $fx=''
[ERR] file does not exist: /home/jneidel/org/3_resources/open
$f='/home/jneidel/org/3_resources/rücken.norg' $fx='/home/jneidel/org/3_resources/rücken.norg'
# success
```

Having this retry mechanism works, but it's not ideal :smile:

**Comment by joelim-work** [comment]
The problem is that `lf` loads directories *asynchronously*, if it hasn't been visited before. This means that if you try to `open` the file immediately after using `select`, `lf` will have changed to the containing directory, but `$f` is empty because the contents of that directory have not been loaded yet.

I would suggest to either:

- Open the file directly inside your `fzf_file` command, instead of calling `open`
- Just have `fzf_file` select the file, and then manually `open` the file afterwards (e.g. by pressing `l`)

**Comment by jneidel** [comment]
I went for select + calling my open script directly :+1:

Thanks for the tip and explanation!
