### ISSUE TITLE
Colours on Windows cmd are unusable

### ISSUE THREAD

**Issue by eggbean** [gokcehan/lf#1383]
I was looking for something like `ranger` that can be used on Windows and found this. I installed it through scoop, but the colours on my terminal make it unreadable.

The instructions only mention Linux locations, so I am not sure what to do here.

Also, I have `LS_COLORS` set on cmd.exe, so I was hoping that `lf` could use those, unlike `ranger`.

![image](https://github.com/gokcehan/lf/assets/815311/e2f6f808-810e-47a5-ac8b-be8a3af92122)

**Comment by joelim-work** [comment]
`LS_COLORS` should work on Windows. If you want to override them you can create a colors config file, the locations are actually mentioned in the [documentation](https://pkg.go.dev/github.com/gokcehan/lf#hdr-Configuration).

**Comment by ilyagr** [comment]
I think the problem is that `lf` treats all the files as having executable bits set. You might want to setup LS_COLORS so that executable files are shown the same as normal files. I'm not sure if there is a better way, this might depend on the filesystem you are using.

**Comment by eggbean** [comment]
Thanks. I have realised that only some directories appear like this, but not file and not all directories. It doesn't seem to have to do with which Linux mode of Windows attributes that these directories have. Very confusing.

![image](https://github.com/gokcehan/lf/assets/815311/49212401-20d0-4145-8bf8-e30f49c8b076)

**Comment by eggbean** [comment]
This is that same directory shown in Linux WSL

![image](https://github.com/gokcehan/lf/assets/815311/d4b66074-a3ba-4b17-8a1e-68d8e19a4782)

**Comment by joelim-work** [comment]
I'm kind of out of ideas if there's really nothing special about those directories.

If you really want to get to the bottom of this, you can have a look at the code which decides how the colors are applied: https://github.com/gokcehan/lf/blob/dd8294952f3cda8d8671847a5ab4dc3613a2aabd/colors.go#L274-L341

You can also try changing the code and recompiling if you have Go installed.

**Comment by gokcehan** [comment]
@eggbean Can you check which version are you running (i.e. `lf -version`)? There was a time we had background colors in our default colorscheme but we removed them a long time ago (in r10). Otherwise, there should be some configuration somewhere that use the background colors. In addition to `LS_COLORS`, please also check if you have `LSCOLORS` or `LF_COLORS` or a colors file in the corresponding configuration directory.

**Comment by eggbean** [comment]
```
F:\Users\jason>lf --version
r30
```
I don't have any colour profiles, but I do have `LS_COLORS` set. The colours are fine when I comment out my `LS_COLORS` definition, so it is being caused by that. I didn't realise this before.

As I want to use `LS_COLORS`, I tried adding an empty `LF_COLORS=` afterwards, but it makes no difference.

**Comment by eggbean** [comment]
I found the problem. By bisecting the long `LS_COLORS` definition I found that it this causing the problem:

    set LS_COLORS=ow=34;42

ow is other-writable.

**Comment by joelim-work** [comment]
`ow` just simply means the entry is a directory and has the other-writable bit (002) set.

So I tested this on my Windows setup and also found that there were certain directories that has this bit set and others that didn't. I just never noticed it before since the default color for `di` and `ow` are the same. I'm not actually sure how Go maps permissions from NTFS to Unix, but I suspect it's an internal implementation detail, and also other tools like `exa` will give a different result so they actually add to the confusion.

If the distinction between `di` and `ow` isn't important and you don't want to change `LS_COLORS`, you should be able to override it by defining `LF_COLORS` or creating a colors config file as mentioned above.

**Comment by eggbean** [comment]
I just removed the definition for other-writable as it's not really relevant on NTFS as far as I can tell. Cheers.
