### ISSUE TITLE
lfrc.ps1.example Has error on <enter> because of <> characters.

### ISSUE THREAD

**Issue by MrDowntempo** [gokcehan/lf#1396]
I use PowerShell (I'm on 7.3.6) and am attempting to setup LF to play nice. The file [etc/lfrc.ps1.example](https://github.com/gokcehan/lf/blob/master/etc/lfrc.ps1.example) is a good start, however the line:
`map <enter> shell`
gives the error:
`unknown mapping: <enter> `
Which, to me seems like an issue PowerShell has with the <> characters.  Googling led me to many other PowerShell users who happened to stumble on a command with a < in it, and needing to instead run the command using cmd. Obviously that's not going to be the necessary solution here.  I think just an option for a different alias to <enter> without to <> characters could work?

It does seem that using
`map '<enter>' shell`
may be a work around, but I'm still testing.

**Comment by joelim-work** [comment]
The error message `unknown mapping: <enter>` means you pressed <kbd>enter</kbd> but it isn't mapped to anything. I doubt this is an issue with PowerShell since the `lfrc` file is parsed by `lf`, and not PowerShell.

You might want to check that your `lfrc` file is placed in the correct location and is actually being read by `lf`.

**Comment by MrDowntempo** [comment]
> The error message `unknown mapping: <enter>` means you pressed <kbd>enter</kbd> but it isn't mapped to anything. I doubt this is an issue with PowerShell since the `lfrc` file is parsed by `lf`, and not PowerShell.
> 
> You might want to check that your `lfrc` file is placed in the correct location and is actually being read by `lf`.

I posted the line of code where I do map enter and shown that the < character is where it errors, and that the single quotes corrected the error for me. So it is being parsed by lf, and other aspects of the file I can confirm are also being used by commenting them out and seeing the changes.

**Comment by joelim-work** [comment]
I have some more questions:

- Do you get that error message when you start `lf`, or when you actually press <kbd>enter</kbd>?
- The `maps` command (type `:maps`) can be used to display all keybindings if you have a pager setup, does it show an entry for `<enter>`?
- What happens if you manually map this from the command line after starting `lf` (type `:map <enter> shell`)?
- What happens if you delete everything from your config file except for the `map <enter> shell` line?
- Can you provide a minimal config file (i.e. delete all the unnecessary stuff and leave in only what is required to reproduce this issue)?
