### ISSUE TITLE
How to change a drive on Windows?

### ISSUE THREAD

**Issue by muellerto** [gokcehan/lf#142]
I couldn't figure out how to change the drive. If I open up lf on c:\something\mydir and I want to change not to e:\my_projects\most_important it says something about "couldn't find directory".

I used the following notations:
e:\directory
e:/directory
e\directory
e/directory
/e/directory

What is right?

**Comment by gokcehan** [comment]
@muellerto You need quotes around the path, otherwise `:` and `\` characters are confused in our parser:

    cd 'e:\directory'

I realized autocompletion is not being helpful for paths including `\` on windows. Also maybe `\\` should be escaped as `\` without the quotations. I will check the parser to see if we can do something about this.

**Comment by muellerto** [comment]
Yes, that works, single quotes, thanks.

**Comment by sach2** [comment]
I think this can be closed.

**Comment by gokcehan** [comment]
@sach2 I haven't closed this issue yet because I want to improve autocompletion for this purpose though I haven't got the chance to have a look at this on my windows machine so far.

**Comment by gokcehan** [comment]
@sach2 I have made some changes to automatically add double backlashes for autocompletion on windows. We should ideally have an alternative autocompletion behavior triggered when the filename starts with a quote (e.g. `cd 'C:\Users\<tab>`) which should not escape whitespaces and backslashes but this is not specific to windows. Anyway closing this issue now.
