### ISSUE TITLE
lf can't preview long line strings

### ISSUE THREAD

**Issue by gaesa** [gokcehan/lf#1446]
Hello,

I’ve encountered an issue where lf fails to display a line generated by a preview program when the line length reaches or exceeds 65536 characters. This issue is particularly noticeable when previewing compact JSON files.

To clarify, this seems to be an issue with `lf`, not the `bat` command used in the preview program. I’ve tested the `bat --color=always -pp -- longline.txt` command directly in the terminal, and it works fine. The long line is printed without any issues.

**Version**: 31

**Operating System**: Arch Linux

**Installation Method**: I installed lf using the command `sudo pacman -S lf`.

**Steps to Reproduce**:
1. Set your preview program to preview a text file using the command: `bat --color=always -pp -- your_file`.
2. Open lf and attempt to preview the file [longline.txt](https://github.com/gokcehan/lf/files/12735598/longline.txt).

**Expected Behavior**: lf should be able to display long line strings generated by a preview program, regardless of their length.

**Actual Behavior**: lf fails to display any line that contains 65536 characters or more.

**Comment by joelim-work** [comment]
This actually doesn't have anything to do with `bat`, I can reproduce the same issue using the default preview method.

The reason this happens is because `lf` uses [`bufio.Scanner`](https://pkg.go.dev/bufio#Scanner) to read the file line by line, which is limited by the size of its internal buffer [`MaxScanTokenSize`](https://pkg.go.dev/bufio#MaxScanTokenSize). If a line exceeds the size of the buffer then the scanning terminates.

https://github.com/gokcehan/lf/blob/dddf437c42a5e61afefaae6bb39f0c484cd2f0e0/nav.go#L892-L906

**Comment by gaesa** [comment]
I was wondering if it might be possible to consider an alternative approach. Instead of terminating the preview when a line exceeds the buffer size, perhaps `lf` could truncate the line and continue displaying it partially. This could potentially be accompanied by a subtle note or symbol indicating that the line has been truncated due to its length.

**Comment by joelim-work** [comment]
I agree that lines should be displayed even if they exceed the buffer length. Actually in this case there's no point in displaying any message since the preview window can only fit about 100 characters anyway, and you won't notice the difference.

Would you be able to try out the branch in https://github.com/joelim-work/lf/tree/preview-long-lines and see if it works for you? If it does then I might submit it as a PR.

**Comment by gaesa** [comment]
I’ve tested the branch at https://github.com/joelim-work/lf/tree/preview-long-lines and I am content with the behaviour now. It works well and I agree there’s no need for a truncation message. Thank you for your efforts in addressing this issue.

**Comment by joelim-work** [comment]
Thanks, I have submitted PR #1447
