### ISSUE TITLE
[bug]: the contents of lf history file keeps getting overwritten

### ISSUE THREAD

**Issue by noornee** [gokcehan/lf#1450]
I've noticed this issue for a while now but i never took the time to find out the cause. Today i decided to get a bit Sherlocky and figure out what's causing my history file from getting overwritten but i couldn't quite pin it down. What could possibly be the cause ?

if i exit `lf` with the `q` keypress. it doesn't cause any issue. that behavior is normal---

buttt i have this habit of closing(killing) my terminal emulator every time i'm done with something.
quitting `lf` (with `q`) and closing my terminal emulator in two different keystrokes is a long process so i just close my terminal emulator along with whatever's running with a keybinding.

in some cases when i kill the current active terminal emulator with `lf `running in that instance, the history file doesn't get cleared
and in another situation the opposite happens

## normal behavior (history file remains intact after killing terminal emulator)
[good.webm](https://github.com/gokcehan/lf/assets/71889751/1f19a382-a334-4573-9c5a-bb0ee1a4979a)

## unpredictable behavior (history file gets cleared)
[bad.webm](https://github.com/gokcehan/lf/assets/71889751/ce480be3-811d-4068-8f75-ea1df35d25ff)

**Comment by joelim-work** [comment]
`lf` uses [`os.Create`](https://pkg.go.dev/os#Create) to open the history file for writing, which truncates the file if it already exists: https://github.com/gokcehan/lf/blob/dddf437c42a5e61afefaae6bb39f0c484cd2f0e0/app.go#L220

I'm guessing that killing your terminal somehow causes `lf` to terminate ungracefully, potentially preventing it from actually writing the history data after the file is opened.

I guess one idea might be to make the write operation atomic, by writing to a temp file first and then renaming it to the actual history file path. But even then, the history from the current session would still be lost, and I'm not sure if it's worth making this change or not.

Alternatively, can't you launch your terminal to start with `lf` instead of a shell? That way you should be able to quit `lf` normally and then your terminal will automatically quit as well.

**Comment by noornee** [comment]
> I'm guessing that killing your terminal somehow causes `lf` to terminate ungracefully, potentially preventing it from actually writing the history data after the file is opened.

hmm, i seeee
> 
> Alternatively, can't you launch your terminal to start with `lf` instead of a shell? That way you should be able to quit `lf` normally and then your terminal will automatically quit as well.

Thanks for this idea, i tried it and it works!
left me wondering why i didn't do this from the beginning since i launch `lf` almost every time i open my terminal.

but there are situations where i quit `lf` to run commands on my terminal and i do know that `lf` has this prompt to input external commands but--- i suppose i just have to get used to quitting `lf` normally without killing it alongside my terminal emulator. Thanks again for your time!

```zsh
# added this to the bottom of my .zshrc file (works)
# pressing q quits lf and my terminal
exec lf
```

```zsh
# doing just this makes image previews not work
# pressing q quits lf and returns me back to my shell and i see traces of the images i tried previewing
lf
```

**Comment by joelim-work** [comment]
You should be able to start your terminal with a specific program just by passing it in the command line options, instead of having to change your shell rc file, for example `alacritty -e lf`. You can also setup separate keybindings to start your terminal normally and start your terminal with `lf`.

In any case I think it might be better if you avoid killing your terminal directly as you could run into cleanup issues with other programs, though I'm not completely sure about this and the behavior might vary between different terminals.

**Comment by noornee** [comment]
> You should be able to start your terminal with a specific program just by passing it in the command line options, instead of having to change your shell rc file, for example `alacritty -e lf`. You can also setup separate keybindings to start your terminal normally and start your terminal with `lf`.
> 
whoaa, i totally forgot about this!
i'm no longer using alacritty since it doesnt support previewing images with sixel so it tried it with wezterm and it worked

> In any case I think it might be better if you avoid killing your terminal directly as you could run into cleanup issues with other programs, though I'm not completely sure about this and the behavior might vary between different terminals.

alrighttt, i would avoid that. Thank you.
should i close this issue as not planned or leave it as is? (since the fault is actually from me killing my terminal)

**Comment by joelim-work** [comment]
I think we can close the issue, they can always be reopened anyway if further discussion is required. I can close this for you.
