### ISSUE TITLE
Set previewer and cleaner to paths with environment variable in them

### ISSUE THREAD

**Issue by Lassebq** [gokcehan/lf#1453]
```
set previewer "$XDG_CONFIG_HOME/lf/previewer"
set cleaner "$XDG_CONFIG_HOME/lf/cleaner"
```
At the moment it seems to only support absolute paths and paths relative to `~`

**Comment by joelim-work** [comment]
I think this might be a deliberate design decision in that `lf` expands `~` for convenience, but does not expand environment variables as the syntax varies between different shells (e.g. Windows CMD).

But you still can achieve this by calling `lf -remote` in a shell command:

```
${{
    lf -remote "send $id set previewer $XDG_CONFIG_HOME/lf/previewer"
    lf -remote "send $id set cleaner $XDG_CONFIG_HOME/lf/cleaner"
}}
```

**Comment by Lassebq** [comment]
Why not support both? It's very unlikely that you're going to use the same configuration file on windows as you do on Linux. Expand $VAR on Linux and expand %VAR% on Windows.

**Comment by joelim-work** [comment]
So I did a search of the issue tracker, and it turns out someone else asked the exact same thing in #786. The recommendation given there is the same as what I have given here.

I imagine the problem with supporting variable expansion like `$FOO` is that it opens the floodgates for more complex expansions, and users will invariably request other syntaxes such as:
- `${FOO}` (for clarity/separation)
- `${FOO:-bar}` (default values)
- `${FOO#PREFIX}`/`${FOO%SUFFIX}` (removing prefixes/suffixes)
- `\$` (literal `$`)

While I don't think it is impossible to implement all of this directly inside `lf`, I think doing this is harder to justify, given that shells are also capable of variable expansion and that the task can instead be delegated to them. In contrast, `~` is much simpler to expand, and is actually useful when typing on the command line because it is shorter (e.g. `:cd ~/foo/bar`).

I suspect that subsequent discussion is going to be somewhat opinionated, as there will be users who don't plan on changing their config path and are happy to hardcode the value `~/.config`, users who don't mind using `$lf -remote` to expand variables, users who place their `previewer`/`cleaner` scripts in their `PATH` and therefore don't care, and users who insist on having `lf` support variable expansion directly.

**Comment by joelim-work** [comment]
I can't promise anything, but if you want you can keep this issue open and see if anyone else has something to add to the discussion.

**Comment by Lassebq** [comment]
I'll keep the issue open. If anything I'd evaluate string with currently specified shell

**Comment by joelim-work** [comment]
> If anything I'd evaluate string with currently specified shell

I guess that might not be such a bad idea. The following patch might be what you are looking for, although it does feel slightly hacky and I didn't test it very much:

```diff
diff --git a/eval.go b/eval.go
index ff04308..ca44dfd 100644
--- a/eval.go
+++ b/eval.go
@@ -61,7 +61,7 @@ func (e *setExpr) eval(app *app, args []string) {
 	case "borderfmt":
 		gOpts.borderfmt = e.val
 	case "cleaner":
-		gOpts.cleaner = replaceTilde(e.val)
+		gOpts.cleaner = evalShellString(e.val)
 	case "cursoractivefmt":
 		gOpts.cursoractivefmt = e.val
 	case "cursorparentfmt":
@@ -635,7 +635,7 @@ func (e *setExpr) eval(app *app, args []string) {
 		gOpts.preview = !gOpts.preview
 		app.ui.loadFile(app, true)
 	case "previewer":
-		gOpts.previewer = replaceTilde(e.val)
+		gOpts.previewer = evalShellString(e.val)
 	case "promptfmt":
 		gOpts.promptfmt = e.val
 	case "ratios":
diff --git a/misc.go b/misc.go
index b38dab2..5580aef 100644
--- a/misc.go
+++ b/misc.go
@@ -4,6 +4,7 @@ import (
 	"bufio"
 	"fmt"
 	"io"
+	"log"
 	"path/filepath"
 	"regexp"
 	"strconv"
@@ -22,6 +23,16 @@ func replaceTilde(s string) string {
 	return s
 }
 
+func evalShellString(s string) string {
+	out, err := shellCommand("echo "+s, nil).Output()
+	if err != nil {
+		log.Printf("evalShellString: %s", err)
+		return ""
+	}
+
+	return strings.TrimSpace(string(out))
+}
+
 func runeSliceWidth(rs []rune) int {
 	w := 0
 	for _, r := range rs {
```

**Comment by joelim-work** [comment]
An update on this:

I managed to create a wrapper for the `set` command, which uses `eval` to substitute variables, and then passes the result back using `lf -remote`:

```
cmd set-expand &{{
    IFS=" "
    args=$(eval "echo $*")
    lf -remote "send $id set $args"
}}

set-expand previewer "$XDG_CONFIG_HOME/lf/previewer"
set-expand cleaner "$XDG_CONFIG_HOME/lf/cleaner"
```

This hides the complexity in a separate command, and keeps the actual configuration syntax clean.

TBH I'm still not 100% certain about implementing variable substitution as built-in functionality. My understanding is that there's no way to achieve this portably (when taking Windows CMD/PowerShell into consideration) without having to write specific code to handle each shell, and `lf` is designed to be shell-agnostic.

---

The above technique can be generalized into an `eval` utility command (haven't tested thoroughly). @gokcehan you might find this idea interesting.

```
cmd eval &{{
    IFS=" "
    args=$(eval "echo $*")
    lf -remote "send $id $args"
}}
```

Expand variables:

```
:eval echo '$HOME'
```

Expand variables with default values:

```
:eval echo '${FOO:-bar}'
```

Perform command substitution:

```
:eval echo '$(date)'
```

**Comment by gokcehan** [comment]
@joelim-work That `eval` utility seems quite interesting. Thank you for coming up with this idea. I think it could definitely be useful to have it somewhere in the doc, wiki, and/or the example config file. If I understand it right, you can then use `eval set previewer "$XDG_CONFIG_HOME/lf/previewer"` instead of a separate `set-expand` command.

**Comment by joelim-work** [comment]
@gokcehan Yes that's correct. There's already a section in the wiki called [Use enviromental variable in command or mapping](https://github.com/gokcehan/lf/wiki/Tips#use-enviromental-variable-in-command-or-mapping), so I just added my `eval` utility command there.

With this in mind, do you still see any possibility that variable expansion would be implemented directly in `lf`, and whether it's worth keeping this issue open or not?

**Comment by gokcehan** [comment]
@joelim-work If you are asking me, I think it was fine even before you come up with a dedicated `eval` command for this purpose, so I would prefer we don't add anything further for the variable expansion.

@Lassebq Are you satisfied with this solution?

**Comment by Lassebq** [comment]
Good enough 👍
