### ISSUE TITLE
Change archivemount integration on the Wiki

### ISSUE THREAD

**Issue by alejoguitar** [gokcehan/lf#1458]
Since on newer versions, lf has an `on-quit` command, there's no need to a wrapper script for the `archivemount` integration.

This way, it's only needed to just copy and paste the relevant lines on the wiki to the on-exit command. Here's what I did on my config, and it works:
```

archivemount_dir="/tmp/__lf_archivemount_$id"
if [ -f "$archivemount_dir" ]
	then
		cat "$archivemount_dir" | while read -r line
		do
			sudo umount "$line"
			rmdir "$line"
	done
	rm -i -f "$archivemount_dir"
fi
```

BTW: the `umount` requiring `sudo` could be replaced by 
			`fusermount -u "$line"`

In my config, it works perfectly well and its much more easy. I'm not sure why is the other way on the wiki but I assume there is a reason.

The "open " command remains the same, so It would be just a small update to the wiki.

**Comment by joelim-work** [comment]
Would there any issue with `umount` if you quit `lf` while you are _inside_ the mounted directory? Otherwise I can't think of a reason why `on-quit` can't be used.

**Comment by alejoguitar** [comment]
Good point. So, I should add one more line to the `on quit` command

if [ -f "$archivemount_dir" ]
then
	cat "$archivemount_dir" | while read -r line
	do
                if [ "$line" = "$(pwd)" ]; then cd ..; fi
		sudo umount "$line"
		rmdir "$line"
	done
	rm -i -f "$archivemount_dir"
fi

**Comment by joelim-work** [comment]
Regarding `fusermount`, I'm fairly indifferent which one you use. Although I guess not everyone has `fusermount` installed so maybe you can mention that both `fusermount` and `sudo umount` can be used.

Anyway please test your example thoroughly to make sure there's no issues. If it does work then feel free to update the wiki example yourself. The wiki is actually open to all users so anyone can edit it - in the worst case scenario, all the previous version are saved anyway and can be restored.

**Comment by alejoguitar** [comment]
I think plain `umount` it's good enough, in fact. But I can't get the reasoning around the `sudo`. 
File is mounted on user space, so there should be no reason to use a root command, is it? I wonder why it was there on the first place...

OK, I'll check it out and if it works, I'll update the wiki.

**Comment by og900aero** [comment]
I use a simpler solution. The mtab file always contains the folder uploaded by the user:

```
cat /etc/mtab | grep archivemount | cut -f2 --delimiter=' ' | while read -r line
	do
       	    fusermount -u "$line"
            rmdir "$line"
        done
```

Musch easier and lighter resolution in my opinion.

**Comment by alejoguitar** [comment]
That's awesome. Much neater than adding a tmpfile unnecessary using the SSD.
Do you mind if I add it to the wiki?
@joelim-work I think I can close the issue with this and edit the wiki

**Comment by alejoguitar** [comment]
@joelim-work You were right from the beginning. If `lf`exits while being on the archivemount directory, there's no way to umnount if from within lf.
When `lf`exits while being at the *-archivemount directory, `fusermount` fails to unmount. Even `sudo umount` is no usable in this case, as `lf`exits without being possible to enter a password.

I think the most logical would be to make a remote call `lf -remote "send $id select [name-of-zip-file]` , then run the `fusermount -u` command.
For some reason this doesn't work. I think remote commands are not possible to execute on the on-quit command. I also tried (as mentioned in may previous comment) a simple cd ..

I guess only some modification on the code might do this possible? But I've not idea which.

**Comment by joelim-work** [comment]
@alejoguitar I had a look at this further.

What actually happens is that there are two processes involved, `lf` and the shell spawned from the `on-quit` command. **Both of these processes** have their CWD set to the mount directory (the shell is spawned from `lf` and will inherit its CWD), so even if you `cd` inside the shell, you will still not be able to unmount the directory because the parent `lf` process is still in there.

Therefore what you have to do is to have `lf` itself `cd` out of the directory before trying to unmount it, something like this:

```shell
map am ${{
    mntdir="${f}.am"
    mkdir -p "$mntdir"
    archivemount "$f" "$mntdir"
}}

cmd on-quit :cd; umount

cmd umount ${{
    awk '$1 == "archivemount" { print $2 }' /etc/mtab | while read -r mntdir
    do
        umount "$mntdir"
        rmdir "$mntdir"
    done
}}
```

I deliberately took a few shortcuts to keep the example concise and instructive:

- Mounting is done through a mapped keybinding, in order to separate it from the `open` command.
- The `/etc/mtab` file is used instead of maintaining a separate file. This does mean that any archive mounted outside of `lf` (or a different instance of `lf`) will also be unmounted, which may or may not be undesirable.
- Spaces in `/etc/mtab` paths are not handled.

BTW when I tested this, I found that `umount` without `sudo` worked perfectly fine for me, so I don't think there's any need to mention `fusermount -u` unless it provides some additional benefit.

**Comment by og900aero** [comment]
My full code for this:

```
cmd on-quit :{{
	cd ~
	unselect
	clear
	archiveunmount
}}

cmd archiveunmount &{{
	cat /etc/mtab | grep archivemount | cut -f2 --delimiter=' ' | while read -r line
		do
        	fusermount -u "$line"
            rmdir "$line"
        done
}}
```

This has worked for me in all circumstances so far. There was never a mistake or that he didn't do it.
I understand joelim-work that he doesn't like the mtab solution, since it takes place outside of lf, but let's consider that it's quite impractical that mtab also has the other archivemount connection that we need. I only use 1 file manager, and if I attach a compressed file, it is only to extract something from it or to look at it, and there is no need for it to remain there, my own code is suitable for me, and it follows the LF principle that the simpler the better, the lighter the code.

**Comment by joelim-work** [comment]
> I understand joelim-work that he doesn't like the mtab solution,

I'm not against using `/etc/mtab`, I just wanted to point out a potential flaw, which is possibly the reason why the current wiki example doesn't use it.

The only preference I really have is that the wiki examples should be simple and furthermore *instructive* (users should be intelligent enough to refine the code to suit their needs), as opposed to generalized, complex examples which users copy/paste into their config file and hope that it works. I'm not the biggest fan of the current example either TBH, since it conflates `archivemount` usage with concepts like `open`ing files and `lfcd`.

**Comment by alejoguitar** [comment]
@joelim-work I assumed that was one of the reasons (when I first tried just putting "cd" on my test command it didn't change directory. So I called a remote command 

```
file=$(echo $line | sed 's/-archivemount//' )
lf -remote "send $id select \"$file\""

```

but this just doesn't work, because `lf`doesn`t update it`s PWD or $f in between the commands. I tried putting all that stuff in a different command and calling the command from the `on-quit`, same result.
your example and @og900aero 's  just plain sends the shell to $HOME before unmounting, which would break the `lfcd` funcionality  (IMO this is especially relevant since the r31 version, as now the `lfcd` alias is much more simpler, but I still need to wrap the `lf`command in a long alias).
The `cd`command on your example could be replaced by a `cd ..` , but this should be only done if we are on an archivemount directory, and we can't use `if` statements on the read commands...

I imagine the best sequence of commands on a config file something like this:

```
cmd on-quit ${{
   awk '$1 == "archivemount" { print $2 }' /etc/mtab | while read -r mntdir
      do
		if [[ "$line" = "$PWD" ]]; then 
			file=$(echo $line | sed 's/-archivemount//' )
			lf -remote "send $id select \"$file\""
          umount "$mntdir"
          rmdir "$mntdir"
      done
}}

or maybe the -remote select could be done in a separate command, but neither of this config options are possible without tailoring the code. 
If you think such thing can be implemented and it's a relevant feature, I could post a feature request. If not, I guess I'll have to stick with the wrapper.

**Comment by joelim-work** [comment]
@alejoguitar I did not consider `lfcd` earlier, but you are right that it won't work, since the `on-quit` hook runs before the last directory is evaluated and printed. Calling `lf -remote` inside the `on-quit` hook doesn't work either because after this point `lf` will exit the main loop and won't be able to process any more commands. Also, the commands for `lf -remote` don't run immediately - they are sent to the main loop to be run afterwards, which means `umount` won't work anyway.

I think it might actually be best to keep this as a wrapper script like below:

```shell
#!/bin/sh

cleanup() {
    awk '$1 == "archivemount" { print $2 }' /etc/mtab | while read -r mntdir
    do
        umount "$mntdir"
        rmdir "$mntdir"
    done
}

trap cleanup EXIT

command lf "$@"
```

This does mean that the resulting directory wouldn't exist if it was inside an archive mount, in which case the `lfcd` script would have to `cd` into the parent directory instead:

```shell
alias lf=lfwrapper

lfcd() {
    dir=$(lf -print-last-dir "$@")
    while ! cd "$dir" 2> /dev/null
    do
        dir=$(dirname "$dir")
    done
}
```

**Comment by alejoguitar** [comment]
@joelim-work Thanks for the answer.
May I suggest a simpler approach, since `lfcd` will need extra lines. I already implemented that on my aliasrc and I think this should be the example written on the wiki, as it's the closest to the criteria you mentioned

**Comment by alejoguitar** [comment]
@joelim-work Thanks a lot for the answer. The `while` approach to `lfcd` is so elegant...!
(I'm quite noob to any scripting, BTW, so, I really appreciate your patience)

I stood with a simpler one, bundling everything on the alias

```
lfcd () {
                cd "$(command lf -print-last-dir "$@")"'
		awk '$1 == "archivemount" { print $2 }' /etc/mtab | sed 's/\\040/ /' | while read -r mntdir
		do
			if [[ "$mntdir" = "$PWD" ]]; then 
				cd ..
			fi
        		umount "$mntdir"
		        rmdir "$mntdir"
	      done
}
```
I think This changes config files to the mimimum, as it doesn't require an extra script (lfcd needs to be a shell alias anwyay).
But I assume not everybody actually uses an `lfcd` alias and your example is more portable, so to speak. Probably your example should be the one on the wiki. Is just that having three steps seems a little more difficult to understand.
I don't know.

**Comment by joelim-work** [comment]
Yeah the reason why I split the code like that was to ensure that the unmounting would happen for both `lf` and `lfrc`. I think it won't be too hard to understand, provided we add some additional sentences to explain each step.

Anyway if you like, you're welcome to write up the example in the wiki. If not then I'll get around to it some time later this week.

**Comment by alejoguitar** [comment]
Happy to do it :)  but also later this week

**Comment by joelim-work** [comment]
OK I have added the [example](https://github.com/gokcehan/lf/wiki/Integrations#archivemount), I think it's an improvement over the existing implementation, so I'm closing the issue. Feel free to fix any issues you find.
