### ISSUE TITLE
No preview for text files without extension in hidden folders

### ISSUE THREAD

**Issue by chris977** [gokcehan/lf#1465]
I can't preview, in the right preview pane, plane text files without extension that are located in hidden folders, e.g. `.config/lf/lfrc`. If I copy the file to `~/Documents` or some other visible folder, the preview is shown. If I add a .txt or .rc extension to the file in the hidden folder, the preview is shown.
My preview command for text mime types is: `text/*) highlight -O ansi "$1";;`. I also tried `*/*)` or `*) highlight -O ansi "$1";;` (without the mime type option).
I'm not sure if this is a bug or I need to add some setting.
I have lf version 31 from the Arch repos.

**Comment by joelim-work** [comment]
This is an issue with `highlight` (and not `lf`), most likely because it is not able to deduce the syntax based on the filename. I tried running `highlight ~/.config/lf/lfrc` and also got an error.

BTW you can test this by manually running the preview script *outisde of* `lf`, just pass the filename (specify as an absolute path) as the first argument.

**Comment by chris977** [comment]
Yes, that's it, thank you for the quick response. I added the `--syntax=all` option for `highlight`.
