### ISSUE TITLE
Wrong/Outdated Wiki entry: exa

### ISSUE THREAD

**Issue by drzhivago420** [gokcehan/lf#1467]
Currently, the Wiki/Integrations/exa part of the wiki lists this snippet:
```
cmd on-select &{{
    lf -remote "send $id set statfmt \"$(exa -ld --color=always "$f")\""
}}
```
I think there was a breaking change recently in how set statfmt works or something, so the snippet doesn't currently work.

The Wiki/Integrations/vim lf.vim link is dead too -> https://github.com/gboncoffee/lf.vim
I suggest this link instead -> https://github.com/ptzz/lf.vim

**Comment by joelim-work** [comment]
The `exa` snippet works for me. Although it is a slight hack to use formatted output as a *format string* in this way - if your filename contains any placeholders like `%p` then they will end up being replaced.

I think the breaking change you might be referring to is #1337? You can also search the issues and commit history for `statfmt`. If you're still having trouble, you can also post a screenshot or some other details because I can't reproduce otherwise.

---

As for `lf.vim`, I have removed the former link.

**Comment by drzhivago420** [comment]
![Screenshot_20231012_104643](https://github.com/gokcehan/lf/assets/110633694/2def6e03-db73-4bb3-ba4e-d827b549de71)

**Comment by drzhivago420** [comment]
Yes, I was just using an out of date lf version.
