### ISSUE TITLE
Del+Paste to another partition copies file instead of moving

### ISSUE THREAD

**Issue by krem** [gokcehan/lf#1472]
Del+Paste to same partition works as expected, while Paste to another partition copies files (with new timestamp) instead of moving (keeping timestamp)

**Comment by DusanLesan** [comment]
As a user, I would think that is expected. I think, when you are moving file within the same partition, file written to drive would remain in the same place and only pointer to it would be changed, but when you move to different partition we need to move the file itself also (so basically it is modified). It should also be noticeable in the speed of the operation since if you move within the same partition it would be much faster operation than if you are moving between partitions

**Comment by ilyagr** [comment]
Just to double-check, the issue is just about the timestamp? The original file does get deleted even when you move to another partition?

**Comment by joelim-work** [comment]
Moving files between different partitions is treated internally as a copy for the reasons stated above, so the timestamp will be changed to the current time. If you want to preserve the timestamp, you can add `timestamps` to the `preserve` option, though this will affect actual copy operations as well.

**Comment by krem** [comment]
guys, move is move, regardless of partitions - no modification, keeping timestamps and preferably other attributes too.

**Comment by joelim-work** [comment]
Files can't be 'moved' between partitions - under the hood it is implemented by copying the files to the new partition and then deleting the original copies. I think the point you're trying to make is that from a user perspective, this distinction is not important and that the attributes should be preserved across partitions.

Does this mean that you find the solution of setting the `preserve` option to be inadequate, and you want the attributes to be kept (when moving files across partitions) as the default behavior?

I'm not completely sure yet about which side I prefer - on one hand keeping the attributes does feel more natural, but on the other hand this means introducing additional logic into the code (though it might not be too difficult to implement). I think it's worth considering what other tools do (e.g. `mv`/`ranger`/etc.). It might also be good to get @gokcehan 's opinion on this.

**Comment by krem** [comment]
I just want LF behavior by default be the same as lots of other FM's - moved file keeps at least modification time - as it's important attribute telling when file was, say, downloaded - WHY I LOOSE IT by moving file??, that's it

**Comment by DusanLesan** [comment]
Based on by understanding, lf behavior is perfectly logical and expected. I have now tried nnn and ranger and it looks confusing for me. 
![image](https://github.com/gokcehan/lf/assets/20520590/6c83fffd-79ff-4beb-abe3-e8e0456b2c4d)
Let me break the image down:

- First I have created an image and got its stats: everything as expected
- Went into lf, moved that file to another mounted partition, exited and got the stats for the same file on the other partition: All the dates are updated as I would expect
- Went into ranger, moved, exited, got stats again: Birth and change are updated but `modify` is not. In my opinion completely strange since I now have a file that is modified earlier than it is created
- nnn: same confusing behavior as ranger

That being said `mv` itself preserves `modify` date for some reason even though it explains its actions as copy + delete of origin file. `cp` does not preserve date as expected
<details><summary>mv behavior image</summary>
<p>

![image](https://github.com/gokcehan/lf/assets/20520590/1dd846a7-a8d9-4e22-b90d-9f651f4fb48f)


</p>
</details>

**Comment by gokcehan** [comment]
@krem Historically speaking, a move was just a move and it used to fail with an error when trying to move between partitions. Many users complained we should add copy+del as the fall back behavior for such cases, so we are currently doing that. Therefore, we inherit the behavior of copying for these cases. Note, there is not a standard set of metadata attributes for all filesystems in existence, so preserving every attribute for copy+del may not even be possible in some cases.

Some related discussion about this was made in #1026 and I don't have much to add to this discussion at this point. I would be ok to add `mtime` to `preserve` option if we have a consensus here on the expected default behavior, but I suppose it is still possible that we get other similar rants about this in the future for the lack of other attributes when copying (e.g. ownership and/or links). I find it easier to argue that our copy mimics `cp` by default until we have an implementation for `cp -a`.

I wonder, when you download a file, you are copying the file from a remote server to your own machine. Why should the modification time show the download time then? In most cases, you are not actually modifying the file.

**Comment by joelim-work** [comment]
@DusanLesan @krem I think there are two different opinions on this. From a theoretical perspective, moving between partitions technically creates a new file with the contents copied over (the inode is different). But from a practical perspective, the user will generally want the new file to retain attributes from the original file, to simulate the effect of a move operation as much as possible.

To me, the latter approach makes more sense with regards to user needs, and is also consistent with the behavior of other programs.

@gokcehan I'm not sure if simply changing the default value of `preserve` to `mode:timestamps` is sufficient, because while it fixes the behavior for moving between partitions, it will also affect copy operations which may not be desirable. I expect the user would want something like this:

- For copy operations, use the value of `preserve`.
- For move operations across partitions, ignore the actual value of `preserve` and use `mode:timestamps` instead.

It should be possible to achieve this using only configuration like below:

```
map d :cut; set preserve mode:timestamps
map y :copy; set preserve mode
```

But I suspect the reason this issue was raised in the first place was to **make this the default behavior**, which I guess means having to change the code, maybe something like this:

```diff
diff --git a/copy.go b/copy.go
index 2c7a2bd..4d59dca 100644
--- a/copy.go
+++ b/copy.go
@@ -36,15 +36,20 @@ func copySize(srcs []string) (int64, error) {
 	return total, nil
 }
 
-func copyFile(src, dst string, info os.FileInfo, nums chan int64) error {
+func copyFile(src, dst string, info os.FileInfo, nums chan int64, preserve bool) error {
 	var dst_mode os.FileMode = 0666
 	preserve_timestamps := false
-	for _, s := range gOpts.preserve {
-		switch s {
-		case "timestamps":
-			preserve_timestamps = true
-		case "mode":
-			dst_mode = info.Mode()
+	if preserve {
+		preserve_timestamps = true
+		dst_mode = info.Mode()
+	} else {
+		for _, s := range gOpts.preserve {
+			switch s {
+			case "timestamps":
+				preserve_timestamps = true
+			case "mode":
+				dst_mode = info.Mode()
+			}
 		}
 	}
 
@@ -98,7 +103,7 @@ func copyFile(src, dst string, info os.FileInfo, nums chan int64) error {
 	return nil
 }
 
-func copyAll(srcs []string, dstDir string) (nums chan int64, errs chan error) {
+func copyAll(srcs []string, dstDir string, preserve bool) (nums chan int64, errs chan error) {
 	nums = make(chan int64, 1024)
 	errs = make(chan error, 1024)
 
@@ -149,7 +154,7 @@ func copyAll(srcs []string, dstDir string) (nums chan int64, errs chan error) {
 					}
 					nums <- info.Size()
 				} else {
-					if err := copyFile(path, newPath, info, nums); err != nil {
+					if err := copyFile(path, newPath, info, nums, preserve); err != nil {
 						errs <- fmt.Errorf("copy: %s", err)
 					}
 				}
diff --git a/nav.go b/nav.go
index b6a0dce..cef801e 100644
--- a/nav.go
+++ b/nav.go
@@ -1320,7 +1320,7 @@ func (nav *nav) copyAsync(app *app, srcs []string, dstDir string) {
 
 	nav.copyTotalChan <- total
 
-	nums, errs := copyAll(srcs, dstDir)
+	nums, errs := copyAll(srcs, dstDir, false)
 
 	errCount := 0
 loop:
@@ -1415,7 +1415,7 @@ func (nav *nav) moveAsync(app *app, srcs []string, dstDir string) {
 
 				nav.copyTotalChan <- total
 
-				nums, errs := copyAll([]string{src}, dstDir)
+				nums, errs := copyAll([]string{src}, dstDir, true)
 
 				oldCount := errCount
 			loop:
```

**Comment by gokcehan** [comment]
@joelim-work I guess it makes sense to separate the behavior of copy and move as you suggest. My only worry is that someone may ask the move behavior to be also configurable in the future. Still, I think it makes sense to do this change if @krem also agrees with this change.

**Comment by krem** [comment]
@joelim-work, @gokcehan, indeed, reason for this issue was losing modification times of multitude of files in directory moved by d+p on another partition, and modification times mean very much for these files! I was shocked )) luckily this directory was in backup )) Thank you for your great work!

**Comment by joelim-work** [comment]
> My only worry is that someone may ask the move behavior to be also configurable in the future.

I think most other file managers just assume that users want the timestamps preserved in this case, and don't offer a way to configure this. Allowing for configuration sounds like a very niche requirement, and IMO not worth considering right now.

Anyway I have submitted PR #1482
