### ISSUE TITLE
Stringing cmds

### ISSUE THREAD

**Issue by se7en-x230** [gokcehan/lf#1473]
map Yb          %cp -r "$f" ~/.local/bin 
map YB          %cp -r "$f" ~/.local/bin ; %cd ~/.local/bin

frist part works second not. Why?
or is there a better way to do that

**Comment by og900aero** [comment]
The second cd command does not need the %:
map YB %cp -r "$f" ~/.local/bin ; cd ~/.local/bin

**Comment by og900aero** [comment]
Try this:

map YB %cp -r "$f" ~/.local/bin ; lf -remote "send $id cd ~/.local/bin"

**Comment by se7en-x230** [comment]
very nice. That saves some time.

**Comment by se7en-x230** [comment]
Could cp also be done with lf copy paste?
This way the cp command would not lock lf + I would have a progress bar

**Comment by joelim-work** [comment]
There are a few examples in the [Tips](https://github.com/gokcehan/lf/wiki/Tips) that use `cp`/`mv` to replace the default `paste` command. Although they won't work with the progress bar since the actual copying/moving is done outside of `lf`.

There may be tools out there that performing copy/moves and also provide a progress bar which could be piped to `%` commands, if anyone knows of such tools then that would be great to add them to the wiki.

**Comment by joelim-work** [comment]
Apparently someone has already provided an example for showing progress when copying files: https://github.com/gokcehan/lf/wiki/Tips#show-progress-for-file-copying
