### ISSUE TITLE
Feature Request: bulkrename

### ISSUE THREAD

**Issue by blairdrummond** [gokcehan/lf#149]
This is the only feature that I miss from ranger. For anyone unfamiliar with it, it just lets you edit a list of selected filenames in an editor, like vim (similar to wdired in emacs), and then rename (=move) things in bulk. It's really nice for cleaning up file-names interactively.

https://github.com/ranger/ranger/blob/a3a9ea373129731fb923927ad32ee30016112f69/ranger/config/commands.py#L1055

I assume that this could be done with a simple lfrc function, but I frankly don't fully trust my shell-foo when it comes to handling file names safely...

**Comment by TeddyDD** [comment]
I use external tool for this - [massren](https://github.com/laurent22/massren)

**Comment by gokcehan** [comment]
@blairdrummond Currently we don't even have a regular `rename` as a builtin but that is likely to change in the future. `bulkrename` is more difficult because it is more complicated and people may have different expectations about how it should work. So external tool seems like the best option for now. I don't know what tools are out there but @TeddyDD 's suggestion seems nice. We should probably add some example tools to our integrations wiki. Also maybe someone can come up with a simple shell command for this instead of a separate tool.

**Comment by blairdrummond** [comment]
Thanks @TeddyDD, I didn't know about this tool. That's a perfectly good solution for me, for now at least.

**Comment by EmmChriss** [comment]
@blairdrummond Here, take mine ;)
```
cmd bulk-rename ${{
	index=$(mktemp /tmp/lf-bulk-rename-index.XXXXXXXXXX)
	if [ -n "${fs}" ]; then
		echo "$fs" > $index
	else
		echo "$(ls "$(dirname $f)" | tr ' ' "\n")" > $index
	fi
	index_edit=$(mktemp /tmp/lf-bulk-rename.XXXXXXXXXX)
	cat $index > $index_edit
	$EDITOR $index_edit
	if [ $(cat $index | wc -l) -eq $(cat $index_edit | wc -l) ]; then
		max=$(($(cat $index | wc -l)+1))
		counter=1
		while [ $counter -le $max ]; do
			a="$(cat $index | sed "${counter}q;d")"
			b="$(cat $index_edit | sed "${counter}q;d")"
			counter=$(($counter+1))
			
			[ "$a" = "$b" ] && continue
			[ -e "$b" ] && echo "File exists: $b" && continue
			mv "$a" "$b"
		done
	else
		echo "Number of lines must stay the same"
	fi
	rm $index $index_edit
}}

```

**Comment by blairdrummond** [comment]
@EmmChriss You are a gentleman and a scholar. Thank you.

**Comment by crocket** [comment]
Why don't you implement most of bulkrename functionality in Go?
Implementing everything in shell script is clumsy.
Shell script is best used as a glue language.

**Comment by gokcehan** [comment]
@crocket As mentioned in my previous comment, we don't have a builtin `bulkrename` because it's a relatively complicated command and everyone have different expectations for how this should work. If you don't want to use shell script for this purpose, you can always use one of the dedicated bulkrename tools out there.

I don't remember why we left this issue open. Probably to update our wiki pages with examples and such.

**Comment by gokcehan** [comment]
Anyway closing the issue now. Feel free to leave comments if you have for discussion.

**Comment by crocket** [comment]
Everyone has different expectations for how everything works.
Ranger's bulkrename functionality works for most people.

**Comment by gokcehan** [comment]
@crocket I don't think it's fair to compare `bulkrename` to one of our builtin commands, say like `rename`. Most people expect a file manager to be able to rename a file by prompting a new name, though there are many file managers that do not provide a `bulkrename` functionality. I agree everyone has different expectations for nearly everything, though the extend of this difference is much higher for bulkrenaming.

Even for `rename` command we had a discussion whether we should have it as a builtin or leave it as a custom command. In this case, implementing it as a builtin had some advantages such as being able to put the current file name to the command line and having a prompting mechanism that would work without hitting the enter key, that were otherwise difficult to implement if not impossible. I don't see any advantages for having a builtin `bulkrename` as there is no ui involvement. I have tried ranger, and it seems that it launches an editor to get the new names, which is appropriate as a shell command or an external tool. As I said, if you don't want to use a shell command, you can always use an external tool for this purpose. We try to exclude features that could be implemented externally to keep the complexity of the code at minimum.

If you intend to push the argument further, please try to address all arguments mentioned previously.

**Comment by crocket** [comment]
If you are aiming for minimal codebase, not implementing bulkrename makes sense.
But, it'd be better if someone added an implementation of bulkrename to https://github.com/gokcehan/lf/wiki/Integrations or etc/lfrc.example

**Comment by gokcehan** [comment]
@crocket I have now added an example shell command to tips wiki page.

I haven't tried any dedicated bulk rename tools myself and I don't know how they work so I haven't added them to the wiki. Everyone is welcomed to add these tools to the integrations wiki page.

**Comment by marcosrdac** [comment]
I've made a post on my new bulk-renaming functionality for LF, inspired by your, @EmmChriss.

[marcosrdac.github.io/propper renaming_for_LF](http://marcosrdac.github.io/content/blog/20200310_propper_renaming_for_lf.html)

**Comment by alexherbo2** [comment]
## Batch

[Batch] is a command-line program for [batch processing].

[Batch]: https://github.com/alexherbo2/batch
[Batch processing]: https://en.wikipedia.org/wiki/Batch_processing

[![Batch demo](https://img.youtube.com/vi_webp/QN4mrZXYHPo/maxresdefault.webp)](https://youtu.be/QN4mrZXYHPo "YouTube – Batch demo")
[![YouTube Play Button](https://www.iconfinder.com/icons/317714/download/png/16)](https://youtu.be/QN4mrZXYHPo) · [Batch demo](https://youtu.be/QN4mrZXYHPo)

## Configuration

`~/.config/lf/lfrc`

```
cmd batch ${{
  batch --editor kak --map 'rename "$1" "$2"' --drop 'trash "$1"' $fx
}}

map b batch
```

**Comment by dikeert** [comment]
There's this little script: https://github.com/thameera/vimv for which there's actually a package in AUR and then in your `lfrc`:

```
cmd batch ${{
  /bin/sh -c "vimv $(echo -e "$fx" | xargs -i echo "\\'{}\\'" | xargs echo)"
}}
map rb batch
```

**Comment by marcosrdac** [comment]
I gave vimv a try and it's an good piece of code, much well written than mine hahaha
But in terms of eficacy, my code is able to rename only extensionss if you want or only filenames without extension, or entire paths too.

In the rest, both mine and thameera's code have the same kind of problems when swapping lines or deleting them :S

**Comment by ismay** [comment]
There is already a package that does basically exactly this: renameutils (see: https://man.archlinux.org/man/qcmd.1.en and https://www.nongnu.org/renameutils/).

From the docs: 

> Edit names of files with extension `.c'. Sort files by modification time: `qmv -t *.c`

This will open up the filenames in `$VISUAL` or `$EDITOR` and move afterwards.

**Comment by amano-kenji** [comment]
https://raku.land/zef:amano.kenji/File::Name::Editor is another alternative that I wrote.

This one supports cyclic renaming which is cool.
