### ISSUE TITLE
Win.printr is called too much

### ISSUE THREAD

**Issue by KenjiTakahashi** [gokcehan/lf#15]
It certainly gets called on quit and I think also on command completion. When you happen to be siting on a 25M SQL file with "not clever" previewer turned on, it takes `lf` ~5 seconds to unfreeze, which is *kinda* annoying.

**Comment by gokcehan** [comment]
@KenjiTakahashi For command completion it should be necessary since the completion window could have been narrowed down in the second time and the text there need to be redrawn. We can buffer the text that goes there though in order to get rid of filtering each time which is most likely the bottleneck there. Still ~5 second sounds quite annoying even if it is only when navigating. I hope #14 can help here.

For quitting it shouldn't be necessary.

I will prioritize adding the profiling to the code so we can do better than blind optimization.

**Comment by KenjiTakahashi** [comment]
Yeah, #14 helps here. Still it's strange to have to wait for redraw when you want to close the app anyway ;-).

**Comment by gokcehan** [comment]
With commit 60940781858f1aca3095be03613cda71b666fa7b previews are now buffered and `Win.printr` is a cheap operation. Hence I'm closing this issue now. The rest is tracked in #5.
