### ISSUE TITLE
Crash on `:low`

### ISSUE THREAD

**Issue by postsolar** [gokcehan/lf#1500]
**Version**: 30.r84.g741dd48
**OS**: Arch Linux x86-64
**Installation method**: with pacman, package extra/lf
**To reproduce**: open LF, navigate to a dir where the number of files/subdirs exceeds the number of terminal window rows, type `:low` and press return.
**Crash log**:
```
panic: runtime error: index out of range [-50]

goroutine 1 [running]:
main.(*nav).currFile(0x6061af?)
	github.com/horriblename/lf/nav.go:1993 +0x78
main.(*ui).loadFile(0xc000466820, 0xc0004c0000, 0x1)
	github.com/horriblename/lf/ui.go:700 +0x35
main.(*callExpr).eval(0xc00007abd0, 0xc0004c0000, {0xc00051d9d8?, 0x3?, 0x4?})
	github.com/horriblename/lf/eval.go:1529 +0x5e5
main.(*callExpr).eval(0xc00007b710, 0xc0004c0000, {0xc0000284e0?, 0x0?, 0xc0000061a0?})
	github.com/horriblename/lf/eval.go:2179 +0x8cf3
main.(*app).loop(0xc0004c0000)
	github.com/horriblename/lf/app.go:446 +0xd04
main.run()
	github.com/horriblename/lf/client.go:61 +0x3cf
main.main()
	github.com/horriblename/lf/main.go:331 +0x79e

```

Happens on 31.r16.g9698ecd from AUR as well.

**Comment by postsolar** [comment]
Can't reproduce anymore — while I was tweaking some settings and configurations I noticed it stopped crashing. Later I'll look closer into if there's something in my config that could be triggering it.

**Comment by joelim-work** [comment]
Thanks, I can reproduce a crash scenario on the latest version on the `master` branch. The issue seems to be caused by using a large `scrolloff` value which causes `dir.ind` (index showing which file the cursor is at) to be negative: https://github.com/gokcehan/lf/blob/9698ecddf17c5fdff78494314bd2a718b4100f3e/nav.go#L1178-L1184

Steps to reproduce:

1. Set `scrolloff` to a large value, for example `set scrolloff 1000`
2. Ensure the current directory has more files than the terminal height
3. Run the `low` command

There is a similar bug for the `high` command as well:

1. Set `scrolloff` to a large value, for example `set scrolloff 1000`
2. Scroll down (e.g. using `scroll-down`) so that the first file in the directory is not shown
3. Run the `high` command

**Comment by joelim-work** [comment]
I have submitted a PR #1504 which places the cursor in the middle for `low` and `high` when the `scrolloff` value is a large number, this behavior is consistent with other navigation commands like `up` and `down`.
