### ISSUE TITLE
Parsing question

### ISSUE THREAD

**Issue by TheYellowArchitect** [gokcehan/lf#1505]
Hello!
I wrote an ffmpeg script and found a bizzare bug, and want to confirm if it's my pc/setup which causes it.
For context, see the compressvideo script of https://github.com/gokcehan/lf/wiki/Integrations#ffmpeg

On the terminal (st), if I run `read compressionRate; if ! [[ $compressionRate =~ "^[0-5][0-9]$" ]]; then echo "Is not a number" && sleep 1; fi` this always returns the expected output. But if I run the above via lf command (see commented codeblock in above URL), it ALWAYS gets inside that codeblock, it ALWAYS prints "Is not a number"

I suspect something is different because `read -N 2 compressionRate` works inside `lfrc` but not the terminal (output being: `read: bad option: -N`)

Anyway, could someone try making an lfrc cmd whose containers are exclusively these?
```shell
echo "Compression Rate? (default: 31, maximum: 50)";
read compressionRate;

   #If not a number (e.g. empty), give default 31 value
   if ! [[ $compressionRate =~ "^[0-5][0-9]$" ]]; then
      echo "Is not a number" && sleep 1;
   fi
```

map it to a key and run it and tell me results? It's honestly so strange that with the same input, there is different output in st and lf, and it's a very useful condition to be disabled.

**Comment by joelim-work** [comment]
By default `lf` uses `sh` for running all shell commands (beginning with `$`/`!`/`%`/`&` prefix), which is not necessarily the same shell that is running in your terminal. If you are getting different results when running commands inside your terminal compared to inside `lf`, then you likely have different shells involved.

If you want to change the default shell used inside `lf`, then set the `shell` option, e.g. `set shell bash`.

I'm guessing from your code snippet, you use `bash`, in which case you shouldn't quote regex patterns otherwise they will be treated as a literal string. I recommend to use https://www.shellcheck.net/ for detecting common shell scripting mistakes. The following example works for me:

```bash
set shell bash

map x ${{
    echo "Compression Rate? (default: 31, maximum: 50)";
    read compressionRate;

    #If not a number (e.g. empty), give default 31 value
    if ! [[ $compressionRate =~ ^[0-5][0-9]$ ]]; then
        echo "Is not a number" && sleep 1;
    fi
}}
```

**Comment by TheYellowArchitect** [comment]
Wow, that was it, the regex quotations was the problem as you pointed out. Thank you very much.
