### ISSUE TITLE
strange issue with tag

### ISSUE THREAD

**Issue by superiums** [gokcehan/lf#1515]
```bash
cmd mkdir %{{
    # IFS=" "
    mkdir -p -- $@
    # lf -remote "send $id unselect"
    for file in "$@";do
      lf -remote "send $id :echo $file;select $file; tag +"
      sleep 2
    done
}}
map mk push :mkdir<space>

```

after run `m` `k` `a b c`
the new folder 'b' , 'c' was tagged as +, but 'a' was not.
strange.

**Comment by joelim-work** [comment]
I don't really know what can be done about this, but using `select` can be problematic when scripting. The reason is because directories are reloaded asynchronously, which means chaining commands immediately afterwards may not work. What happens in your scenario is:

1. Directories `a`/`b`/`c` are created
2. `lf` tries to select `a` immediately, but it does not work as it isn't aware about the newly created directories yet
3. Tagging the current entry (supposed to be `a`) does not work as a result
4. The script sleeps for two seconds, during which time the new directories are loaded
5. The script resumes, and `b` and `c` are selected and tagged as expected

I suggest to use `toggle` instead, which is not only simpler, but also happens to work since `lf` just calculate the path without having to do any reloading. Something like this:

```shell
cmd mkdir %{{
    mkdir -p -- $@
    lf -remote "send $id :toggle $*; tag +; unselect"
}}
map mk push :mkdir<space>
```

**Comment by joelim-work** [comment]
**EDIT:** I looked at the code in a bit more detail, it looks like this can be solved by initializing the path during `select` without having to wait for `lf` to reload:

```diff
diff --git a/eval.go b/eval.go
index 47c8eeb..b4b18e6 100644
--- a/eval.go
+++ b/eval.go
@@ -2267,19 +2267,19 @@ func (e *callExpr) eval(app *app, args []string) {
 			log.Printf("getting current directory: %s", err)
 		}
 
-		path := filepath.Dir(replaceTilde(e.args[0]))
+		path := replaceTilde(e.args[0])
 		if !filepath.IsAbs(path) {
 			path = filepath.Join(wd, path)
 		} else {
 			path = filepath.Clean(path)
 		}
 
-		if wd != path {
+		if filepath.Dir(path) != wd {
 			resetIncCmd(app)
 			preChdir(app)
 		}
 
-		if err := app.nav.sel(e.args[0]); err != nil {
+		if err := app.nav.sel(path); err != nil {
 			app.ui.echoerrf("%s", err)
 			return
 		}
diff --git a/nav.go b/nav.go
index f748619..d5e43be 100644
--- a/nav.go
+++ b/nav.go
@@ -1615,9 +1615,6 @@ func (nav *nav) cd(wd string) error {
 }
 
 func (nav *nav) sel(path string) error {
-	path = replaceTilde(path)
-	path = filepath.Clean(path)
-
 	lstat, err := os.Lstat(path)
 	if err != nil {
 		return fmt.Errorf("select: %s", err)
@@ -1634,7 +1631,7 @@ func (nav *nav) sel(path string) error {
 	last := nav.currDir()
 
 	if last.loading {
-		last.files = append(last.files, &file{FileInfo: lstat})
+		last.files = append(last.files, &file{FileInfo: lstat, path: path})
 	}
 
 	for i, f := range last.files {
```
