### ISSUE TITLE
Add option to display the summarized size of directories

### ISSUE THREAD

**Issue by EmmChriss** [gokcehan/lf#152]
Pretty self-explanatory, but would be quite complicated to implement if a tool, like `du` isn't used.
On the flip side, it'd be a nice feature to have.

**Comment by gokcehan** [comment]
@EmmChriss Do you mean like next to each directory or only for the current directory at the bottom status line? The reason this is not yet implemented so far is that filesystems do not provide this information and we need to sum the sizes for all files recursively to calculate this value and this can take a significant amount of time for big directories. Implementation part may not be that difficult. In fact, we already do such a calculation before copying to show the progress of the operation.

**Comment by EmmChriss** [comment]
To clarify, to my knowledge lf uses some internal mechanism to determine the size of files and folders, and displays that information in the bar on the bottom left of the screen, and next to files, after executing `set info size`.
It would be a useful optional feature to have it display the summarized size of directories instead of the actual, canonical one.

**Comment by gokcehan** [comment]
@EmmChriss We show the sizes of files and folders as they are provided by the filesystem. For regular files, this is fine. For directories, the reported number is not the thing most people expect. The problem is that the filesystem only provides the size of the directory file that holds the names and inodes of files inside. To actually calculate the cumulative size of all files, we need to recursively iterate over all the files inside the directory and sum the sizes manually. For crowded directories, this is a significant amount of work. Imagine if you were to calculate the size of your home folder, you need to visit all the files in your home folder.

At some point, we received a patch for an option to show the number of files inside a directory instead of the size (i.e. `dircounts`). Number of files inside a directory is also not provided by the filesystem and this calculation can also be significant. For this reason, we use a strategy to count only the first 1000 files and show `999+` for directories bigger than that. Cumulative size is even more expensive than number of files and I can't think of an equivalent fallback strategy to limit this calculation.

You can try to run `du` on your home folder or your root directory to see how long it takes and decide if you want to wait this long every time you visit this directory.

**Comment by roipoussiere** [comment]
This feature could be integrated among with the *sortby/size* option (default map `ss`).

This one displays size of each file, but always displays `4.0k` for folders. `lf` could display the actual folder size (ie. the size of all files inside the folder, recursively) instead.

**Comment by Monirzadeh** [comment]
> This feature could be integrated among with the _sortby/size_ option (default map `ss`).
> 
> This one displays size of each file, but always displays `4.0k` for folders. `lf` could display the actual folder size (ie. the size of all files inside the folder, recursively) instead.
it can be useful but until then can hide only '4.0k' of directories

**Comment by gokcehan** [comment]
@Monirzadeh You can use `dircounts` option to show number of items instead of size for directories which should hide `4.0k` for directories (and bigger sizes for bigger directories).

**Comment by auseeu** [comment]
There are several terminal tools to analyze file system usage.
I like these two: [NCurses Disk Usage](https://dev.yorhel.nl/ncdu), [Duc: Dude, where are my bytes!](https://duc.zevv.nl/)

But again, it would be nice if **lf** just be capable to show directories size recursively.

**Comment by laktak** [comment]
ranger solves this with a command that lets you compute the dir size on demand (`get_cumulative_size` bound to `dc`) for the selected items.

The nice thing is that it then keeps it as a static value in the list (even when you cd somewhere else and then come back it is still shown).
