### ISSUE TITLE
running shell: exit status 134

### ISSUE THREAD

**Issue by MichaelC001** [gokcehan/lf#1550]
in lF manager, use key 'l' to enter a text file with Neovim, after editing the file press 'q' to quit back to lf.
lf show "running shell: exit status 134" 
how to hide this annoying message

some answer says: to and return 0 to 'l' 
but I don't know how to bind l, because l is the default key bind, it will enter Neovim when it is a file, and it will enter the folder with lf if it is a folder.

I found out that the issue is caused by the Neovim plugin "EtiamNullam/deferred-clipboard.nvim", and how to hide the message with this plugin.

**Comment by joelim-work** [comment]
You should report the issue to the offending plugin.

Otherwise you can try suppressing the failure like the suggestion in #1252

**Comment by joelim-work** [comment]
I have written a section on how to deal with the `running shell: exit status ...` in the wiki: https://github.com/gokcehan/lf/wiki/Troubleshoot#running-shell-command-results-in-non-zero-exit-status

Given that the root cause is not from `lf`, and there is a documented workaround available, I think there is no point keeping this issue open.
