### ISSUE TITLE
Thoughts on navigating remote files?

### ISSUE THREAD

**Issue by ChausseBenjamin** [gokcehan/lf#1584]
Vim has this brilliant feature with `netrw` which let's you navigate a remote filesystem. For example, you can from within vim type the following: `:e scp://user@hostmachine/.config/` and it will open that directory with netrw inside vim. What are your thoughts on implementing something similar.

I personally replaced netrw with lf for 90% of my usecases inside vim.

**Comment by joelim-work** [comment]
Based on responses like https://github.com/gokcehan/lf/issues/698#issuecomment-939337171, I would say that this kind of feature is outside the scope of `lf`.

Instead of adding code into `lf` to handle different protocols, you can instead use something like `sshfs` to mount a remote filesystem, and browse it as you would normally do in `lf`.

**Comment by joelim-work** [comment]
I have finally gotten around to adding `sshfs` as an [integration](https://github.com/gokcehan/lf/wiki/Integrations#sshfs). Closing this issue now.
