### ISSUE TITLE
Support D-Bus interface specification

### ISSUE THREAD

**Issue by avidseeker** [gokcehan/lf#1609]
See: https://www.freedesktop.org/wiki/Specifications/file-manager-interface

This makes it possible to make "Open in folder" button (e.g: found in Firefox, VScode, etc) open up lf instead of a GUI file manager.

**Comment by DusanLesan** [comment]
It would be nice if lf suported a argument like `--dbus-listener` and to have its server start listening if it is set.

But that is probably unnecessary as we do have a way of achieving that in more unix way of having separate handler for such events. I had [this python script](https://github.com/DusanLesan/dotfiles/blob/master/.local/bin/lfd) that was supposed to subscribe to `org.freedesktop.FileManager1` event and open lf when needed. But now it looks like I am missing python dependencies for dbus and since I do not want any more python on my system, I now wrote C alternative for it:
```
#include <stdio.h>
#include <stdlib.h>
#include <dbus/dbus.h>

static void show_items(DBusMessageIter *iter) {
	const char *term = getenv("TERMINAL");
	DBusMessageIter array;
	dbus_message_iter_recurse(iter, &array);
	while (dbus_message_iter_get_arg_type(&array) != DBUS_TYPE_INVALID) {
		const char *item;
		dbus_message_iter_get_basic(&array, &item);
		item += 7;
		char *cmd;
		asprintf(&cmd, "%s lf '%s' &", term, item);
		system(cmd);
		free(cmd);
		dbus_message_iter_next(&array);
	}
}

static DBusHandlerResult message_handler(DBusConnection *connection, DBusMessage *message, void *user_data) {
	if (dbus_message_is_method_call(message, "org.freedesktop.FileManager1", "ShowItems")) {
		DBusMessageIter iter;
		dbus_message_iter_init(message, &iter);

		DBusMessage *reply = dbus_message_new_method_return(message);
		if (reply != NULL) {
			show_items(&iter);
			dbus_connection_send(connection, reply, NULL);
			dbus_message_unref(reply);
		} else {
			fprintf(stderr, "Error creating reply message\n");
			return DBUS_HANDLER_RESULT_NOT_YET_HANDLED;
		}
	}

	return DBUS_HANDLER_RESULT_HANDLED;
}

int main() {
	DBusConnection *connection = dbus_bus_get(DBUS_BUS_SESSION, NULL);
	if (connection == NULL) {
		fprintf(stderr, "Failed to connect to the D-Bus session bus\n");
		return 1;
	}

	dbus_bus_request_name(connection, "org.freedesktop.FileManager1", DBUS_NAME_FLAG_REPLACE_EXISTING, NULL);

	dbus_connection_add_filter(connection, message_handler, NULL, NULL);
	while (dbus_connection_read_write_dispatch(connection, -1));

	return 0;
}
```
You need to compile it with dbus libraries like `gcc -o file-handler file-handler.c $(pkg-config --cflags --libs dbus-1)`

**Comment by joelim-work** [comment]
> It would be nice if lf suported a argument like `--dbus-listener` and to have its server start listening if it is set.
>
> But that is probably unnecessary as we do have a way of achieving that in more unix way of having separate handler for such events.

The purpose of the `lf` server is to allow instances to communicate with each other (e.g. via `lf -remote "send $id ..."`). Acting as a DBus client feels like a separate responsibility and I am not yet convinced it is worth adding it to the `lf` server just because it is a server process. I am also concerned that the line `asprintf(&cmd, "%s lf '%s' &", term, item);` may need to vary for different users and require it to be exposed as configuration.

I would instead suggest this to be added as an [integration](https://github.com/gokcehan/lf/wiki/Integrations).

**Comment by DusanLesan** [comment]
> Acting as a DBus client feels like a separate responsibility and I am not yet convinced it is worth adding it to the lf server just because it is a server process

I completely agree with this. The way of implementing the dbus handling is possible to be done externally, any dbus support might benefit only users of one OS, and communication between GUI and TUI tools might not be what majority of users need.

> I am also concerned that the line `asprintf(&cmd, "%s lf '%s' &", term, item);` may need to vary for different users and require it to be exposed as configuration.

Possibly. I just offered C code this as alternative to python script if users want to use existing packages they probably already have (and since I personally wanted to stop using the other one). Python script might be more portable and does not need any compile instructions

> I would instead suggest this to be added as an [integration](https://github.com/gokcehan/lf/wiki/Integrations).

Feel free to copy any of my dotfiles wherever.

**Comment by joelim-work** [comment]
@DusanLesan Thanks for your feedback. I ended up adding your C program, with some very minor changes: https://github.com/gokcehan/lf/wiki/Integrations#d-bus

I'm not sure what terminal you use but when I was testing with `alacritty` I had to add an `-e` flag to the command string.

Anyway unless there's anything else, I think this issue can be closed?

**Comment by DusanLesan** [comment]
> I'm not sure what terminal you use but when I was testing with `alacritty` I had to add an `-e` flag to the command string.

I was not thinking about that. I have set up `TERMINAL` to be `alacritty -e` so I can feed it commands, and I have `TERM` set to `alacritty` somewhere else (possibly by alacritty itself) that I could use for getting the name of current term

**Comment by joelim-work** [comment]
Oh, sorry I mixed up `TERMINAL` with `TERM`. Thanks for pointing it out - I have updated the example.

I will close this issue, but feel free to make changes if you want as the wiki is open to everyone.

**Comment by hownioni** [comment]
Hi I have a question, where would the file-handler compiled executable go? Do I just put it in PATH?

**Comment by DusanLesan** [comment]
> Hi I have a question, where would the file-handler compiled executable go? Do I just put it in PATH?

Yes, anywhere on the PATH. You need to have it running either on the system launch or before you plan using it
