### ISSUE TITLE
When doing `ctrl-c` inside of `less -F`, `lf` exits

### ISSUE THREAD

**Issue by alejandrogallo** [gokcehan/lf#162]
When you're checking out a document with `less -F` and then you exit the follow mode of
`less` by pressing `ctrl-c`, then `lf` also exits, which is not the desired behaviour.

https://asciinema.org/a/FQ5kcpMnM9qRzr9DG0IdC9j0b

**Comment by gokcehan** [comment]
@alejandrogallo This has been like this from the start and I have kind of learned to live with this but I agree this is counterintuitive and I guess it is time to fix this. Interruptions work for `%` commands and ignored for `&` commands which is intentional. I think we somehow need to catch interrupt signals and pass them to the running command for `$` and `!` commands. We should also decide what should happen for stop signals in the meantime.

**Comment by noscript** [comment]
I'm suffering from the same problem. I made a mapping to run executables with <kbd>Enter</kbd>:
```
map <enter> exec
cmd exec ${{ $f }}
```

But processes terminating with `SIGTERM` also cause `lf` to exit.

I tried to change the mapping to wrap the command into a script and trap the signal, but couldn't prevent the signal from propagating to `lf`. Is there a workaround?

**Comment by gokcehan** [comment]
@noscript There is no workaround for this that I'm aware of. Actually signal should have been propagated from `lf` to other processes, not the other way around but since we are not doing that yet, they never reach those processes. Only after `lf` exits unintentionally, they receive a signal because their parent process is finished.

**Comment by noscript** [comment]
`lf` is the one that reacts upon <kbd>ctrl+c</kbd> and exits, is it so?

**Comment by gokcehan** [comment]
@noscript Hmm, actually now that I think about this again, I'm not so sure. Maybe signal is sent to both the `lf` and the child process and they both exit at the same time. I need to try and see this to be sure. If anyone wants to tackle this, there is a [signal](https://golang.org/pkg/os/signal/) package in Go standard library that can be used for this purpose.

**Comment by gokcehan** [comment]
I have now changed the code to ignore interrupt signals. Closing this issue now.

**Comment by mohkale** [comment]
Can confirm this issue has been resolved. Just updated to master and `lf` no longer exits when sending sigint to subprocesses.

Thnx for the great work :smile:.
