### ISSUE TITLE
Feature Request: sepparate glob option for filter command

### ISSUE THREAD

**Issue by Catalyn45** [gokcehan/lf#1649]
Hello,

I saw that currently the `globsearch` option is used to allow patterns (like `*`) both in `search` and `filter` commands. 

My general usecase is: when I search for a directory/file, usually I do it by the first or last letters from it's name but when I'm using the `filter` command usually I want to use patterns, ex: `*.go`. 

If I enable the `globsearch` then I can't quickly search for a file, because I always need to use `*` as suffix or prefix or both, and if I let it disabled then I can't use patterns in `filter` command to filter only files for a specific extension.

I was wondering if it's feasible to have a separate option, let's say `globfilter` which will be only for the `filter` command, and if there are people who finds this useful.

I guess a workaround could be to create custom commands which will dynamically set and unset `globsearch` before `search` and `filter` but then if I first filter, then I want to search on the filtered results it will reset.

**Comment by joelim-work** [comment]
I can't think of a good solution either since `globsearch` is used in in `dir.sort` to selectively display the files matching the filter, which means it has to be enabled for the entire duration for which the filter is applied.

Considering that there are separate options for incremental updates (`incfilter` and `incsearch`), I think it would be reasonable to have separate options for globs too.
