### ISSUE TITLE
"set period 1" causes flickering in sixel image previews

### ISSUE THREAD

**Issue by Zerogaku** [gokcehan/lf#1665]
From https://github.com/bakkeby/st-flexipatch/issues/128, `set period 1` causes flickering on images previews, removing that line from lfrc fixes it.

https://github.com/bakkeby/st-flexipatch/assets/144664603/e9ff8233-5971-4e34-9286-bcd62c10c9ac

**Comment by joelim-work** [comment]
I'm not sure whether it's possible to prevent flickering when redrawing the same image in the same spot. TUI libraries like [`tcell`](https://pkg.go.dev/github.com/gdamore/tcell/v2) typically maintain an internal buffer which stores the contents of the screen before flushing them to the actual terminal. As only *changes* in the internal buffer are flushed, this makes the actual updates appear more smooth.

The problem is that terminals don't truly have a concept of displaying images, and hacky standards like Sixel graphics are only made possible by bypassing the internal buffer and writing directly to the terminal. When you consider the steps that `lf` uses to draw the UI, it makes sense that there is a flicker:

1. `lf` clears the screen (really the internal buffer) to draw everything from scratch
2. Various components (pane, prompt, status bar, etc.) are drawn to the internal buffer. This includes previews that are text-based and not images
3. The internal buffer is flushed to the terminal (this will wipe the existing image preview)
4. If `sixel` is enabled, the sixel image is drawn by writing it to the terminal

---

That being said, specifically for the `period` timer, I think there is no need to redraw the UI since the purpose is to just check if any files have been modified, which essentially happens in the background.

**Comment by joelim-work** [comment]
I have submitted #1666 to address this, hopefully it fixes the issue for you.
