### ISSUE TITLE
lf image preview flickering when swapping workspace

### ISSUE THREAD

**Issue by Zerogaku** [gokcehan/lf#1689]
This occurs even when removing `set period 1` from the lfrc, I'm not sure what could be causing this.
I'm also using chafa with sixels for previewing.

https://github.com/gokcehan/lf/assets/144664603/b93f2c6a-bc0d-4400-bd3d-408bbc7f325b

**Comment by joelim-work** [comment]
I suspect this might be because the `previewer` script is somehow being triggered when changing workspaces, and it isn't just limited to image previews. You can verify this by adding a command to the `previewer` script to additionally write to a log file.

If that is the case, then we could try looking into what is triggering the `previewer` script. I don't know if it's possible for you to try using an older version of `lf`, the latest `master` branch, do a `git bisect`, etc.

**Comment by Zerogaku** [comment]
Hey so I've been checking recently and noticed the issue hasn't been happening, at all. I even added a line in my previewer script to log text into a log file to see if it updates, when I preview any image it adds a line of text to the file (obviously) but when I change workspace and swap back to file manager, I notice nothing happens, no log or flicker.

 I haven't checked the version so I assume that it was because my lf installation wasn't at the latest update to receive the fix from https://github.com/gokcehan/lf/issues/1665 and that running `yay -Syu --devel` recently (I don't remember if I did or not 😅) fixed it, so I'm closing for now, thanks!
