### ISSUE TITLE
Pistol doens't work as a previewer unless wrapped in a shell script

### ISSUE THREAD

**Issue by doronbehar** [gokcehan/lf#169]
Following [my last comment on #161](https://github.com/gokcehan/lf/issues/161#issuecomment-494409882), I'll explain here in details the problem I'm having with a specific previewer which is called 'Pistol' - https://github.com/doronbehar/pistol .

If I use the following in `lfrc`:

```
set previewer /home/doron/.go/bin/pistol
```

I see nothing in the preview window when files are highlighted. But, very interestingly, if I `set previewer /home/doron/.config/lf/scope.sh`, and in `scope.sh` I put only

```sh
#!/bin/sh
/home/doron/.go/bin/pistol "$@"
```

I do see previews!

I think it would be proper to explain a little bit how Pistol works, in order to give background and perhaps help in the attempt to fix this strange phenomenon:

Pistol implements an `io.Writer` to put the text of the preview in the terminal and it writes it to `os.Stdout`. Here's a [link to where this is implemented](https://github.com/doronbehar/pistol/blob/v0.0.1/cmd/pistol/main.go#L42-L46).

I've tried to debug this my self with [delving](https://github.com/derekparker/delve) to Lf's source code but I could find no clue.

**Comment by gokcehan** [comment]
@doronbehar I think the problem is that `lf` passes two arguments to the previewer program. First one is the file name, and the second one is the height parameter in case you want to internally limit the preview to a specific number of lines, which can be useful for longer files. I tried to change `lf` code to pass a single file name parameter and `pistol` started working as the previewer. I'm not quite sure how having a wrapper shell script fixes this problem. Do you think you can change `pistol` to accept multiple parameters?

Another issue is that `pistol` uses high level sgr codes for colors (e.g. `\033[95m`). These are currently not recognized by `lf` so the code highlighting is not working. We can try to add these colors to `lf` but they don't have their semantic equivalent in termbox API. As far as I understand, these are meant to be brighter versions of the basic 8 colors but termbox does only have the regular versions as the basic 8 colors. Is there an option to configure chroma library to use regular sgr codes (e.g. `\033[35m`) in the output?

Lastly, I realized `pistol` does not work without a configuration file and there are no example configuration files provided in the repository which can be a poor experience for new and impatient users. Having an empty configuration file seems to work so maybe it can work without a configuration file as well. Also I think most programs use an extra redundant directory with the name of the program inside the configuration directory (i.e. `~/.config/pistol/pistol.conf` instead of `~/.config/pistol.conf`). I'm not sure which one is a better convention though.

**Comment by doronbehar** [comment]
Wow I never expected the issue to be that simple. and I thought that I might have found a bug in Go...

> I'm not quite sure how having a wrapper shell script fixes this problem.

Pardon me, I wasn't accurate when I exemplified the wrapper script. It worked originally with `"$1"` and not `"$@"` and I didn't pay attention to that.

> Do you think you can change pistol to accept multiple parameters?

Indeed, I'll teach it to ignore extra arguments.

> Another issue is that pistol uses high level sgr codes for colors (e.g. \033[95m) [...]

Yea I noticed that.. I think I'll enable to configure that through environmental variables. Thanks for pointing this!

> Lastly, I realized pistol does not work without a configuration file and there are no example configuration files provided [...]

Thanks for the initial feedback! It would certainly be a good idea to handle the configuration file in a friendlier manner and not depend on it to actually operate. If you have any more suggestions, I'm all ears.

**Comment by doronbehar** [comment]
@gokcehan I'm closing this issue since it was from the beginning completely on my side. I've fixed the issues mentioned above. Now the default style and formatter Pistol uses should play well with Lf and Ranger. If not, this is configurable using environmental variables, as documented [here](https://github.com/doronbehar/pistol/tree/v0.0.2#environmental-variables).

I've also added an integrations section where I mention Lf and Ranger, both tested.
