### ISSUE TITLE
Issue with archivemount integration

### ISSUE THREAD

**Issue by BigCrow** [gokcehan/lf#1705]
In the wiki page for [integrations](https://github.com/gokcehan/lf/wiki/Integrations#archivemount), code is provided for archivemount integration. It has 2 issues:
- The auto CD does not work correctly for folders with spaces in them. To fix this you can change the archivemount command (only the final line) like this:
```
map am ${{
    mntdir="${f}.mnt"
    mkdir -p "$mntdir"
    archivemount "$f" "$mntdir"
    lf -remote "send $id cd '$mntdir'"
}}
```
- The script provided for unmounting archives doesn't work for folders with spaces in them. The script pulls information from /etc/mtab, however mtab uses octal representation for spaces. This is a potential fix:
```
awk '$1 == "archivemount" { print $2 }' /etc/mtab | while read -r mntdir
do
    sanitized_input=$(printf "$mntdir")
    umount "$sanitized_input"
    rmdir "$sanitized_input"
done
```

**Comment by joelim-work** [comment]
I believe you're right. The wiki can be edited by anyone so feel free to add your fixes in.

**Comment by DusanLesan** [comment]
@joelim-work Is that smart to allow editing for non-maintainers? Could you overlook some bad changes?

**Comment by joelim-work** [comment]
@BigCrow So a very quick point on the original `archivemount` integration, that was actually written by me in https://github.com/gokcehan/lf/issues/1458#issuecomment-1751628056. Turns out that I knew that spaces wasn't supported but I just wanted to provide a bare-minimum example (this is from half a year ago so my memories are a bit hazy), apologies for the inconvenience.

The change is probably fine as it is, maybe add a comment explaining that the `printf` call is required to handle spaces.

---

> Is that smart to allow editing for non-maintainers? Could you overlook some bad changes?

@DusanLesan Thank you for your concern. Actually I believe the default setting for wikis is that only admins (and collaborators) have write permissions, at least according to [this documentation](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis). Which means that opening the wiki to all users was a deliberate decision, and it is also mentioned on the [front page](https://github.com/gokcehan/lf/wiki) of the wiki itself.

TBH I don't know whether it's better to keep things as it is, or restrict write access to the wiki. On one hand, it's nice to benefit from the entire community, but on the other hand (leaving aside the possibility of malicious users) it is difficult to establish quality control, and there may be advice that is either outdated or just outright terrible.

As a collaborator, I do not have access to the repo settings, only @gokcehan does. And even if I did I probably wouldn't change anything myself because I do not see it as my decision to make.

**Comment by DusanLesan** [comment]
> On one hand, it's nice to benefit from the entire community

I would still expect that to be the case, but In my opinion, I would prefer for doc improvements to go through review process same as PRs or done by suggestions in issues like this one. Something like: "Any documentation improvements are welcome. Submit a issue with a proposed change: <new issue link(maybe with some template if possible)>"

**Comment by BigCrow** [comment]
> The change is probably fine as it is, maybe add a comment explaining that the `printf` call is required to handle spaces.

I added a comment explaining why printf was added.

**Comment by joelim-work** [comment]
> > On one hand, it's nice to benefit from the entire community
> 
> I would still expect that to be the case, but In my opinion, I would prefer for doc improvements to go through review process same as PRs or done by suggestions in issues like this one. Something like: "Any documentation improvements are welcome. Submit a issue with a proposed change: <new issue link(maybe with some template if possible)>"

That is fair enough - I can add such a message [here](https://github.com/gokcehan/lf/wiki) if you want, but other people might miss it, and such a process can't be enforced unless the wiki is locked.

**Comment by DusanLesan** [comment]
> I can add such a message [here](https://github.com/gokcehan/lf/wiki) if you want

Maybe we can wait for @gokcehan to decide before making any actions.
