### ISSUE TITLE
Is there a way to select a directory for --print-selection and --selection-path?

### ISSUE THREAD

**Issue by nabakolu** [gokcehan/lf#1791]
When using the `--print-selection` or `--selection-path` flags, normal files
can be printed/written by opening them with the `:open` command. But since the
`:open` command is also used to change directory when used on a directory, it
is not possible to print/write the path of a directory.  

Is there any other wayto print/write the file path?

**Comment by joelim-work** [comment]
This is handled by the following code: https://github.com/gokcehan/lf/blob/505c4ef6c0dec48cf48161dd3acd8c42de8837ad/eval.go#L1064-L1083

- Using `open` on a directory will just change into it and then `return`, simple as that.
- But if `open` is used on a file, then will it check for the `--print-selection`/`--selection-path` flags. In this case the final result printed out is the _current file or selections_. This means the list of selected files (e.g. using `toggle`), otherwise the current file pointed by the cursor if that list is empty.

So the answer to your question is technically yes it is possible:

- Use `toggle` to select a directory
- Navigate to any file
- Use `open`, whilch will quit and print the selected directory

**Comment by nabakolu** [comment]
This doesn't feel like a good way to select directories.
I think a better way to do it, would be to have a dedicated command,
that quits lf and prints the path(s) of the current selection.

I have quickly implemented this and it feels very good.

**Comment by joelim-work** [comment]
TBH I don't like the design either - using `open` to quit and print the selection feels very unintuitive to me. I am merely just stating what the existing code (not written by me) does.

I also managed to implement something similar, without having to make any changes to the actual code:

```sh
map Q :{{
    $echo "$fs" > "/proc/$id/fd/1"
    quit
}}
```

That being said, I don't think this feature is likely to be changed/removed because:

- It is a port of `ranger`'s `--choosefiles` option.
- It has existed from the [very start](https://github.com/gokcehan/lf/commit/4b266c97e94c4fa04b6be18bbace0ef7e941bf72#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R66).
- Any modifications constitutes a breaking change and will impact users.
