### ISSUE TITLE
File statinfo not refreshed when using mark-load

### ISSUE THREAD

**Issue by valoq** [gokcehan/lf#1807]
Related to #1536

The statinfo refresh is currently handled here
https://github.com/gokcehan/lf/blob/382095bfb59ce59a58781760151ce17e59d81873/app.go#L412
but when I use mark-load to change to a directory after receiving an error message, the statinfo is not refreshed and the error message persists until I change to another directory.

@joelim-work I noticed that msgIsStat is false when I use mark-load but I am not quite sure how to best address this.

**Comment by joelim-work** [comment]
`app.ui.msgIsStat` represents whether the statline actually displays file info or not. This is important so that other things like error messages do not get wiped out from asynchronous updates.

However I found that when changing to an empty directory (or a new directory that hasn't been loaded yet), the `loadFileInfo` function doesn't actually set `app.ui.msgIsStat` because there is no file to display information for. But I think this is incorrect since the old file info will remain - can you try #1808 to see if this fixes your issue?

**Comment by valoq** [comment]
Works as expected

**Comment by valoq** [comment]
A possibly related behavior can be observed when opening files after an error message:

1. Trigger Error -> Error Message is displayed 
2. Open text file, then close the text file
3. Error Message is still displayed

Not sure this is intended or another missing check.

**Comment by joelim-work** [comment]
This is a separate issue, can you try #1809 to see if it works?
