### ISSUE TITLE
Select with regex

### ISSUE THREAD

**Issue by JurisMajors** [gokcehan/lf#181]
Option for selecting according to regex would be nice.

For example
:select *.txt 
to select all txt files

(I would be happy  to implement this, but some guidance where this could be put would be appreciated)

**Comment by gokcehan** [comment]
@JurisMajors Thank you for your interest in contributing. This has been requested before and I was actually thinking of adding this for a while but never got the chance to do it. I was thinking of using globbing instead of regular expressions as it is easier and more appropriate when working with file names. Go standard library has a function named [filepath.Glob](https://golang.org/pkg/path/filepath/#Glob) for this purpose. We already have a command named `select` for a different purpose. I think a more appropriate name for this new command would be `glob-select`. I guess we can add this command by simply going over the list of files in the current directory and selecting files matching the pattern. You may want to see `nav.toggleSelection` and `nav.toggle` functions in `nav.go` file for this purpose. Also make sure you check "Adding a new builtin command" section in [contributing wiki page](https://github.com/gokcehan/lf/wiki/Contributing#adding-a-new-builtin-command) which should guide you through this. Feel free create a PR early on and I can try to give you suggestions if you get stuck at any point.
