### ISSUE TITLE
Sixel previews not rendering under tmux when using chafa.

### ISSUE THREAD

**Issue by kootrit** [gokcehan/lf#1820]
When trying to preview some images with sixel under tmux, they just don't render but all of my images do render when I'm not using tmux. I'm using ctpv as the previewer and foot as my terminal emulator.
### With tmux
![1730129831_grim](https://github.com/user-attachments/assets/8738771b-068a-4f8a-9540-76c0a23560a1)
### Without tmux
![1730130076_grim](https://github.com/user-attachments/assets/9b15751f-253a-4691-9fe3-3fd66507453c)
Using img2sixel instead of chafa works just fine wether I'm running tmux or not. The problem with img2sixel is that I can't figure out how to convert the height and width of an image reported by lf into pixel size. I can only hardcode the height to make sure the image isn't too big, which works.
The UI starts to break on some images only when using tmux aswell.
![1730130247_grim](https://github.com/user-attachments/assets/e6a84e75-7fe0-4215-912f-350961502aa5)

**Comment by joelim-work** [comment]
Have you tried [using `chafa` directly](https://github.com/gokcehan/lf/wiki/Previews#with-sixel), without using `ctpv` at all?

I don't use sixel on a regular basis, but I tried setting it up very briefly in `wezterm` and I could get images to display under `tmux`:

![image](https://github.com/user-attachments/assets/134810e0-23ab-49d1-88a8-c700239990d1)

**Comment by sonjiku** [comment]
In my case, most images work fine, except for some very specific cases where the filesize is too large(i think). Though I've come to the conclusion that that file size may not be the real culprit.
I switched to using `magick` to create very compressed and "light" images. That seemed to have fixed the problem, but some images continue to not get shown for some gosh darn reason, even though they only take up a few hundred kBs.

**Comment by joelim-work** [comment]
@sonjiku Thank you for looking into this. I did a search in the `tmux` repo and found that the 1 MB limit for sixel images has been mentioned a number of times:

- https://github.com/tmux/tmux/issues/3668#issuecomment-1689490893
- https://github.com/tmux/tmux/issues/3726#issuecomment-1779850535
- https://github.com/tmux/tmux/issues/3959#issuecomment-2107350362
- https://github.com/tmux/tmux/issues/4161#issuecomment-2394764746

Unfortunately I don't think there's much that can be done here, since the issue is to do with `tmux`. However if you want, you can add this limitation as a note in the [wiki](https://github.com/gokcehan/lf/wiki/Previews#with-sixel).

**Comment by kootrit** [comment]
Thanks for looking into this. I guess I'm gonna have to start building tmux from source.

**Comment by sonjiku** [comment]
No worries!
After spending a shamefully long amount of time trying to get the previews to work, and actually managing to do so after using the patch(wnicn was trivial thanks to using NixOS), I learned about `yazi` and after giving it a shot, I switched over to it since previews work out of the box in `foot` (my term of choice) with and without `tmux`, no matter the image size!
