### ISSUE TITLE
Directories with a background color don't render correctly

### ISSUE THREAD

**Issue by neeshy** [gokcehan/lf#1848]
r32:

![2024-11-12-16:46:54 377282762](https://github.com/user-attachments/assets/443f97b4-99c3-4843-ace5-2725a67918ce)

r33:

![2024-11-12-16:47:05 670816048](https://github.com/user-attachments/assets/0c04c04f-d56f-4a20-aed5-fe31f9dd3b69)

This regression originates in b819d90be20eab1ba2f62f8f4e4976288d872f8f

**Comment by joelim-work** [comment]
Thanks for reporting the issue.

That commit changes the UI code so that different components (tag, icon and filename) are rendered separately. Note that the space before the filename is not merely 'padding' - it is actually used to store the [tag](https://github.com/gokcehan/lf/blob/master/doc.md#tag) if there is one. If there isn't a tag then I think it's fine to use the corresponding background color instead, as opposed to not drawing anything at all.

Can you try #1849 to see if it fixes the issue for you?
