### ISSUE TITLE
dotfiles are now shown first before the normal files

### ISSUE THREAD

**Issue by NotMurPh** [gokcehan/lf#1855]
Hi :) so lf used to show these in this order 
1. normal directories
2. DOTdirectories
3. normal files
4. DOTfiles

now its like this: 
1. DOTdirectories
2. normal directories
3. DOTfiles
4. normal files

so the dotfiles now have priority how can i revert this without reversing everything ?

**Comment by joelim-work** [comment]
Ordering dotfiles before non-dotfiles is the proper order, as mentioned in https://github.com/gokcehan/lf/issues/387#issuecomment-645882460. It's also the order that `ls` gives:

```
$ ls -al | head
total 604
drwxr-xr-x  6 joelim joelim  4096 Nov 17 13:07 .
drwx------ 22 joelim joelim  4096 Nov 13 21:04 ..
drwxr-xr-x  9 joelim joelim  4096 Nov 17 13:07 .git
drwxr-xr-x  3 joelim joelim  4096 Oct 22 15:09 .github
drwxr-xr-x  2 joelim joelim  4096 Oct 22 15:09 etc
drwxr-xr-x  2 joelim joelim  4096 Oct 22 15:09 gen
-rw-r--r--  1 joelim joelim    29 Oct 22 15:09 .gitignore
-rw-r--r--  1 joelim joelim  2697 Oct 22 15:09 CONTRIBUTING.md
-rw-r--r--  1 joelim joelim  1072 Jul 14 23:39 LICENSE
```

**Comment by NotMurPh** [comment]
It would make sense to also have an option to sort like so 

1. dir
2. dotdir
3. file
4. dotfile

since dotfiles are hidden, they become quite annoying if you unravel them because they are too meny and clutter your workspace

and i personally think that normal directories or files are usually quite more important, and you need to work with them more often, so showing any hidden file should come second

**Comment by joelim-work** [comment]
`.` comes alphabetically before letters, so that's why the files are sorted in that order. Whether a file is hidden or not doesn't have any effect on this alphabetical order.

What you're asking for here is some custom ordering where hidden files come after non-hidden files because they are not as important. But if hidden files are causing too much clutter for you, then you should be hiding them, not trying to order them towards the bottom.

Sorry, but I think that only common use cases (e.g. sorting by name, sorting by size, placing directories first, etc.) should be supported, and that ordering hidden files later is too niche of a use case when there is already the ability to just hide them instead.
