### ISSUE TITLE
Lf miss identifying files somehow

### ISSUE THREAD

**Issue by Set2Minecraft** [gokcehan/lf#1864]
I am trying to configure LF for colors and icons and for some reason files in certain folders are not matching the correct regex. and instead are matching them to exec's

example: some .txt files are marked with the rocket ship and green. and some have the correct icon and color

I dont know why this is happening, there seems to be no rime or reason. Some files in the same folder have this inconsistency

Help is wanted

**Comment by Set2Minecraft** [comment]
[1.pdf](https://github.com/user-attachments/files/18000892/1.pdf)

Here is an example, the file with the highlight is the correctly sttyled pdf. The other are for some reason not

**Comment by Set2Minecraft** [comment]
[2.pdf](https://github.com/user-attachments/files/18001729/2.pdf)
^ Here is a much better example of the problem. I added example files to show what should be happening.

**Comment by joelim-work** [comment]
Green and rocket ship means that the file is executable, which overrides file extension. I don't know why you have such files as executable though - if you're on Linux then you can change them with `chmod`, but for Windows I'm much less sure about this.

**Comment by Set2Minecraft** [comment]
All the files that have this issue were copied from a windows drive. That is all they have in common. 

One other issue is that while I am doing this, lf is not rechcking the file permissions. so the only way I can accurately check the permissions is to restart lf. This is very tedious and annoying. I have the period internal set to 1 so Im not sure what config option could change this behavoir??

**Comment by joelim-work** [comment]
If you're copying the files from Windows then that makes sense. Windows doesn't have the concept of Linux file permissions, so when copying the files you need to make sure the executable bit is not set or otherwise cleared afterwards. This is an issue with using Windows in general, not an issue with `lf`.

In regards to refreshing file permissions, `set period 1` won't work since it only updates the file if it is modified (`mtime`), and changing the file permissions (`ctime`) is doesn't count as being 'modified'. You can try using `set watch true` instead, which uses filesystem notifications.

**Comment by Set2Minecraft** [comment]
Yea, I'm not blaming LF for windows being windows.
The 'set watch true' works like a charm!

I have ran into another thing though, I like to make to-do lists in terminal file managers ( unusual yes ) and I was making icons for: .todo and .todo.done

*.todo {icon}
*.todo.done {icon}

The .todo files are showing the .todo.done files icons  (regardless of order set in the config file), and the .todo.done icons are showing the default file icons. Is this a simple config setting that ive missed or is it something more complicated?

**Comment by Set2Minecraft** [comment]
Huh, I though it was possible because some extensions is example.icons have a similar execution. 

with https://github.com/gokcehan/lf/blob/master/etc/icons.example#L190 ( line 190 )
also having 2 file extensions. And this extension works ( .gitlab-ci.yml ) as expected in lf which is making me even more confused.

**Comment by joelim-work** [comment]
It is a bit confusing, but `*.gitlab-ci.yml` literally matches the exact filename `.gitlab-ci.yml` - see below in the documentation: https://github.com/gokcehan/lf/blob/master/doc.md#colors

> 5. File Name (e.g. `*README`)

Such a rule would match `.gitlab-ci.yml`, but not `foo.gitlab-ci.yml`.

Technically speaking, a file called `.gitlab-ci.yml` is hidden (starts with a dot), and has an extension of `yml`, but this doesn't matter since the matching done here is simply done on the entire filename. If you don't mind reading through the code, below is the relevant part which determines which icon is used: https://github.com/gokcehan/lf/blob/68a29c92848397e642e060a83f8a1bd7bd979af2/icons.go#L172-L194

**Comment by Set2Minecraft** [comment]
Ah okay, I think I see it. thanks
