### ISSUE TITLE
On symlinks handling

### ISSUE THREAD

**Issue by KenjiTakahashi** [gokcehan/lf#20]
Currently symlinks are handled as they are (i.e. files) and only checked when trying to list the items inside/cd to them.
I think it will be better to treat them transparently by handling their destination instead. This should simplify the logic and also have nice properties to the user, like having symlinks that point at dirs sorted among dirs, instead of files. But we'd still like to know they're symlinks, so that information can be displayed to the user as well.
This will obviously require taking both `Lstat` and `Stat` properties of the items. The performance should not be a problem, because we can avoid one redundant `Sort` inside `ReadDir` on the way, which pretty much evens out the speed.

Now, I've looked through `lf` code and also `ranger` code and I see two ways of doing this.

1. The `ranger` way, store both `Lstat` and `Stat` outputs. I think this is not necessary, as the `Lstat` part is only ever used to check if a file is symlink or not. This can also lead to further fragmentation of the code (more on it below).
2. Derive our own structure for file metadata, which will hold FileInfo + symlink flag [+ possibly something else, if needed]. This will be a bit more work, but looks cleaner to me. Plus, it will probably allow concatenating current `currFile`, `currPath`, etc. methods into one, instead of introducing another one. And it gives a better room for expansion, as required.

I am willing to do this, but I'd like to know what is your opinion on this first, @gokcehan.

**Comment by gokcehan** [comment]
Thanks for bringing this up and asking it first @KenjiTakahashi .

This has been somewhat bugging me as well, having to remember calling `Stat` for symlinks. In addition to the two places you mention we are also doing this in completion if I remember correctly. I thought about cleaning things when I was working on #2 but then I got distracted to something else. I remember it was not very straightforward though.

Now you mention a few different issues. I think we both agree that symlinks should not be treated identical to the files they link to. Currently symlinks pointing to directories are not grouped within other directories. This is different than `ranger` but is similar to `ls` with `--group-directories-first` option on my machine (probably GNU coreutils). Same thing for the file permissions as well. When I'm in doubt I usually try to follow `ls` behavior rather than `ranger`. I don't feel very strong about this though so I guess you can change it or just create an option for it if you like.

Second issue you mention is the redundant sort inside `ioutil.ReadDir`. This should probably be done with `os.Readdir` or `os.Readdirnames` to avoid that extra sort with sort by methods different than `name`. It could also be nice to add a sort by `none` option in the mean time.

**Comment by KenjiTakahashi** [comment]
Not identical, but kinda almost ;-). I'd like to know that it is a symlink and commands should get the symlink location as well (e.g. rename or sth should not rename [or sth] the destination). But when I want to cd or open, I expect it to do so on destination, it doesn't make sense to edit a symlink in vim :-).
Personally, I like links pointing at dirs listed among other dirs, but maybe I'm just used to it. BSD `ls` does not have the option you mentioned, unfortunately.

To use `os.Readdirnames` is exactly what I planned to do. I wasn't really pointing at it as issue, only suggesting that we'll be able to "amortise" additional `.Stat` call by avoiding the sort.

I will try to come up with some code over the weekend, let's see how it turns out.
