### ISSUE TITLE
by default, xdg-open shouldn't be called asynchronously

### ISSUE THREAD

**Issue by mvdan** [gokcehan/lf#211]
For example, I had my xdg-open configured to use a terminal audio player for audio files; this worked fine on ranger.

However, on lf with the default config, whem pressing `l` on a music file, the music would play, but I would still be navigating the folder. It took me a while to figure out that the default is to fork `xdg-open`, so the audio player's command-line controls weren't even accessible.

I ended up configuring `cmd open $xdg-open "$f"`, which I think should be the default. It's always possible for `xdg-open` to decide when or not to fork when opening certain files. For example, I've told mine to not fork when opening text and audio files, as those happen in the same terminal, but all others fork into a graphical window.

The other silly thing is that the fork cases worked normally, but essentially there were two forks taking place. A bit unnecessary :)

**Comment by doronbehar** [comment]
I've encountered this annoying issue as well back when I used Ranger (along with `rifle`). But I don't experience it now with Lf. In Ranger, `rifle` has a configuration option for that: https://github.com/ranger/ranger/blob/v1.9.2/ranger/config/rifle.conf#L38

1. What media player are you using?
2. If it's MPV, What's your `~/.config/mpv/mpv.conf` look like? 
3. What happens when you run on a command line e.g `xdg-open music-file.mp3`?
4. What's the output of this command: `xdg-mime query default $(xdg-mime query filetype music-file.mp3)`?

In my setup, `xdg-open` and Lf open a new window with that media file played with MPV. Even if it doesn't have an image attached to it, it's a whole new window so I don't have any problem controlling it.

**Comment by gokcehan** [comment]
@mvdan It is not easy to decide what should be the default. I could also give examples where async behavior is more desirable. For example, without any configuration with `lf` and `xdg-open`, pdf files open as expected, that is launching and external pdf viewer without locking the terminal. As long as things are configurable, I don't think this should be a big issue. I expect users that prefer terminal applications over others to be able to do some customization according to their own setup.

**Comment by mvdan** [comment]
That makes sense. In that case, perhaps add an entry to the FAQ or README, so that users like me can easily spot what to do. It took me a good fifteen minutes of googling and doc reading before I figured out the right syntax and so on.

**Comment by doronbehar** [comment]
@mvdan You can contribute to the Wiki by yourself with no prior permission  🙂. As for your specific (objectively) bad experience with MPV and `xdg-open`, did you manage to find out if there is a particular reason which makes `mpv` (even with `xdg-open` _forking_) to be attached to no terminal, as you described? Please see the questions in my previous comment.

**Comment by gokcehan** [comment]
@mvdan It is described in "Opening Files" section in the documentation but I understand this could be confusing for new users. I think we can add something about this to the tips wiki page.

**Comment by mvdan** [comment]
Sorry all about the late reply. @doronbehar the reason is pretty simple; mpv with the terminal interface runs in the background, and its controls are inaccessible. From its point of view, this doesn't seem like a bug to me.

Thanks @gokcehan. I'd still argue that those who need the current default should just fix their `xdg-open` setup, but that's a battle I don't want to fight :) Changing the setting works for me, and amending the wiki sounds fine. We can leave this open if anyone wants to make the wiki edit.

**Comment by doronbehar** [comment]
@mvdan Could you answer the questions I've asked you [here](https://github.com/gokcehan/lf/issues/211#issuecomment-520181236)?

I insist on knowing this in order to help you. The point is, that usually If you open an audio file, mpv usually opens a 'GUI' window never the less with which you can control the media.

**Comment by mvdan** [comment]
1) mpv
2) practically empty:
```
volume-max=600
ao=pulse
```
3) it runs on the terminal, with the controls working on the terminal itself. I've never seen mpv opening a window when it's given an audio file.
4) I don't have xdg-mime installed.

**Comment by mvdan** [comment]
I'd also like to clarify that mpv is not the issue here. I use plenty of other terminal-based UIs, such as text editors. Requiring all `xdg-open` programs to open a new window is not good design, in my opinion.

**Comment by doronbehar** [comment]
Oh and version?

**Comment by mvdan** [comment]
```
$ mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Thu Oct 10 20:08:23 UTC 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.1
```

**Comment by doronbehar** [comment]
My `mpv.desktop` is:

```
[Desktop Entry]
Type=Application
Name=mpv Media Player
Name[ca]=Reproductor multimèdia mpv
Name[cs]=mpv přehrávač
Name[da]=mpv-medieafspiller
Name[fr]=Lecteur multimédia mpv
Name[pl]=Odtwarzacz mpv
Name[ru]=Проигрыватель mpv
Name[zh_CN]=mpv 媒体播放器
Name[zh_TW]=mpv 媒體播放器
GenericName=Multimedia player
GenericName[cs]=Multimediální přehrávač
GenericName[da]=Multimedieafspiller
GenericName[fr]=Lecteur multimédia
GenericName[zh_CN]=多媒体播放器
GenericName[zh_TW]=多媒體播放器
Comment=Play movies and songs
Comment[ca]=Reproduïu vídeos i cançons
Comment[cs]=Přehrává filmy a hudbu
Comment[da]=Afspil film og sange
Comment[de]=Filme und Musik abspielen
Comment[es]=Reproduzca vídeos y canciones
Comment[fr]=Lire des vidéos et des musiques
Comment[it]=Lettore multimediale
Comment[pl]=Odtwarzaj filmy i muzykę
Comment[ru]=Воспроизвести фильмы и музыку
Comment[zh_CN]=播放电影和歌曲
Comment[zh_TW]=播放電影和歌曲
Icon=mpv
TryExec=mpv
Exec=mpv --player-operation-mode=pseudo-gui -- %U
Terminal=false
Categories=AudioVideo;Audio;Video;Player;TV;
MimeType=application/ogg;application/x-ogg;application/mxf;application/sdp;application/smil;application/x-smil;application/streamingmedia;application/x-streamingmedia;application/vnd.rn-realmedia;application/vnd.rn-realmedia-vbr;audio/aac;audio/x-aac;audio/vnd.dolby.heaac.1;audio/vnd.dolby.heaac.2;audio/aiff;audio/x-aiff;audio/m4a;audio/x-m4a;application/x-extension-m4a;audio/mp1;audio/x-mp1;audio/mp2;audio/x-mp2;audio/mp3;audio/x-mp3;audio/mpeg;audio/mpeg2;audio/mpeg3;audio/mpegurl;audio/x-mpegurl;audio/mpg;audio/x-mpg;audio/rn-mpeg;audio/musepack;audio/x-musepack;audio/ogg;audio/scpls;audio/x-scpls;audio/vnd.rn-realaudio;audio/wav;audio/x-pn-wav;audio/x-pn-windows-pcm;audio/x-realaudio;audio/x-pn-realaudio;audio/x-ms-wma;audio/x-pls;audio/x-wav;video/mpeg;video/x-mpeg2;video/x-mpeg3;video/mp4v-es;video/x-m4v;video/mp4;application/x-extension-mp4;video/divx;video/vnd.divx;video/msvideo;video/x-msvideo;video/ogg;video/quicktime;video/vnd.rn-realvideo;video/x-ms-afs;video/x-ms-asf;audio/x-ms-asf;application/vnd.ms-asf;video/x-ms-wmv;video/x-ms-wmx;video/x-ms-wvxvideo;video/x-avi;video/avi;video/x-flic;video/fli;video/x-flc;video/flv;video/x-flv;video/x-theora;video/x-theora+ogg;video/x-matroska;video/mkv;audio/x-matroska;application/x-matroska;video/webm;audio/webm;audio/vorbis;audio/x-vorbis;audio/x-vorbis+ogg;video/x-ogm;video/x-ogm+ogg;application/x-ogm;application/x-ogm-audio;application/x-ogm-video;application/x-shorten;audio/x-shorten;audio/x-ape;audio/x-wavpack;audio/x-tta;audio/AMR;audio/ac3;audio/eac3;audio/amr-wb;video/mp2t;audio/flac;audio/mp4;application/x-mpegurl;video/vnd.mpegurl;application/vnd.apple.mpegurl;audio/x-pn-au;video/3gp;video/3gpp;video/3gpp2;audio/3gpp;audio/3gpp2;video/dv;audio/dv;audio/opus;audio/vnd.dts;audio/vnd.dts.hd;audio/x-adpcm;application/x-cue;audio/m3u;
X-KDE-Protocols=ftp,http,https,mms,rtmp,rtsp,sftp,smb
```

Note the line with `Exec=`.

**Comment by mvdan** [comment]
I have a custom xdg-open setup with `linopen`, so it simply calls `mpv` alone. The desktop file is ignored entirely. You can call that an exotic `xdg-open` setup, which is probably the source of the inconsistencies. I can't find official docs on xdg-open being required to spawn graphical programs.

**Comment by doronbehar** [comment]
Well then that's it @mvdan. If you'll somehow arrange your setup to make `xdg-open` run `mpv` with these command line options, you won't have to touch your `lfrc`.

**Comment by mvdan** [comment]
Sure, but to reiterate, this is not specific to mpv. Unless I'm missing something, it should be possible to set up terminal UIs with xdg-open. Which it is, if you skip the default setting.

**Comment by doronbehar** [comment]
Well then this is exactly the dilemma faced by terminal file managers and no other programs face. `xdg-open` is meant for graphical programs and therefor in our case it (should) open any media files comfortably thanks to the command line options `mpv.desktop` has.

In comparison, running `xdg-open file.txt` opens `file.txt` in a new terminal / GUI editor's new window - as you'd expect if you had used a graphical file manager. This is usually not desired when using a terminal file browser and that's why you'd probably want to use `e` when hovering a text file you'd want to use the same terminal to edit / view it.

Ranger's `rifle` kind of solves this dilemma specifically for terminal file mangers by essentially re-implementing most of `xdg-open` in Python and  using a single configuration file. With rifle you can declare that for example:

- `text/*` files will be openned by `$EDITOR` in the current terminal
- `application/media-whatever` will be openned with `mpv --player-operation-mode=pseudo-gui -- %U`

Etc.

@mvdan I hope this helps. FWIW, I don't think @gokcehan would want to implement rifle under the wings of this project.

You can use install ranger and only use `rifle` as your `$OPENER`.
