### ISSUE TITLE
Support for navigating history of jumps

### ISSUE THREAD

**Issue by aidam38** [gokcehan/lf#212]
Hi, there is one crucial functionality not present at the moment in lf that I even think I must be missing something. It's going back in history of jumps, example use case:
**I'm configuring some program in my home directory but I need to quickly jump to /etc to edit some config file but then come back immediately. In general when you are very deep in some directory and you accidentally bookmark away, you have to travel all the way back.**
Bind like `map <c-j> back` would solve this, I believe ranger has it.
Thanks.

**Comment by gokcehan** [comment]
@aidam38 There is the automatic `'` mark for the last visited directory. I think you can use it to for your usecase. However, there is no general mechanism to jump back more than once (i.e. jumplist).

**Comment by doronbehar** [comment]
As an fzf user, I think it would have been awesome if we could search all already visited directories in the current Lf session. Such functionality could be easily built around fzf if only Lf would provide e.g an environmental variable that will be available in all child shells or a command that will print these and that could be used with `lf -remote`.

This enhancement would help @aidam38 as well because it'll be possible to select a directory from the history stack via it's position.

**Comment by hajdamak** [comment]
Is it possible map mark `'` to shortcut? If I add `map <a-h> mark-load '` to config it still asks me to select mark after using this shortcut.

**Comment by gokcehan** [comment]
@hajdamak Assuming your `mark-load` command is still mapped to `'` as default, you can try the following:

    map <a-h> :push ''

**Comment by hajdamak** [comment]
@gokcehan Yeap, this works fine. Thanks. 
This covers most important use case. Although having full history would be very handy.

**Comment by rafi** [comment]
**Wish** there was a simple way to jump through directory history stack backwards and forwards, irrelevant of fzf, _e.g._ `map H history-stack-backward` and `map L history-stack-forward`

**Comment by forgitmenots** [comment]
Hello, not sure if this feature is a part of lf yet but I made something that works for me. I'm a programming newbie though, so it may damage your computer or not do what you want, in which case you can improve it or use something else. But I like lf file manager so I decided to make it for fun.

```
map h :updir ; dir-history save
map l :open ; dir-history save
map b dir-history prev
map f dir-history next

cmd dir-history ${{

	list="/home/user/.config/lf/dirlist"

	if [[ "$1" == "save" ]]; then
		all () { lines+=("${src[@]}") ; lines+=("$(pwd)") ; }
		update () { printf '%s\n' "${lines[@]}" > $list ; }
  		mapfile -tn 0 src < "$list"
		all
		if [[ "${lines[-1]}" != "${lines[-2]}" ]]; then
  			if [[ "${#lines[@]}" -gt 29 ]]; then
				printf '%s\n' "${lines[@]: -29}" > $list
			else
				update
  			fi
		fi

	elif [[ "$1" == "next" ]]; then 
		mapfile sort < "$list"
  		sort+=("${sort[0]}")
  		while [ "${#sort[@]}" -gt 0 ] ; do
			sort=("${sort[@]:1}")
		[[ "${#sort[@]}" -gt 0 ]] && load+=("${sort[0]}")
  	done

	elif [[ "$1" == "prev" ]]; then
		mapfile init < "$list"
  		sort=("${init[-1]}")
  		sort+=("${init[@]:0:${#init[@]} - 1}") 
  	while [ "${#sort[@]}" -gt 0 ] ; do
		[[ "${#sort[@]}" -gt 0 ]] && load+=("${sort[0]}")
		sort=("${sort[@]:1}")
  	done
	fi

	if [[ "$1" == "prev" ]] || [[ "$1" == "next" ]]; then
  	printf '%s' "${load[@]}" > $list
		dir="${load[-1]}"
		cmd="cd"
		lf -remote "send $id $cmd \"$dir\"" 
	fi
}}
```

To change the amount/number of history entries change the both the numbers 29 to something lower or higher. And change /home/user to your own path.

**Comment by forgitmenots** [comment]
Hello, I made something for this.  

It saves history when you go back or forward, and has a separate history file for each instance of lf, creating a folder called historydir in ~/.config/lf to save it in

```
map h :updir ; dir-history save
map l :open ; dir-history save
map b dir-history prev
map f dir-history next

cmd dir-history ${{

max="30"
list="${HOME}/.config/lf/historydir/dirlist$id"
[ -d "${list%/*}" ] || mkdir "${list%/*}"
[ -f $list ] || touch "$list"
mapfile -tn 0 src < "${list}" # get history 

# save current dir as history entry
if [[ "$1" == "save" ]]; then
    update () { printf '%s\n' "${lines[@]}" > "$list" ; }
    lines+=("${src[@]}") ; lines+=("$(pwd)")
    if [[ "${#lines[@]}" -lt 2 ]] ; then
        update
    elif [[ "${lines[-1]}" != "${lines[-2]}" ]]; then
        if [[ "${#lines[@]}" -gt $max ]]; then
            printf '%s\n' "${lines[@]: -$max}" > "$list"
        else
            update
        fi
    fi

# move first history line to the end
elif [[ "$1" == "next" ]]; then 
    sort+=("${src[0]}")
    while [ "${#src[@]}" -gt 0 ] ; do
	sort=("${src[@]:1}")
	[[ "${#src[@]}" -gt 0 ]] && load+=("${src[0]}")
    done

# move last history line to beginning
elif [[ "$1" == "prev" ]]; then 
    sort=("${src[-1]}") 
    sort+=("${src[@]:0:${#src[@]} - 1}") 
    while [ "${#sort[@]}" -gt 0 ] ; do
	[[ "${#sort[@]}" -gt 0 ]] && load+=("${sort[0]}")
	sort=("${sort[@]:1}")
    done
fi

if [[ "$1" == "prev" ]] || [[ "$1" == "next" ]]; then
    printf '%s' "${load[@]}" > "$list"
    dir="${load[-1]}"
    cmd="cd"
    lf -remote "send $id $cmd \"$dir\"" 
fi

}}


```

Not sure if this feature is a part of lf yet but this works for me. But I'm a programming newbie, so I can't guarantee no bugs or design flaw. It might not work or worse it could damage your computer.

**Comment by mvrozanti** [comment]
For what's worth, I managed to get a (close enough) behavior with the following in `lfrc`:
```
$pwd > ~/.dir-stack-lf
cmd on-cd &{{ 
    SKIP=`cat ~/.do_skip`
    if [ $SKIP -ne 1 ]; then
        pwd >> ~/.dir-stack-lf
    fi
    echo 0 > ~/.do_skip
}}
cmd go-back ${{ 
    last_dir="`tail -2 ~/.dir-stack-lf|head -1|sed 's;/;\\/;g'`"
    lf -remote "send $id cd \"$last_dir\""
    # egrep -vE "^$last_dir$" ~/.dir-stack-lf > /tmp/lf-last-dirs
    egrep -vE "^$last_dir$" ~/.dir-stack-lf > /tmp/lf-last-dirs
    # sed '$d' /tmp/lf-last-dirs > ~/.dir-stack-lf
    mv /tmp/lf-last-dirs ~/.dir-stack-lf
    echo 1 > ~/.do_skip
}}
map H go-back
```

**Comment by wincent** [comment]
Neat idea @mvrozanti. I didn't know about the `on-cd` command; super useful. Took your idea and tweaked it in a few of ways:

- Keep one jump list file per client (means that if you have multiple `lf` instances running they don't clobber each other).
- Preserve jump list file across invocations of `lf` (use of `uniq` imposes an upper bound on the size of the list file).
- Using `sed` instead of `head` + `tail` because it should be faster.

Probably also "highly improvable though", just like yours 😂. Thanks for sharing.

```
map <f-6> jump-in
map <c-o> jump-out

${{
  JUMP_LIST=~/.config/lf/jump-list.$id
  JUMP_INDEX=~/.config/lf/jump-index.$id
  JUMPING=~/.config/lf/jumping.$id
  $pwd >> $JUMP_LIST
  uniq $JUMP_LIST $JUMP_LIST.uniq
  mv $JUMP_LIST.uniq $JUMP_LIST
  cat $JUMP_LIST | wc -l | sed -e 's/ //g' > $JUMP_INDEX
  rm -f $JUMPING
}}

cmd jump-in ${{
  JUMP_LIST=~/.config/lf/jump-list.$id
  JUMP_INDEX=~/.config/lf/jump-index.$id
  INDEX=$(expr `cat $JUMP_INDEX` + 1)
  MAX=$(cat $JUMP_LIST | wc -l)
  if [ $INDEX -le $MAX ]; then
    echo $INDEX > $JUMP_INDEX
    touch ~/.config/lf/jumping.$id

    # https://stackoverflow.com/a/6022431/2103996
    TARGET=$(sed "${INDEX}q;d" $JUMP_LIST)
    lf -remote "send $id cd \"$TARGET\""
  fi
}}

cmd jump-out ${{
  JUMP_LIST=~/.config/lf/jump-list.$id
  JUMP_INDEX=~/.config/lf/jump-index.$id
  INDEX=$(expr `cat $JUMP_INDEX` - 1)
  if [ $INDEX -gt 0 ]; then
    echo $INDEX > $JUMP_INDEX
    touch ~/.config/lf/jumping.$id

    # https://stackoverflow.com/a/6022431/2103996
    TARGET=$(sed "${INDEX}q;d" $JUMP_LIST)
    lf -remote "send $id cd \"$TARGET\""
  fi
}}

cmd on-cd &{{
  JUMP_LIST=~/.config/lf/jump-list.$id
  JUMP_INDEX=~/.config/lf/jump-index.$id
  JUMPING=~/.config/lf/jumping.$id
  if [ -e $JUMPING ]; then
    # If jumping, just move.
    rm $JUMPING
  else
    # Otherwise, truncate jump list at current index and record new directory.
    head -n $(cat $JUMP_INDEX) $JUMP_LIST > $JUMP_LIST.new
    pwd >> $JUMP_LIST.new
    mv $JUMP_LIST.new $JUMP_LIST
    INDEX=$(expr `cat $JUMP_LIST | wc -l`)
    echo $INDEX > $JUMP_INDEX
  fi
}}
```

**Comment by mvrozanti** [comment]
That mapping is horrible

That being said, I'm copying this to my lfrc.

**Comment by MahouShoujoMivutilde** [comment]
I also wanted this, but found that having not just history, but a ranked by frequency and recency list is more useful.

Something like this can be done with [z](https://github.com/rupa/z). Imo, it is a better way of doing it, since it also accounts for your cd's in interactive shell. 

If you want just recency - that also possible via `z -t`. But note that database is the same across all lf instances. In that case - yes, separate simple jump lists as presented above are better. 

But if you like me - here is how you can integrate z into lf.

Since z is designed to be sourced in shell rc file to work - we will need two simple helper scripts.

First one - `z-add`, as name suggests - is used to add directory into z database.

```sh
#!/usr/bin/env bash

source /usr/share/z/z.sh

# --add is undocumented for some reason, but it works
_z --add "$1"
```

Second - `z-list` - to list (ranked) directories from database

```sh
#!/usr/bin/env bash

source /usr/share/z/z.sh

_z -l 2>&1
```

Assuming those two somewhere in your $PATH - in lfrc add

```
cmd on-cd &{{
    z-add "$PWD"
}}
on-cd

# and fzf integration
cmd fzf_z ${{
    sel="$(z-list | sed "s|$HOME|~|g" | fzf +s --nth=2.. --tac | sed "s|~|$HOME|g;s|^[0-9,.]* *||")"
    [ -d "$sel" ] && lf -remote "send $id cd \"$sel\""
}}

map <c-g> fzf_z
```

Now when you'll press ctrl+g you'll be presented with ranked list of all visited directories:

![image](https://user-images.githubusercontent.com/14999778/96034656-8542c580-0e6a-11eb-8c20-5ebf73fca8e8.png)

If  you want ranking by recency only - change `-l` to `-t` in `z-add`.

**Comment by laktak** [comment]
If you want to test or have some feedback, I've added a PR for this feature here: #755
