### ISSUE TITLE
File path and window history inquiry

### ISSUE THREAD

**Issue by quantttum** [gokcehan/lf#243]
Hello first of all I need to say Im not a programmer and I also lack the skills to manage efficiently a Linux desktop so Im stuck in Windows 7 where I use LF adding its executable to the Path Environment Variable and running it through Cmder (because the default conmmand interpreter cmd.exe wont display LF correctly due to some configurations I did in the past), so Im very happy to see this project is commited to be compatible with Windows because Im an avid gVim user and Im aware how useful and incredibly needed could be a Vim-like file explorer in the broken toy that is the Microsoft Operative System.

That being said I have 2 inquiries:

1) Is there currently a default feature or maybe a known workaround to copy to clipboard the full path of a single or mutiple selected file/s and/or folder/s

2) I also would like to ask if the quit command could not be by default a key you can press by accident like "q" and therefore lose all your current session work in a blink, even if the user can remap it I think it should be hardwired by default to a more thoroughly option like ":q" for example (like happens in Vim).

This leads me to also suggest "q" should be used instead by default like a modal command for a multiple "Window History" option (again Vim-like) where "q:" opens an editable command window history and "q/" opens an editable search window history, "editable" being the keyword here, something that would greatly enhance LF usage in my humble opinion.

Finally this editable window history could be expanded to other fields like for example the already requested #212 "history jumps" (partly like :ju behaves in Vim but also editable here) or the very interesing #128 "filtering" request where the user controls what filters apply to be shown by LF while being able to edit and modify them anytime in the background.

Thank you for your help and sorry I cannot give solutions only ideas since I lack the needed knowledge.

**Comment by gokcehan** [comment]
@quantttum Thank you for the feedback.

Regarding your first question, it is doable on linux systems using `xsel` or `xclip` with something like:

    $echo $f | xsel

I'm not aware of an equivalent command line clipboard manager program in windows but I feel like there should be some.

Regarding your second question, first I should say that default keybindings are always a problem. It is impossible to make everyone happy with default behaviors. If we remove `q` binding, I'm sure we will have some `ranger` users complaining about the lack of `q` key in `lf`. This is why we try to be as configurable as possible. If you like, you can unmap the current binding with `map q`. You can then quit from the command line using `:quit` command. You may also want to assign a different keybinding for quitting like `map Q quit`. Hope this helps.

Editable window history is much more complicated. Vim can easily do this because essentially it is a text editor. We don't have any editing components implemented in `lf`. Even if we implement some editing capabilities, I feel like demands would not be finished until we implement a fully fledged text editor on top of it. I think an easier way to achieve this would be to launch `vim` with the content of a previous command and then execute the changed command afterwards using remote commands, much like `<c-x> <c-e>` in bash shell. I don't have such a command ready on the top of my head but I think it should not be too difficult.
