### ISSUE TITLE
Recent escape-character commits break config file parsing

### ISSUE THREAD

**Issue by matoro** [gokcehan/lf#249]
After building from master since the last 3 commits related to escape characters, config file parsing on Linux is broken.  Previously working config file shows:

```
unexpected token: fx\n"
```

and no configuration changes take place.

Edit:  I bisected and found that it was the first commit, https://github.com/gokcehan/lf/commit/7a4d1cc2757b267dc23b00254ac9498d3634dc49 that created the issue.

**Comment by gokcehan** [comment]
@matoro Thanks for reporting this issue. I was trying to do some refactoring to more closely mimic the behavior of shell for quoting within double quotes and it seems that I messed up and pushed too early without testing things properly. I have now pushed a commit to fix the problem. If the problem is fixed for you as well, feel free to close the issue.

**Comment by matoro** [comment]
> @matoro Thanks for reporting this issue. I was trying to do some refactoring to more closely mimic the behavior of shell for quoting within double quotes and it seems that I messed up and pushed too early without testing things properly. I have now pushed a commit to fix the problem. If the problem is fixed for you as well, feel free to close the issue.

Yes that fixed it, thank you.
