### ISSUE TITLE
Copy paste issues

### ISSUE THREAD

**Issue by luisdavim** [gokcehan/lf#255]
When I open a text file with `nvim` from `lf` and paste text into it, using the Os clipboard not `vim`'s yank and paste, some times I get garbled output and it starts printing out my key strokes so I get stuck in `vim`, the only way to get out is by killing `lf`. I also have to `reset` the terminal (or `tmux` pane) where `lf` was running after this.

This works fine when I use `nvim`/`vim` outside of `lf`.

**Comment by gokcehan** [comment]
@luisdavim Which command type are you using to launch `nvim` from within `lf.` For `$` and `!` our termbox is closed before running the shell command so you should not see any difference than running `nvim` from the shell. Also what terminal are you using?

**Comment by luisdavim** [comment]
Hi, this is my config: https://github.com/luisdavim/dotfiles/blob/master/files/config/lf/lfrc
```
echo $EDITOR
nvim
type nvim
nvim is /usr/local/bin/nvim
```
I'm using `zsh` on `tmux` in `alacritty` and I never have these issues when using `nvim` directly.

**Comment by luisdavim** [comment]
should I add an extra `$`?
```
text/*) $$EDITOR $fx;;
```

**Comment by gokcehan** [comment]
@luisdavim You should not need an extra `$` there.

Which operating system are you on? And when you say pasting using the os clipboard, how exactly do you mean? Are you pasting text in neovim insert mode using alacritty paste keybinding? Have you tried `paste` option in neovim to see if it makes a difference? Also do you have this same issue with regular vim? Lastly, can you try a different terminal emulator to see if it makes a difference?

**Comment by luisdavim** [comment]
I'm on MacOS. I mean pressing `CMD+v` whilst in insert mode. If I press `p` whilst in normal mode I have no issues. But using `CMD+v` in insert mode when running `nvim` outside of `lf` is not a problem either, even if I'm using `ranger`.

**Comment by luisdavim** [comment]
I will try `vim` and other terminals and report back.

**Comment by luisdavim** [comment]
I've tried with other terminals and the issue is still there. I wasn't able to reproduce it with `vim` yet, only with `neovim`.
Another thing that I've noticed is that if I scroll fast with my mouse in `nvim` sometimes, when running through `lf` it goes into insert mode and adds garbage to the file, some other times it prints garbage into the command area and blocks scrolling.
Could the issues that I have all be coming from the fact that I have the mouse mode enabled in `nvim`/`vim`?

**Comment by gokcehan** [comment]
@luisdavim The issue is not only specific to neovim but also I think to MacOS as well because I can't produce it on my Linux machine. Can you confirm this also happens when you run neovim without any configuration? (i.e. `nvim -u NONE`)

Termbox have some extra logic for the escape delaying mechanism on MacOS ([escwait_darwin.go](https://github.com/nsf/termbox-go/blob/master/escwait_darwin.go)), but termbox is closed before running `$` commands so I doubt it is related. If you have a go installation, can you try the following program to see if the issue persists?

	package main

	import (
		"os"
		"os/exec"
	)

	func main() {
		cmd := exec.Command("/bin/sh", "-c", "nvim")

		cmd.Stdin = os.Stdin
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr

		if err := cmd.Run(); err != nil {
			panic(err)
		}
	}

Also since you can only observe this on neovim but not on vim, maybe this is a good candidate as an issue on neovim side as well? They might have a better understanding of the differences between vim and neovim to identify the problem here.

**Comment by luisdavim** [comment]
Hi, sorry for the late reply.
I was able to reproduce this with `nvim` outside of `lf`, it just seems to happen more often when running with `lf` and it never happens with `vim8` so I'm convinced this is a `nvim` bug.
Thanks for your help.
