### ISSUE TITLE
read-only mode

### ISSUE THREAD

**Issue by v217** [gokcehan/lf#259]
Sorry, if that has been asked before, but is there a commandline flag or a shortcut to toggle read-only mode? By read-only mode I mean you have to drop into a shell to modify anything.

**Comment by gokcehan** [comment]
@v217 We don't have such a flag or shortcut. In general, it would be difficult to implement such a thing because we're not interpreting the shell commands ourselves but only pass them to the shell to execute. If you're worried, you may try to unmap file operation shortcuts (e.g. `yank`, `delete`, `paste`) and also avoid using the command line mode at all (maybe also unmap these as well).
