### ISSUE TITLE
Setting the window title of the terminal

### ISSUE THREAD

**Issue by nostdm** [gokcehan/lf#262]
Currently when running `lf` in the terminal the window title gets set by the shell to the name of the binary, in this case to "`lf`".

Personally, I'd like to disable the `promptfmt=""` and instead put the directory name in the window title. I managed to set the initial window title by invoking `echo "\033]0;$PWD\007"` before launching the `lf` binary. But this solution has multiple problems:

- The title doesn't update dynamically when you change a directory
- When another program is launched from `lf` (e.g. `vim`) and sets the window title as well, that new title won't go away after exiting the program (i.e. it will not be cleared by `lf`)

It would be great if `lf` could manage the window title dynamically, perhaps with an option that also allows you to set the format (e.g. adding an icon):

```
set titlefmt " %w"
```

**Comment by gokcehan** [comment]
@nostdm I haven't been using terminal titles for a while so I don't exactly know how things work. Termbox does not seem to have anything about setting the terminal title. Your terminal may be setting the terminal title on its own. That sequence you invoke is I'm guessing the xterm escape sequence for setting the terminal title. It's not standard and it may not work for other terminals and on other platforms (i.e. OSX, Windows). In general, termbox avoid adding features that would work on only a single platform, and since we're using termbox we also mostly use the same philosophy. I'm marking the issue as a feature request but I don't think there is an easy way to add this at this point.

**Comment by lucas-mior** [comment]
The feature described by @nostdm  would be very useful since I use tabbed (https://tools.suckless.org/tabbed/) to get multilpe tabs of lf in urxvt. The tab gets its title from WM_NAME property which can be set using 
`echo "\033]0; $PWD\007"`
as @nostdm stated. 
Is there a way to send escape sequences when lf changes it's current directory?

**Comment by gokcehan** [comment]
@lucas-mior Doing an action when lf changes directory requires a more general hooking system to be implemented (something like autocmd in vim) which is currently not yet available. You should be able to send escape sequences manually using shell commands. You might try to run a script that sends escape sequences periodically though I don't think it is a good idea.

**Comment by lucas-mior** [comment]
I've mapped the following:
`map l :open; $name.sh 
map h :updir; $name.sh`
where name.sh is a script that runs 
`printf "\033]0; $PWD\007"`
That works, but there is a flash everytime I press h or l, (due to the invocation of the shell (?!)), which is quite annoying. 
I have tryed to map it with % or &, but none of that works. 
Using % it just prints 
]0; $PWD
(correctly printing my present working directory)
and using &, nothing happens.

Am I missing something?

**Comment by gokcehan** [comment]
@lucas-mior I don't think you're missing something. `&` command does not connect its stdout so it won't work. `%` command does not send control characters to the terminal so it doesn't work either. I think this is currently only possible with `$` commands.

**Comment by ShawnMcCool** [comment]
I'm not complaining but I expected this to be default behavior.

In the vein of the way terminals typically are configured to update the title I'd love to be able to disable the prompt and have the window title show the current path.

I'm an I3 user and having multiple instances of LF running while easily being able to see which instance is where in various tiling circumstances would be a huge win.

**Comment by gokcehan** [comment]
FYI, hooking mechanism to run a command when the directory is changed is implemented as `on-cd` and it's in the documentation. The issue described here still persists though, as you can't print escape sequences with `%` commands.

@ShawnMcCool Maybe there is a way to change titles with i3 commands instead of terminal escapes. I have my titlebars disabled in my i3 setup. Disabling promptline in lf is still not possible so it is better to use the promptline instead of titlebars for now. I think it is also better if you're running multiple lf instances in a single terminal using tmux.

**Comment by MahouShoujoMivutilde** [comment]
Got this working without shell flashing via `>/dev/tty`

```sh
# NOTE: does not fire until you change the directory within lf
cmd on-cd &{{
    printf "\033]0; $PWD\007" > /dev/tty
}}
```

<details>
  <summary>demo</summary>
 
  ![demo](https://user-images.githubusercontent.com/14999778/92522474-73488400-f227-11ea-9300-5daf537d6291.gif)

 (it actually changes instantly, i just pull updates only once per second)
</details>

**Comment by MahouShoujoMivutilde** [comment]
@gokcehan, [done](https://github.com/gokcehan/lf/wiki/Tips#show-current-directory-in-window-title).

**Comment by gokcehan** [comment]
@MahouShoujoMivutilde Nice, thanks.

I think we can close this issue now. Feel free to leave further comments if any.
