### ISSUE TITLE
The cursor cannot reach the end of a long filename in rename prompt.

### ISSUE THREAD

**Issue by crocket** [gokcehan/lf#269]
Version: lf-r13
Operating System: Gentoo Linux

Try to rename

```
おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|おはよう|.txt
```

by pressing `r` on it.

The cursor cannot reach the end of a filename in the rename prompt.

**Comment by gokcehan** [comment]
@crocket Is this specific to CJK characters or it happens in other files with a long name as well?

**Comment by crocket** [comment]
I think it is specific to double-width characters.

**Comment by gokcehan** [comment]
@crocket I have tried this again and I'm able to add some characters to the file name you provide, though it doesn't show up in the ui. The problem is that when the filename does not fit to the statusline, it doesn't show the name properly. It is replicable with a filename like `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.txt` as well. So we need to implement a mechanism to show long filenames in the prompt (e.g. by adding `~` to the beginning and/or the end depending on the current displayed portion).

**Comment by nsklaus** [comment]
it's not specific to CJK characters, it happens to me too.
i'm using dwm and st, as such my lf window can become quite small in some case, as in the screenshot below. i like it like that. but when i rename a long file, the cursor does not allow sliding to the end of filename, i can only see the part of the filename that is visible when i press 'r'. so i often 'rename' in the blind regarding to end part of the string that i cannot see..

the full string for that filename is: `"some_long_filename_to_test_lf_rename_with_it_you_cannot_see_the_end.txt"`
and indeed no matter what i do i cannot see the end of that long string. cursor doesn't scroll the area.
it was the same when i created the file, i pressed `return` to input a shell command, and typed `touch some_long_filename_to_test_lf_rename_with_it_you_cannot_see_the_end.txt` toward the end of that string i was inputing, i could not see what i typed either, the visible part was always "touch some_long_filename_to_test_lf_rename_with_it_you_can" .. then typing in the dark.. 

![screen](https://user-images.githubusercontent.com/6810861/89731449-5f064100-da47-11ea-9863-386c4e0e449e.png)

**Comment by crocket** [comment]
I want to scroll along a long file name.

**Comment by gokcehan** [comment]
@crocket I don't think it's impossible, it's just that I didn't have a chance to work on this.

If anyone wants to tackle this, the related code is in `ui.draw` method in `ui.go`. There is a switch statement that draws the statusline with different prefixes using `ui.msgWin.print` calls. Instead of naively printing `ui.cmdAccLeft` and `ui.cmdAccRight`, one should trim these slices accordingly with respect to the window width to implement a scrolling behavior.

**Comment by gokcehan** [comment]
Sorry for taking too long for this issue. I have now implemented basic scrolling in the prompt line that keeps the cursor at the last column for long lines. We might implement a dynamic cursor position in the future but it is not easy with all command line movements so maybe it is better to keep it simple. Closing the issue now. Feel free to report back if there is still an issue.

**Comment by crocket** [comment]
Closing the issue for you. I think I will rely on terminal renamers for the foresseable future.
