### ISSUE TITLE
icons don't show

### ISSUE THREAD

**Issue by sharethewisdom** [gokcehan/lf#294]
This issue is fixed with https://github.com/gokcehan/lf/pull/257, and can be closed if that's merged.

I use a Nerdfont, and I can see icons in the terminal (termite). `$LF_ICONS` was correctly exported. Icons can appear in filenames and in previews, but they're not showing when using `set icons` either in lfrc or as a command. I'm not sure what I did wrong.

```
broken version:             r13-27-g3c5abbb
version with applied patch: r13-23-g93a8fe6
uname -rs:                  Linux 5.5.1-arch1-1
```

**Comment by gokcehan** [comment]
@sharethewisdom That patch is unlikely to be merged at this point. Can you give more details about this issue? What is the value of `$LF_ICONS`? Are you able to display default icons without `$LF_ICONS` variable?

**Comment by blayz3r** [comment]
How do you set $LF_ICONS on windows

**Comment by gokcehan** [comment]
@blayz3r It depends whether you use `cmd.exe` or `powershell`. I think you can also define an environmental variable from the graphical interface. I'm not sure nerdfonts or any such other fonts are available in windows though.

**Comment by blayz3r** [comment]
I think windows 10 defaults to powershell. I have NF with Gvim +devicons working. When I set LF_ICONS the icons are blank because the gui interface can't read special characters. Another question I had was if we can set the preview program on Windows. I guess a Windows Lfrc that mimics the Linux one would answer all my questions. All the Linux commands seem to be working touch,mv, delete etc.. So I am a bit confused by the shell being powershell

**Comment by ThoreKolms** [comment]
> How do you set $LF_ICONS on windows

`$env:LF_ICONS="<whatever icons you wish, see [wiki](https://github.com/gokcehan/lf/wiki/Icons)>"`
put that in your powershell profile (`notepad $PROFILE`).

For me the icons were not working, because i copied them from the [wiki](https://github.com/gokcehan/lf/wiki/Icons) where they have backslashes which do not work in powershell. I have removed all backslashes and newlines and now it works (same for setting LF_COLORS).

**Comment by w-kote** [comment]
```pwsh
$Env:LF_ICONS="di=:fi=:<etc..>"
```

put that in powershell profile.
it works.


https://github.com/gokcehan/lf/blob/c0c85f206fbd5011c10cc839ced94acb444a1b9a/etc/icons.example#L128

but, it does not work including that icon setting.

```
$Env:LF_ICONS = ((Get-Content -Path ($Env:USERPROFILE + '\AppData\Local\lf\icons') -Encoding utf8) -replace '\s*#.*','' -replace '(?<File_Regex>[\S]+)\s+(?<Icon_String>\S)','${File_Regex}=${Icon_String}') | ?{$_ -ne ""} | Join-string -Separator ':'
```

this script in powershell profile is usefull for fetching icons from icons file, lf using powershell.

**Comment by nasu-oldhand** [comment]
```pwsh
$Env:LF_ICONS="di=:fi=:<etc..>"
```

put that in powershell profile.
it works.


https://github.com/gokcehan/lf/blob/c0c85f206fbd5011c10cc839ced94acb444a1b9a/etc/icons.example#L128

but, it does not work including that icon setting.

```
$Env:LF_ICONS = ((Get-Content -Path ($Env:USERPROFILE + '\AppData\Local\lf\icons') -Encoding utf8) -replace '\s*#.*','' -replace '(?<File_Regex>[\S]+)\s+(?<Icon_String>\S)','${File_Regex}=${Icon_String}') | ?{$_ -ne ""} | Join-string -Separator ':'
```

this script in powershell profile is usefull for fetching icons from icons file, lf using powershell.
