### ISSUE TITLE
Wiki lacks binary installation instructions

### ISSUE THREAD

**Issue by kingliamb** [gokcehan/lf#295]
On the tutorial page for new users (https://github.com/gokcehan/lf/wiki/Tutorial), I noticed there weren't any installation instructions, just download instructions. Maybe add those, broken down by operating system?
I'm a pretty new user to the Linux command line and didn't even know how to extract a tarball a bit ago. With some research, I figured out how to get the lf tarball extracted and squared away in my OS, but if the wiki page had instructions on how to do that, that would be really helpful. Assuming the tarball was downloaded to the current working directory, here's what I did.

`$ tar zvxf lf-linux-amd64.tar.gz` or whatever tarball was downloaded.
`$ sudo chmod a+x lf` To be honest, I don't know if the `chmod` command is necessary in combo with the `install` command, but I did it anyway.
`$ sudo install ./lf /usr/local/bin` I suppose the file could also be installed to `/usr/bin`.

I'm running amd64 with Ubuntu 16.04 LTS.
Thank you for considering adding installation instructions to the wiki!

**Comment by shabahengam** [comment]
yes wiki can be more organized but i think lf is not an application for Linux newbies so when someone gonna try lf she/he knows how to use that.
unfortunately my english is not very good to write wiki articles and make it more accurate.
> sudo chmod a+x lf

you don't need `chmod a+x` because lf permission(in the tar file) is set to 755.
![2020-02-08_20-15](https://user-images.githubusercontent.com/53096747/74089112-10391800-4ab3-11ea-9e6f-7d0ee35bfc9d.png)
> sudo install ./lf /usr/local/bin I suppose the file could also be installed to /usr/bin

please don't do this if you don't know what you are doing.just create a `bin` folder in your home directory and copy lf in there and then add `~/bin` in your `$PATH`.something like `export PATH=$PATH:~/bin`

**Comment by gokcehan** [comment]
@kingliamb There are instructions for installation in the tutorials wiki. The `curl` command example in the page is piped to `tar` to extract the downloaded file to an appropriate directory in path variable. What else can we add there?

**Comment by kingliamb** [comment]
I didn't see this earlier. Maybe it wasn't there or maybe I just missed it.
