### ISSUE TITLE
push single quotes

### ISSUE THREAD

**Issue by lucas-mior** [gokcehan/lf#317]
I want to jump back to last directory (`mark-load '`) as part of another command, but it doesn't work.

I've tried `lf -remote "send $id push ''"` (both escaping and not escaping single quotes)
and `lf -remote "send $id mark-load '"`
but neither of those work.

**Comment by gokcehan** [comment]
@lucas-mior Your first example `lf -remote "send $id push ''"` is working on my machine. Do you change directory beforehand? What is the error you are having? Can you come up with a minimalist error config example?

**Comment by lucas-mior** [comment]
I'll explain what I'm trying to do.

I want a command that copies or moves my selection (or load) into my last visited directory.
`lf -remote "send $id push ''"` indeed works when I use $ instead of %.

**But the problem is:**
If I use lf's built-in `paste` command, lf "forgets" what was in `'` mark and throws the following error:
`mark-load: no suck mark` (apparently lf forgets last dir when I yank or cut files)
If I use `mv ./ $fx` the shell will not cd into last directory so it will try to move to the same directory I'm already in.

And a minor problem that happens is that I would like to also select the file I've just pasted in,
and as I've noticed such behavior is only possible with % commands, like a command I implemented that moves or copies a file into a directory, changes directory to the same directory and then selects the moved file.

**Comment by doronbehar** [comment]
> I want a command that copies or moves my selection (or load) into my last visited directory, and therefore, I make use of markload ' so I can cd into last directory.
lf -remote "send $id push ''" indeed works when I use $ instead of %.

I imagine that you want to see the directory you are moving the files _from_, before actually doing so. This is an anti-pattern. If you are trying to achieve a somewhat compensating UX for Lf's lack of tabs or panes (as opposed to [Ranger](https://github.com/ranger/ranger)), you should visit:

https://github.com/gokcehan/lf#non-features & https://github.com/gokcehan/lf/wiki/Tutorial#multiple-terminals-or-multiplexers

> And a minor problem that happens is that I would like to also select the file I've just pasted in,
and as I've noticed such behavior is only possible with % commands, like a command I implemented that moves or copies a file into a directory, changes directory to the same directory and then selects the moved file.

See https://github.com/gokcehan/lf/issues/308

> If I use lf's built-in paste command, lf "forgets" what was in ' mark and throws the following error:
mark-load: no suck mark (apparently lf forgets last dir when I yank or cut files)
If I use mv $fx ./ the shell will not cd into last directory so it will try to move to the same directory I'm already in.

An actual code snippet where you'd point us to "This line doesn't work" would be helpful.
