### ISSUE TITLE
Can't escape tilde (~) in builtin commands arguments

### ISSUE THREAD

**Issue by ivanp7** [gokcehan/lf#349]
Tilde character are always getting expanded into $HOME when trying to pass arguments to builtin commands.
To reproduce, create a directory with '~' in the name, and then :cd to it (or :select).
Expected behavior: do not expand tilde when it is not in the beginning of a string.

**Comment by gotroyb127** [comment]
I have also had the same issue before. I ended up renaming every folder that contained '~'. That worked.
Today, I used grep to locate the files containing `~` and filtered them so I got the lines containing something like 
````Go
Astring = strings.Replace(Astring, "~", gUser.HomeDir, -1)
````
The problem that this creates is the problem you mentioned. By looking at [https://golang.org/pkg/strings/#Index](url), it seems that replacing those lines with 
````Go
if strings.Index(s, "~") == 0 {
	s = strings.Replace(s, "~", gUser.HomeDir, 1)
}
````
solved the problem. I tested this replacement and it worked though didn't like is that it doesn't feel very elegant. Instead, I would recommend defining a new function: (maybe the name isn't good enough)
````Go
func ReplaceFirst (s, t1, t2 string) string {
	if strings.Index(s, t1) == 0 {
		return strings.Replace(s, t1, t2, 1)
	}
}
````
(or similarly)
````Go
func ReplaceTilde (s string) string {
	if strings.Index(s, "~") == 0 {
		return strings.Replace(s, "~", gUser.HomeDir, 1)
	}
}
````
I would have done that if i knew where to put its decleration since I don't know much about Go (the function should be called from a few source files).

P.S. It seems to me that fixing this would take almost no time to gockehan. There are a few bugs I have encountered and I am trying to help fixing them since lf has been a my main file browser (I would like to thank you for lf, by the way). Also they doesn't seem to difficult to detect in comparison with some feature requests, though fixing them can make a noticeable difference.

**Comment by gokcehan** [comment]
@ivanp7 Thanks for reporting this.

@gotroyb127 Thanks for working this out. Your patch seems ok. I think you can put the helper function somewhere in `misc.go`. I would have probably use something like `strings.HasPrefix` instead of `strings.Index` so it would not search the whole string if it does not have `~`. Don't you also need a return at the end of the function in case the string does not start with `~`. Anyway, it would really help if you can send it as a PR. Even the simplest things take some time and I can't even catch up with issue activity these days.
