### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by tSU-RooT** [gokcehan/lf#35]
Could you use [go-runewidth](https://github.com/mattn/go-runewidth) instead of golang.org/x/text/width ?
It is already used in termbox-go.
In addition, go-runewidth looks to provide better support in some cases.

Screen Captures
commit: 880615ddd0bcde416e03362298c683866058f306
![bad-case01](https://cloud.githubusercontent.com/assets/1822861/19644274/ce0ae61c-9a29-11e6-87f4-de4d0c5fd90f.png)

using go-runewidth
![good-case01](https://cloud.githubusercontent.com/assets/1822861/19644292/e222b274-9a29-11e6-94a3-f46e03ad3a33.png)

patch is here:

``` diff
diff --git a/ui.go b/ui.go
index 32d5e1e..7609437 100644
--- a/ui.go
+++ b/ui.go
@@ -17,6 +17,7 @@ import (
    "unicode"
    "unicode/utf8"

+   "github.com/mattn/go-runewidth"
    "github.com/nsf/termbox-go"
 )

@@ -203,7 +204,7 @@ func (win *Win) print(x, y int, fg, bg termbox.Attribute, s string) {
        if r == '\t' {
            x += gOpts.tabstop - (x-off)%gOpts.tabstop
        } else {
-           x += runeWidth(r)
+           x += runewidth.RuneWidth(r)
        }
    }
 }
@@ -272,11 +273,13 @@ func (win *Win) printd(dir *Dir, marks map[string]bool) {
            s = append(s, r)
        }

-       w := runeSliceWidth(s)
-       if w > win.w-2 {
-           s = runeSliceWidthRange(s, 0, win.w-2)
-       } else {
-           s = append(s, make([]rune, win.w-2-w)...)
+       if runewidth.StringWidth(string(s)) > win.w-2 {
+           for runewidth.StringWidth(string(s)) > win.w-2 {
+               s = s[:len(s)-1]
+           }
+       }
+       if runewidth.StringWidth(string(s)) < win.w-2 {
+           s = append(s, make([]rune, win.w-2-runewidth.StringWidth(string(s)))...)
        }

        switch gOpts.showinfo {

```

**Comment by gokcehan** [comment]
@tSU-RooT I guess we can change that. I realized though go-runewidth returns 0 for space chars. This is seen on your screenshots where the highlight doesn't span the whole column in the second example. I'm not sure this is desirable. Maybe we can use a logic similar to the one used in termbox as such:

    if w == 0 || w == 2 && runewidth.IsAmbiguousWidth(back.Ch) {
        w = 1
    }

I need to do some testing for this. Can you copy the filenames in your screenshots here?

**Comment by KenjiTakahashi** [comment]
Yeah, it will not look good this way, especially in the middle column. I'll have a look at the other lib later myself, I'm curious about this :-).

**Comment by tSU-RooT** [comment]
@gokcehan
Sure :) , Filenames in my screenshots are
```
aaa∞bc
aa∞bc
a∞bc
```
'∞' s unicode point is 0x221E

The reason why I chose this character in test case is 
I found this in my video directory when I using lf in that.

In other case, '…'(0x2026) is too.

**Comment by gokcehan** [comment]
@tSU-RooT I have tested both of those chars on gnome-terminal (libvte) and xterm on my machine and they both display as narrow characters so they don't collide with others. Github's monospace font (as is in your comment) on Firefox and Chrome also seems to display these as narrow characters. I suspect these chars are those that have ambiguous width so they can be displayed as narrow or wide (http://unicode.org/reports/tr11/). I remember there were some functions to get the wide or narrow variant of a character which may be relevant to solve this issue. go-runewidth seems to work on your setup but if it's working accidentally that's not very good because it means it might fail for others. I guess I shall better finish reading the unicode article before doing anything. Ideas are welcomed in the meantime :)

**Comment by gokcehan** [comment]
@tSU-RooT I tried to read the unicode report but I couldn't really make much sense out of it. Anyway, I have replaced the package now. Closing this issue now.
