### ISSUE TITLE
Custom file info formatting

### ISSUE THREAD

**Issue by hjerabek** [gokcehan/lf#354]
Is there a way to fully customize the formatting of file infos?

`set info` seems to be limited to core file properties, like time and size, and does not allow to modify their display format...

**Comment by hjerabek** [comment]
Looking at the respective parts of the [code](https://github.com/gokcehan/lf/blob/933b49d09563cae768fc03eb5aa30141850f012f/ui.go#L195), it seems that the info properties are limited and use constant formatting.

To the projects developer(s): I assume the given property limitations are implemented for performance reasons. However, it would be nice to be able to change the time format from constant `"Jan _2 15:04"` to the existing `gOpts.timefmt` or a new `gOpts.infotimefmt` option. The impact on the UI's performance should be negligible.

**Comment by gokcehan** [comment]
@hjerabek I think I had added `timefmt` option because someone asked for it. We don't have an option for info time format because noone implemented it yet. Unfortunately I don't have much time to work on lf these days. I would be ok to accept a PR related to this. This should not be difficult to implement if anyone is interested in working on this.

**Comment by gokcehan** [comment]
This was added in #751 a while ago which will likely be available in the next release (e.g. r27).
