### ISSUE TITLE
inspect async commands

### ISSUE THREAD

**Issue by mohkale** [gokcehan/lf#359]
This might be related to issue #61 

At the moment `lf` doesn't seem to offer any way to inspect async commands, including:
- how many are running?
- the output from them?
- whether they've finished?

the second point I can live without but not knowing when an async command finishes makes me avoid using them altogether. I'd like to suggest `lf` adds a view where you can inspect running async commands, maybe their output, maybe send `kill` signals to them, jump to the directory from which you spawned those commands etc..

For eg, a situation where this would come in useful is when you're zipping directories. You mark a few directories, then run an async command that zips them, then you leave and goto some other directories but you keep jumping back to that zipping directory because you want to know when its finished.

**Comment by gokcehan** [comment]
@mohkale Unfortunately this is not possible the way async commands are implemented. They are left to the OS after the start so they can continue running even if lf quits. Since lf doesn't own these processes, we can't have any information about these commands. You may try to send some message to the lf client at the end of your command.

**Comment by mohkale** [comment]
I see, that's a shame. I guess I'll just have to get used to dedicating my current pane to a synchronous process and moving between them instead.
