### ISSUE TITLE
some xterm escape sequences do not work

### ISSUE THREAD

**Issue by lucas-mior** [gokcehan/lf#366]
I'm starting to work on image previews using URxvt.
In URxvt with pixbuf support, running a regular shell, the command
```
printf "\033]20;/path/to/image.jpg;100x100+100+50:op=keep-aspect\007"
```
will correctly display the image as required.
Inside ```lf```, it will work if called from the command line. 
As a preview script, however, just prints
```
]20;/path/to/image.jpg;100x100+100+50:op=keep-aspect
```
Although some other escape sequences from xterm/urxvt work, this one does not.

How I implemented:
lfrc:
```
set preview
set previewer pix.sh
```
pix.sh:
```
#!/bin/bash
IMG=$(realpath "$1")      #this escape sequence only works with real paths
printf "\033]20;${IMG};100x100+100+50:op=keep-aspect\007"

**Comment by gokcehan** [comment]
@lucas-mior Which escape sequences work?

**Comment by lucas-mior** [comment]
I'm sorry. Actually, I don't know of any escape sequence that work
*when called from the preview script.* I was thinking about the ones that work inside a command, or called from lf's command line. (Including the one I want to make work).

I understand if you don't feel like digging into it.
Could you just give me a hint of why is it that the same escape sequence will work as a regular lf command, but not as a preview command/script, so I can look into it myself?
Thanks.

**Comment by gokcehan** [comment]
@lucas-mior The reason is that we need to manage the terminal ourselves to draw the ui using termbox library. Termbox api does not print anything on the screen but only allows changing characters at specified positions. So we simply read the file and put the characters at relevant positions in the preview pane.

It works in commands because termbox is paused with `$` and `!` commands and terminal management is left to the command itself.

The exception is the color codes, which are technically escape codes as well, but they are standard. We interpret colors by converting these escape codes to their corresponding attributes in termbox api.

**Comment by lucas-mior** [comment]
Thanks for the information.

**Comment by gokcehan** [comment]
@lucas-mior fyi, @Provessor has been working on image previews in his fork [here](https://gitlab.com/Provessor/lfp) and I think he may like some help and/or feedback.

**Comment by Barbaross93** [comment]
I was sort of able to get URxvt previews to work, but unfortunately it is as @gokcehan says; using `$` or `!` are the only ways to get the images to display and this creates the problem of flickering the entire `lf` program when traversing through images.  Another issue I ran into is that lf caches the results of the preview commands. It didn't seem possible to always rerun the command unless I manually `reload` every time I go back to view a previous image.

If I understand you right @gokcehan, `lf` would need to be able to interpret URxvt image escape sequences since the termbox api doesn't do any of the interpretation?
