### ISSUE TITLE
How to prompt from a shortcut?

### ISSUE THREAD

**Issue by alexherbo2** [gokcehan/lf#369]

**Comment by mohkale** [comment]
if you define a command using the `%` shell code then it runs from within the `lf` interface and you can read any input from the user there.

eg.

```
cmd mkcd %{{
    printf "directory: "
    read -e dir
    mkdir -p "$dir"
    lf -remote "send $id cd \"$dir\""
}}
map ,n mkcd
```

I haven't managed to get completion working reasonably but if it's just reading something from the user then this works.

**Comment by gokcehan** [comment]
@alexherbo2 You can also define a custom command that takes an argument and use a mapping to put the command name to the command line. See `rename` examples in the documentation.

**Comment by alexherbo2** [comment]
@gokcehan File selection does not seem to work.

### Configuration

`~/.config/lf/lfrc`

``` lf

# Commands ─────────────────────────────────────────────────────────────────────

cmd create-new-file ${{
  file=$1
  if test -e "$file"; then
    lf -remote "send $id echo File exists: $file"
    exit 1
  fi
  directory=$(dirname "$file")
  mkdir -p "$directory"
  touch "$file"
  lf -remote "send $id select $file"
}}

cmd create-new-directory ${{
  directory=$1
  if test -e "$directory"; then
    lf -remote "send $id echo File exists: $directory"
    exit 1
  fi
  mkdir -p "$directory"
  lf -remote "send $id select $directory"
}}

# Mappings ─────────────────────────────────────────────────────────────────────

map <f-2> push :create-new-file<space>
map <f-3> push :create-new-directory<space>
```

**Comment by mohkale** [comment]
Aren't you asking the same thing as #370? lf doesn't automatically load the current directory when a new files been written to it in a `cmd`. You need to actively call `load` before `select` or else lf will assume your trying to select a non-existent file and then ignore your request.

I just realized the wiki doesn't have a `touch` file or `mkdir` command in the tips section. I'll add mine for now.

```
cmd mkdir %{{
    printf "directory: "
    read -e dir
    mkdir -p "$dir"
    lf -remote "send $id load"$'\n'"send $id select \"$dir\""
}}
```

**Comment by alexherbo2** [comment]
It could be nice to support the following syntaxes:

``` lf
cmd create-new-file ${{
  …
  lf -remote "
    send $id load
    send $id select $file
  "
}}

cmd create-new-directory ${{
  …
  lf -remote "
    send $id {{
      load
      select $directory
    }}
  "
}}
```

**Comment by mohkale** [comment]
That would be nice :smile:.

But doesn't it depend on the underlying shell? Are you suggesting we allow the parser to transform that into shell agnostic input?

**Comment by alexherbo2** [comment]
It could be done like that:

``` lf
cmd create-new-file ${{
  …
  lf -remote '
    send %arg{1} :{{
      load
      select %arg{2}
    }}
  ' -- "$id" "$directory"
}}
```

**Comment by gokcehan** [comment]
@alexherbo2 @mohkale If I'm not mistaken, you should be able to put multiple commands in a single line as such:

    lf -remote "send $id :load; select $file"

Does this not work?

**Comment by alexherbo2** [comment]
Nope

**Comment by gokcehan** [comment]
@alexherbo2 It seems that the syntax is supported but load does not work in your examples. I'm reopening #370 for further inspection. Meanwhile, you can use `%` commands for renaming as described in #165 .

**Comment by alexherbo2** [comment]
@gokcehan What do you think about the syntax suggestions?

**Comment by gokcehan** [comment]
@alexherbo2 Syntax already works. Try this:

    map a %{{
        lf -remote "send $id :down; down"
    }}

or this:

    map a %{{
        lf -remote "
            send $id down
            send $id down
        "
    }}

**Comment by alexherbo2** [comment]
And

``` lf
cmd double-down ${{
  lf -remote "
    send $id :{{
      down
      down
    }}
  "
}}
```

?

**Comment by gokcehan** [comment]
@alexherbo2 That doesn't work since the parser is confused by the first closing `}}` inside the string. Also, server reads remote commands line by line. I can't think of any way to make it work in an easy way.

**Comment by alexherbo2** [comment]
Perfect forwarding with `-arguments` and `-named-arguments` is also important.

**Comment by gokcehan** [comment]
@alexherbo2 I don't know what mean by perfect forwarding but I don't think it is related to prompts. Closing this issue.

**Comment by muellerto** [comment]
I don't want to open a new thread, I have a related problem on Windows. I took the code from above:
```
cmd create-new-directory ${{
  directory=$1
  if test -e "$directory"; then
    lf -remote "send $id echo File exists: $directory"
    exit 1
  fi
  mkdir -p "$directory"
  lf -remote "send $id select $directory"
}}
map <f-3> push :create-new-directory<space>
```
Looks good, I understand all that. Then I modified it to let it run on a Windows machine, variables in `%%` and so on:
```
cmd create-new-directory ${{
  set directory=%1%
  mkdir -p "%directory%"                     (only these two lines for the test)
}}
map <f-3> push :create-new-directory<space>
```
But it still does nothing. I have a mkdir.exe and it works, when I type `:mkdir hello` it creates indeed a hello-directory as expected. So I assume my `%1%` is always empty and `mkdir -p` does just nothing, especially it doesn't say something. When I try ...
```
cmd create-new-directory !{{              mind the !
  echo %1%
}}
```
... I would expect that I get my argument echoed. But I don't see anything. I also tried `%1` instead of `%1%`, doesn't help.

**Comment by mohkale** [comment]
@muellerto whats the value of your `$shell`?

**Comment by muellerto** [comment]
`cmd`, of course.

**Comment by gokcehan** [comment]
@muellerto If I'm not mistaken, positional parameters are referred as `%1` in cmd. Also, I'm not sure if there is `-p` for `mkdir`. I want to prepare example config files for cmd and powershell but I don't know when I can have time for that.

**Comment by muellerto** [comment]
@gokcehan Idescribed the problem precisely.

I said "I have a mkdir.exe", this means I do not use the `mkdir` or `md` builtin commands of cmd.exe. My mkdir.exe is a msys-port of the Unix-mkdir, of course it has a -p option, and I said it works correctly, it's not part of the problem at all.

I also said I checked them both, `%1` and `%1%`, don't know how you [1] want it. I did this twice. None of them works as expected. The values of these symbols are always empty. Even `%0` seems to be empty, by all means I can't echo them all. I also cannot put them into a file using output redirection which is legal in a common batch file

`echo  %0  %1  >  myfile`

The output file will never be created.

`%f` and its siblings are different, I can see them in the environment of the child batch.

I'm at a loss with that at the moment. I have several ideas for commands using an argument but I couldn't implement one of them as long as I can't refer to the given input values. And mkdir (what nobody needs, I know) is only one of them.

--------------
[1] More and more it gets clearer: you create a temporary batch file from the body between `{{` and `}}` and let it be processed by a shell. In this case the numbered parameters must be real parameters [2] of the batch. But this is intransparent for the user and not good documented, I must guess all that.

[2] A batch file can have parameters, the parameters can be referred as `%1`, `%2` and so on. The values for these parameters must be specified on the command line when the batch file is invoked:

`mybatch.bat  value1  value2  value3`

You have no other way to get them into the environment of cmd.exe which processes the batch. Especially you cannot use a function like `setenv()` for them as you can for `%f%` and siblings.

**Comment by muellerto** [comment]
Update: I now compiled a very simple test program as follows to get rid of all possible complicacies with builtin commands like `echo` and so on:

```
#include <iostream>
int main (int argc, char* argv[])
{
	for (int i = 0; i < argc; i++)
		std::cout << argv[i] << std::endl;
}
```

I start this program in a user defined command like this just to see what I really get:

```
cmd Test !{{
        test.exe %0 %1 %2 %3 %4 %5
}}
```

This user defined command is invoked as follows:

`map <f-7>       push :Test<space>`

When I now press F7 an input line asks for a Test input. I give him a word. Then it flickers a bit and then I see only the request to press any key, not more. Expected is that I see

1. the name of my test program including a path
2. the name of the batch job (because I specified %0 as parameter
3. the value of the first parameter

It seems that not only the handling of the parameter doesn't work, I'm not sure whether the batch job is indeed started.

More interesting: when I change the command to a one liner without `{{` and `}}` ...

`cmd Test !test.exe %0 %1 %2 %3 %4 %5`

... the result is very different. My program is called now and says something:

```
/e/test/gcc/test                    this is the msys-notation for e:\test\gcc\test.exe
%0                                  as if I specified "%0" in the command definition
%1
%2
%3
%4
%5
hello                               this was my input
press any key . . .
```

That's much better, but causes still many new questions. When I specify my command now (against all the examples) without any `%` just as ...

`cmd Test !test.exe`

... it shows implicitly everything I want:

```
/e/test/gcc/test
hello
press any key . . .
```

But that's not good because of the implicit parameter value for my program.

At the end I added again `{{` and `}}` but now on one line:

`cmd Test !{{test.exe}}`

This shows the same result, so I guess there's a problem with multiline command definitions on Windows, perhaps related to the different line endings or so. (I could now still produce a lfrc file having Unix line endings ...)

**Comment by mohkale** [comment]
@muellerto if you believe line endings are the issue, have you tried running your config through `dos2unix`?

**Comment by muellerto** [comment]
Simple line endings in lfrc are NOT part of the issue. I checked this now. It's more complicated. Perhaps line endings in the batch job are wrong, I don't know. I even don't know if there is indeed a real temporary batch file or if all is in memory.

The issue has two general aspects:
1. multiline command definitions and/or execution on Windows
2. numbered parameter transfer to external Windows programs

Windows 10 1909, r14

**Comment by gokcehan** [comment]
@muellerto Sorry, it seems that I did not read the previous reply carefully. I'm not good at scripting in windows either. `cmd` is particularly difficult since it has strange quoting rules. We have been using it as default since it is still referred as the windows default. You might have a better luck with `set shell powershell` if you intend to define custom commands, though it has its own problems. Otherwise, you can just stick to using `$` commands directly instead of defining custom commands for the while.

Thanks for identifying the issues. I will now create a separate issue for these as this issue is not very relevant.

I'm aware our documentation is not sufficient for some things, and we have an open issue about it. I'm hoping to make a new release in the upcoming days, and then focus on doc and wiki updates for the next release.

Shell commands are implemented by passing them them as string arguments in a similar fashion as below:

    cmd /c "echo %1 %2 %3" one two three

The difference is that we pass them directly as strings in Go code [here](https://github.com/gokcehan/lf/blob/master/os_windows.go#L83).

**Comment by gokcehan** [comment]
@muellerto If you decide to give `powershell` a try, don't forget to check #186 to see how file variables are to be used currently.

**Comment by muellerto** [comment]
I see no difference in handling the numbered parameters when I use powershell, except that the error messages are red and much longer. Powershell expects these parameters exactly like cmd.

This is what powershell says when I call my test program as `test.exe %1 %2 %3` and the input was `hello`.
```
/e/test/gcc/test
%1
%2
%3
hello : Die Benennung "hello" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie
die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:3 Zeichen:2
+  hello
+  ~~~~~
    + CategoryInfo          : ObjectNotFound: (hello:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

The german error message says that `hello` is not a {Cmdlet | function | script | executable}. This tells us that the value I typed in after the prompt is handled here as a command to be executed instead of being a parameter. It's the same message you get when you type `hello` on the powershell command line.

When I define the command as `test.exe $1 $2 $3` it looks like
```
/e/test/gcc/test
hello : Die Benennung "hello" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie
die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:3 Zeichen:2
+  hello
+  ~~~~~
    + CategoryInfo          : ObjectNotFound: (hello:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
This means $-variables have no value at all, they got filtered out completely. I guess the powershell is not the solution (it's just one helpless try from Microsoft to get some scripting capabilities ...)

I see three workarounds for the Windows problem.

1. Fill up real named environment variables with numbers like `%p1%`, `%p2%`, ... instead of `%1`, `%2` ... The user defined commands could use them in the same way as `%f%` and siblings. This is not nice but will work easily.

2. Put the complete multiline body of a user defined command into a real temporary batch file and write it on disk when the command gets invoked. Then call cmd.exe with this batch file as parameter: `cmd.exe /c temp.bat value1 value2 value3`. The values must only be quoted when they contain spaces. This is the most robust solution, allowing full batch file capabilities, internal input and output redirection, piping and more.

3. Expand the parameters yourself. This was my first idea. Don't let any shell expand them. This means: when a user defined command is invoked you must analyze the body of its definition and replace yourself each numbered parameter by a value. This would have the great advantage that you could also under Windows have commands with $-variables in the body.

**Comment by gokcehan** [comment]
@muellerto Positional parameters are stored in `$Args` array in `powershell`. It seems to work with single line commands, but multilines are still a problem. It is likely that windows does not like multiline command line parameters whether it is `cmd` or `powershell`.

I don't think (1) and (3) would help with the multiline problem. You could do (2) manually yourself as a workaround for now (i.e. create a script named `lf-mkdir.bat` or `lf-mkdir.ps1` somewhere in path and call it in a single line command from within `lf`).

If you have further discussion, please use the other issue.
