### ISSUE TITLE
tagging files

### ISSUE THREAD

**Issue by anjandev** [gokcehan/lf#400]
Ranger has this feature where you can tag files by pressing t on your keyboard:

![screenshot](https://user-images.githubusercontent.com/8602360/86527321-745adf00-be8d-11ea-961e-a6fc3388379c.png)

For example, here I have "tagged" the `bin` folder and it's given a red asterisk. If you close and relaunch ranger, the `bin` folder will still have a red asterisk next to it.

I often use this feature for when I am watching a series and I want to keep track of the episodes I have watched. This is also useful for when I am reviewing for an exam and I want to keep track of notes I have reviewed.

I couldnt find this feature in the manpages. Can this tagging feature be added to lf?

**Comment by gokcehan** [comment]
@anjandev Similar suggestion in #83 though this one may require persistence across sessions.

**Comment by igorhub** [comment]
@gokcehan Why not push persistence to the user’s end? All that needs to be done on lf’s part is to send the contents of the directory to the user-defined decorator command, and then receive the file list in whatever form the user desires. That would solve (or at least shift the burden from you) both this and #83, as well as the whole layer of potential enhancements.

Am I missing something?

**Comment by gokcehan** [comment]
@igorhub I'm not sure it is wise to call a script every time a directory is displayed.

**Comment by igorhub** [comment]
@gokcehan I meant to say the script would be called when directory's loaded, not displayed.
Running a small script upon entering or previewing directory should not add much of an overhead. In case of previewing there’s already a script in action, and it hurts nobody.

**Comment by gokcehan** [comment]
@igorhub Aren't you the one complaining about loading screens? 😄 

Anyway this may worth a try, though I'm not sure about some of the details like color.

**Comment by igorhub** [comment]
Consistency is the hobgoblin of little minds!

**Comment by igorhub** [comment]
More seriously, I think the value is worth the price, especially since it’s entirely optional.

Even though I came here for smooth visuals (which, as I’ve discovered, are not quite there yet), I now see lf’s extension facilities as its most attractive feature.

Of all the file managers I’ve tried so far, lf gets the closest to my ideal of interactive software: minimalist core you can rely on, and well-designed extension system to help you fit it seamlessly into your personal workflow.

Directory decorators, if all goes well, will move it even further in that direction. Most of them, I would imagine, are rather niche. Dragging them into the core wouldn’t do the project much good, and neither would the arguments about what is essential and what is not.

**Comment by joelim-work** [comment]
This is fixed in #791, turns out this issue wasn't linked properly in the PR.

**Comment by sdsaati** [comment]
Ranger has tabs, and it's a pretty good feature—I use it daily. Why? Because it's easy! That's reason enough without installing other applications, running multiple instances (server/clients), or dealing with a lot of extra stuff. In Ranger, you just press Alt+2 and that's it. Then Alt+1 takes you back to tab 1. If you know of anything that can be this simple, then I’m with you.
