### ISSUE TITLE
Fix: smylink creation on zsh.

### ISSUE THREAD

**Issue by wizardofsource** [gokcehan/lf#436]
Good day to you!

I find lf very useful. Not sure how  one contributes to your wiki, but the Tip for creating smylinks wasn't working for me. I changed the script a little bit here it is:

```
cmd Link %{{
        for file in $(lf -remote 'load'); do 
	    if [ ! -n "${mode+1}" ]; then
	        mode="$file"
		continue
	    fi
	files+=("$file")
        done
	# lf -remote 'load' | while read file; do
	# 	if [ ! -n "${mode+1}" ]; then
	# 		mode="$file"
	# 		continue
	# 	fi
	# 	files+=("$file")
	# done
	#if [ "${#files[@]}" -le 1 ]; then
	if [ "${#files[@]}" -lt 1 ]; then
		lf -remote "send $id echo no files to link"
		exit 0
	fi
	# symbolically  copy mode is indicating a soft link
	if [[ "$mode" == copy ]]; then
		ln -sr $files -t .
	# while a move mode is indicating a hard link
	elif [[ "$mode" == move ]]; then
		ln $files -t .
	fi
}}
map P :Link
```

The old parts are commented out. Oh and I use Zsh, not sure if it's the reason why the old one didn't work though.
Cheers!

**Comment by gokcehan** [comment]
@wizardofsource Good day to you as well.

Wiki should be editable by everyone. Since you already have a github account, you should be able to edit it with no problem.

I haven't seen this tip before. If the issue is about the differences in zsh, I think it would be better if you could also try the new version in `bash` or `sh` to make sure it still works. Alternatively, you could also add this as a separate tip specific for `zsh` if differences are significant.

Cheers.

**Comment by wizardofsource** [comment]
Hello.

I have tested it on sh and bash and it looks like it's working there too. I will update the wiki.

Cheers.

**Comment by BachoSeven** [comment]
@wizardofsource This can probably be closed, since the entry has been added to the wiki(?)

**Comment by wizardofsource** [comment]
Ofc, sorry. :}
