### ISSUE TITLE
question: error message when exiting out of fzf

### ISSUE THREAD

**Issue by n0ibe** [gokcehan/lf#441]
I'm getting some weird error message when calling fzf from an empty directory.

The steps to reproduce are the following;
1. go to an empty directory;
2. call fzf via the `$` shell, for example `$ ls | fzf` (since the directory is empty no results will be shown, that's ok);
3. quit out of fzf by pressing escape;

I now get an error message at the bottom that says `running shell: exit status 130`. For some reason I don't get this error if I'm doing this from a directory that's not empty, and I don't remember ever experiencing this behaviour before upgrading to version 15.

![2020-08-08@09:45:25](https://user-images.githubusercontent.com/59321248/89705348-de6b1600-d95c-11ea-849a-1c9f225887a9.png)

**Comment by gokcehan** [comment]
@n0ibe It seems that `fzf` returns 130 when you don't select anything. We have a mechanism to show errors when shell commands return non-zero codes, though this is overridden by a file info in non-empty directories. We should not override these messages.

I have checked versions as old as r8 and it seems that this was always the case.

**Comment by gokcehan** [comment]
@n0ibe Now I have changed the behavior to not overwrite shell errors, so it should show `running shell: exit status 130` regardless of you are in an empty directory or not.

**Comment by n0ibe** [comment]
Will there be a way to also silence these errors if we don't care about non zero exit codes?

**Comment by gokcehan** [comment]
@n0ibe It's a little tricky because we simply report the error returned by [exec.Run](https://golang.org/pkg/os/exec/#Cmd.Run) and it considers non-zero exit codes as errors. Errors are useful in general so we wouldn't want to disable errors altogether. For example if you `set shell zsh` and `zsh` is not installed, it will also show you an error like executable file not found.

Why do you want to silence these errors? Non-zero exit codes are the common convention to show an error. You could ask `fzf` devs to return `0` when a file is not selected, but this is probably not a good idea either. What does your command look like? In your original post you listed `ls | fzf` which doesn't make much sense on its own. If you pipe this command further to another command or use it as a subcommand, then `fzf` error won't be returned anyway. You could also append `|| true` to your command if you don't care about the return code (e.g. `ls | fzf || true` in your example).

**Comment by n0ibe** [comment]
> What does your command look like?

```
cmd fuzzy_edit ${{
  clear
  filename="$(fzf --height=80%)" && $EDITOR ~/"$filename"
}}
```
it lists all the files in my home directory, and I can fuzzy find the file I want to edit and open it in `$EDITOR`. Using `|| true` isn't a viable solution since I'm using `&&` to decide wheter or not I should call the editor, i.e. I need the command to fail if I exit without selecting anything.

> Why do you want to silence these errors?

Because if I decide to exit without selecting a file I don't want a bright red error to tell me what I just did. 

If I `set shell zsh` and I don't have `zsh` installed then I should absolutely be warned with an error message, but sometimes (especially when resulting from custom defined functions) error messages could be redundant.

**Comment by gokcehan** [comment]
@n0ibe How about this?

    cmd fuzzy_edit ${{
      clear
      filename="$(fzf --height=80%)" && $EDITOR ~/"$filename" || true
    }}

**Comment by n0ibe** [comment]
@gokcehan Well now I feel dumb for putting the `|| true` in the wrong place 🤦 

Thanks ;)
