### ISSUE TITLE
lf hangs with `mimeopen --ask` in fish 

### ISSUE THREAD

**Issue by crivaronicolini** [gokcehan/lf#499]
Using `map O $mimeopen --ask $f` in fish prints the message from `mimeopen` to the console, but then it doesn't record any input, and I have to `ctrl-c` out of lf.
Works with bash tough. Any idea how can I fix it?

**Comment by gokcehan** [comment]
@crivaronicolini The use of non-POSIX shells for `shell` option is not well supported. I have now updated the documentation accordingly.

**Comment by gokcehan** [comment]
@crivaronicolini Sorry, I think you meant the other way, running a shell command inside `fish` with `set shell sh`. This should normally work but apparently not. I'm able to reproduce the issue myself. I suspect this might be related to our recent port from termbox to tcell. I'm labeling the issue as a bug.

To further elaborate on my previous comment, we rely on a POSIX shell command to implement "Press any key to continue" behavior so `set shell fish` would fail to execute waiting shell commands. Besides, our `fs` and `fx` variables are simple strings separated with newlines so I think they need to be converted to arrays to be used properly in `fish`.

**Comment by crivaronicolini** [comment]
Yes I have `set shell sh` in the config file. I was using r14 when I opened this issue, and updating to r17 did not change it, if that helps.

**Comment by gokcehan** [comment]
@crivaronicolini On my machine, this turned out to be a `fish` keybinding issue regardless of `lf` version. So calling `lfcd` by typing it manually in the terminal does not seem to trigger this bug. Can you confirm this is the case for you as well?

I don't remember this being the case but it is possible it was always like this. I'm not using `fish` myself so I haven't tested the script extensively. It is also possible `fish` might have changed something recently. In any case, I could not find an easy way to make the binding work without triggering this issue. We might need to get rid of the keybinding example in the comment.

**Comment by crivaronicolini** [comment]
Good catch, calling `lfcd` does not trigger it. I'll search the `fish` issues page for something similar, and I'll open an issue if I don't find anything. Thanks!

**Comment by crivaronicolini** [comment]
For anyone having this problem, I found  [this](https://github.com/fish-shell/fish-shell/issues/4772) issue in the fish repo, the workaround is to use `bind \eo 'stty sane; lfcd; commandline -f repaint'` in the fish config.

**Comment by gokcehan** [comment]
@crivaronicolini Thanks for looking into it. I have now changed the example in the `lfcd.fish` comment accordingly.

By the way, not sure if you realized, but I think there is a minor annoyance with this new version. If you launch the script using the keybinding and then quit and try launching it again using keybinding, it prints `^O` instead of launching. You need to skip the current line with an enter to be able to launch with the keybinding again for some reason.

**Comment by crivaronicolini** [comment]
Yes it is very annoying. Another way I found digging the fish issues is to leave the keybinding as it is, and when choosing the `mimeopen` option number pressing `^j` instead of enter. It doesn't print the option number but it sends the command anyway. I think that's better, the other way also stopped the syntax highlighting with that `^O` and it wasn't worth it.

**Comment by gokcehan** [comment]
@crivaronicolini I have taken a look at this again and I think the following works without an issue:

    bind \co 'set old_tty (stty -g); stty sane; lfcd; stty $old_tty; commandline -f repaint'

I have now updated the example as such until maybe someone comes up with a cleaner solution.
