### ISSUE TITLE
Show full path (including file name) on the first line

### ISSUE THREAD

**Issue by dumblob** [gokcehan/lf#50]
Currently if one wants to easily copy the full canonical path to the selected file, one has to copy the path from first line, then somehow show the full filename (often it's cut because of a too narrow column, so one needs to use e.g. some key binding running ls on the file) and then concatenate these two.

I'd like the selected file name being shown after the path on the first line to form a full canonical path to the selected file/dir as it's done in ranger.

**Comment by gokcehan** [comment]
You might still have issues if the path does not fit in a single line. Ranger for example compresses directory names when the path is too long. For your purpose, it sounds like you can utilize `$f` variable which will always hold the full path so you won't need to concatenate anything and it will be more reliable. You may also consider copying the name in the command itself with something like `map - $echo $f | xsel`.

**Comment by dumblob** [comment]
@gokcehan forgot to mention, that I love the compressing of the path for viewing - it's great for orientation (also because of it's high similarity to the work in shell directly where one sees the full path always). Because it always allows to clearly see the full path and with an easy trick (maximization or just widening of the terminal window) one gets the full path without running of any commands and any other hassle).

Could you please implement the ranger behavior?

**Comment by dumblob** [comment]
https://github.com/gokcehan/lf/issues/22 seems related as the screen reader can then read the whole path.

@tspivey, would you prefer the whole path with file name or rather having it configurable? And what about the path compression mentioned in the previous comments?

**Comment by gokcehan** [comment]
@dumblob The way I understand it, we never leave the cursor on the path, so I doubt the other issue is related to this one.

Adding the whole path should be an easy change but I didn't make that change because to me it feels like a redundant information. So I would rather make this configurable. I was thinking of adding a `ps1` or just `ps` option much like bash and others. Compression can be a part of this. But there are other more critical issues I would like to tackle on first so it may take some time. It's fine if anyone wants to work on this.

**Comment by gokcehan** [comment]
I had changed the default configuration a while ago to include the current filename since it is difficult to see the current file name with narrow columns. Now I have added `promptfmt` option to configure the prompt line. Old behavior can now be configured if desired. I used `%` for escaping since `\` needs to be doubled in between double quotes. Values are as follows:

    %u    username
    %h    hostname
    %w    working directory
    %f    current file name

Ansi colors are also supported. You can see the default value of this option as an example. Working directory is shortened when it is too long to fit to the prompt. Closing this issue now.
