### ISSUE TITLE
How to use file extensions within 'open' command?

### ISSUE THREAD

**Issue by cacud** [gokcehan/lf#503]
My bad, I can't figure out where do I have to list file extensions within 'open' command. Default lfrc clearly says that this is possible:

```
# This command is called when current file is not a directory. You may want to
# use either file extensions and/or mime types here. Below uses an editor for
# text files and a file opener for the rest.
```

My 'open' command looks like this:

```
cmd open ${{
    case $(file --mime-type $f -b) in
        text/*) $EDITOR $fx;;
        image/*) imv $fx;;
        audio/*) mpv $fx;;
        video/*) mpv $fx;;
        application/pdf) zathura $fx;;
        *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
    esac
}}
```

It works fine, but it won't allow to open AVCHD video files (they have .MTS name extension) because `file --mime-type $f -b` of such a file returns "application/octet-stream", which I think can also be type of some other binaries not for media player.
Please help me add a rule to open a file using its name extension.

**Comment by gokcehan** [comment]
@cacud Does this work?

```
cmd open ${{
    case $f in
        *.mts) mpv $fx;;
    esac
    case $(file --mime-type $f -b) in
        text/*) $EDITOR $fx;;
        image/*) imv $fx;;
        audio/*) mpv $fx;;
        video/*) mpv $fx;;
        application/pdf) zathura $fx;;
        *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
    esac
}}
```

**Comment by cacud** [comment]
@gokcehan It does! Though I have filename extension in capitals, so I wrote it that way in lfrc (otherwise won't work). Thank you!

**Comment by cacud** [comment]
Maybe add the same case to lfrc.example for clarity?

**Comment by gokcehan** [comment]
@cacud By the way, I think you may also need to `exit` in the commands of the first case statement, or otherwise it might still fall back to the second case:

```
cmd open ${{
    case $f in
        *.MTS) mpv $fx && exit 1;;
    esac
    case $(file --mime-type $f -b) in
        text/*) $EDITOR $fx;;
        image/*) imv $fx;;
        audio/*) mpv $fx;;
        video/*) mpv $fx;;
        application/pdf) zathura $fx;;
        *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
    esac
}}
```

I think I agree it is a good idea to keep such an example available somewhere because this is the second time someone asked for something like this, but I'm not sure the example config and man page is the proper place. This is a much more capable example but also more confusing for users not familiar with shell. In the end, we might get more questions about where to add a new file type definition. Maybe [tips](https://github.com/gokcehan/lf/wiki/Tips) wiki page might be better for this with proper explanations?
