### ISSUE TITLE
open function returns an error for no apparent reason

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#504]
This is my `open` function

```
cmd open ${{
  text_files=()
  image_files=()
  for f in $fx; do
    case $(file -b --mime-type $f) in
      text/*|inode/x-empty) text_files+=("$f");;
      image/*) image_files+=("$f");;
      video/*) open -n "$f";;
      *) open "$f" &>/dev/null;;
    esac
  done
  (( ${#image_files[@]} )) && open "${image_files[@]}"
  (( ${#text_files[@]} )) && $EDITOR "${text_files[@]}"
}}
```
instead of opening text files and images directly, I add them to an array (I have `set shell "bash"`), then call `$EDITOR` or `open` on the whole bunch.

However, after I select and open one or more images (but no text files), I get a

`running shell: exit status 1`

error, which I can't understand. The error goes away if I comment the last line. What's causing this?

**Comment by gokcehan** [comment]
@noib3 It doesn't show any errors in my machine. Can you check your log file to see if there is anything relevant? You can use a keybind as such:

```
map ` $less /tmp/lf.${USER}.${id}.log
```

If not, can you define this command in your shell along with some example values for `f` and `fx` and then run the command in shell to see more about the error?

**Comment by noib3** [comment]
The log file doesn't seem to be stored in `/tmp` on macOS. I also tried looking in `/var/tmp` and in `/private/tmp`, but it wasn't there either. Running the same command in the shell works perfectly fine, which is why I thought that error was very weird.

Also, if I change the last line from
```
(( ${#text_files[@]} )) && $EDITOR "${text_files[@]}"
```
to the logically equivalent
```
if (( ${#text_files[@]} )); then
  $EDITOR "${text_files[@]}"
fi
```
then no error is reported.

**Comment by gokcehan** [comment]
@noib3 I was told the log file is somewhere in `/var/folders` in MacOS, wherever your OS says temporary directory is.

Do you have `shellopts` set to anything in your config file? Also do you simply try to run the command in shell, or try to wrap it as `bash -c '...'`, which is literally what we basically do in `lf`. There might be something in your `~/.bashrc` not sourced when you run the command as non-interactive that might change the behavior.

Lastly, how do you check if you have an error or not? Any return code other than `0` is reported as an error in `lf`. Do you try to check your return value in shell after you run the command (i.e. `echo $?`).

**Comment by noib3** [comment]
I found the log file (it was in `$TMPDIR`), and it says
```
2020/11/21 13:23:05 hi!
2020/11/21 13:23:05 reading file: /Users/noibe/.config/lf/lfrc
2020/11/21 13:23:05 loading files: []
2020/11/21 13:23:06 shell: ${{ text_files=() ... }} -- []
2020/11/21 13:23:06 error: running shell: exit status 1
```
I do not have any shellopts set. I tried both running the command line by line in the bash shell and wrapping it in a `bash -c '...'`. The return code is `0` either way. I do not have a `~/.bashrc` (I use fish as my interactive shell).

**Comment by mohkale** [comment]
@noib3 might be a dumb question... but what is your shell set to? By default it should be `set shell sh` which doesn't support all those special substitutions like `${image_files[@]}`

**Comment by noib3** [comment]
@mohkale 
> instead of opening text files and images directly, I add them to an array (I have set shell "bash"), then call $EDITOR or open on the whole bunch.

**Comment by mohkale** [comment]
@noib3 

And if you run `!printenv | grep -i '^lf' | sort -V | "$PAGER"` and look for `lf_shell` is it still bash?

**Comment by noib3** [comment]
@mohkale yep

```
...
lf_shellopts=
lf_shell=bash
lf_smartcase=true
...
```

**Comment by mohkale** [comment]
@noib3 that's strange :/.

> are you on macOS by any chance?

Nope, linux. Plus my shell is zsh.

> can you reproduce the issue?

Nope. 

Oh, I think I've got it. `(( 0 ))` has a non-zero exit code. Try it out.

```sh
(( 0 ))
echo $?
```

What you've got at the end then evaluates to `false && true` which is `false` so you get a bad exit code. I never really use the shell arithmetic fascilities so I didn't notice :zany_face:. Try changing to:

```sh
[ ${#text_files[@]} -gt 0 ] && $EDITOR "${text_files[@]}"
```

**Comment by mohkale** [comment]
I'd also recommend using a pipeline to minimise the number of file processes you're creating.

```sh
text_files=()
image_files=()

while IFS=': ' read -r f mime; do
    echo "$mime"
    case "$mime" in
        text/*|inode/x-empty) text_files+=("$f");;
        image/*) image_files+=("$f");;
        video/*) open -n "$f";;
        *) open "$f" &>/dev/null;;
    esac
done < <(printf "%s\n" $fx | xargs -r -d '\n' file --mime-type)

[ "${#image_files[@]}" -eq 0 ] || open "${image_files[@]}"
[ "${#text_files[@]}"  -eq 0 ] || $EDITOR "${text_files[@]}"
```

If you only ever open 1 or 2 files I guess it doesn't matter but trying to open 100 will require a little more flexibility.

**WARN**: The way you (and this above snippet) implements things doesn't account for files with spaces in them. Trying to open `~/foo bar` will open two files `~/foo` and `bar` not one file. There's ways around that but it doesn't really matter for this example.

**Comment by noib3** [comment]
@mohkale 

> Try changing to:
> ```sh
> [ ${#text_files[@]} -eq 0 ] || $EDITOR "${text_files[@]}"
> ```
> Now it should always be true, whether there're text files or not.

Thanks, that worked ;)


> WARN: The way you (and this above snippet) implements things doesn't account for files with spaces in them

Opening files with spaces works fine for me, e.g. open `~/foo bar` will open that file, not `~/foo` and `bar` separately.

**Comment by mohkale** [comment]
> Thanks, that worked ;)

Great :smile:.

> Opening files with spaces works fine for me, e.g. open ~/foo bar will open that file, not ~/foo and bar separately.

Huh, probably because of how lf changes IFS. Nice to know, thanks for sharing. :+1:

**Comment by mohkale** [comment]
@noib3 

Feel free to close this issue if everythings working now.

**Comment by noib3** [comment]
@mohkale 
> Opening files with spaces works fine for me, e.g. open ~/foo bar will open that file, not ~/foo and bar separately.

Well, that wasn't true. Also, since `file` uses `:` as a separator and we have `IFS=': '`, filenames with `:` don't work either.

A possible solution would be to use the null byte as a separator in `file`, setting `IFS` to the null byte. I tried this

```bash
text_files=()
image_files=()
while IFS= read -r -d "" file mime; do
  case "$mime" in
      text/*|inode/x-empty) text_files+=("$file");;
      image/*) image_files+=("$file");;
      video/*) open -n "$file";;
      *) open "$file" &>/dev/null;;
  esac
done < <(printf "%s\n" $fx | xargs -d "\n" file -0 -F "" --mime-type)
[ ${#image_files[@]} -eq 0 ] || open "${image_files[@]}"
[ ${#text_files[@]} -eq 0 ] || $EDITOR "${text_files[@]}"
```
but it doesn't work.

**Comment by mohkale** [comment]
@noib3 

I think it's generally assumed that `:` won't occur in a file path for unix systems. That's why it's used as the seperator in `PATH` and other such variables. `:` is pretty common on windows for file paths (it's the drive seperator) but you're writing this in bash so I doubt that'll be an issue for you.

But you're right. Null would be a better choice. It's just sometimes the way programs handle null confuses me. For example I've had issues with `cut -d '\0'`, so I generally prefer to use : when possible.

**Comment by mohkale** [comment]
@noib3 

> but it doesn't work.

oh I just realised you were asking for help. My bad.

~~I see where you went wrong. I included ` ` in IFS because file has a tendency to pad out the region between the filename and the mime description.~~

~~Eg.~~

```bash
mega    text/plain
thg.org text/plain
```

~~Notice how there's like 4 spaces after mega. That means `$mime` for it would be `"    text/plain"`. A simple fix would be to change `IFS= read -r -d "" file mime` to `IFS= read -r file mime`. But that means you'd have to include a leading `*` in each case statement. I'd recommend just stripping out all whitespace using bash substitution (`${mime//[[:space:]]}/`) or just the leading whitespace with a sed process `sed -e 's/\x0[[:space:]]*/\x0/'`.~~

~~NOTE: There is a bash substitution format to just remove a pattern from the start of a string... but my experience with it has been awful so I just remove all whitespace or just outsource to another process (`sed`).~~

## UPDATE
Looks like [bash](https://stackoverflow.com/questions/55015044/setting-ifs-to-null-byte-does-not-split-lines-correctly-in-command-line) doesn't have a convenient way to read null delimited input. Yet more reasons to avoid null when you can. So from the beginning I don't think this could've worked.

Consider this simple base case:

```bash
while IFS= read -r file mime; do
    echo "$file"
done < <(printf "%s\n" $fx | xargs -d "\n" file -0 -F "" --mime-type)
```

Notice how the entire row is read into `$file` and `$mime` remains empty. You're gonna have to use : or pick a delimiter which you yourself believe you'll rarely see in a file. Null isn't working sadly. For what it's worth I've had to deal with something like this as well. I [ended](https://github.com/mohkale/dotfiles/blob/8f918dc7808701ecf38ffda87c78309a68f6411a/core/autoload/cmds/fzman) up using `£`.

If you don't want to do that. Move to a higher level language like gawk or python.

**Comment by noib3** [comment]
> or continue with your earlier implementation that spawns a file process for each input file.

Unfortunately I think that's the only viable option. Altough tbh I rarely open more than 5 files at once, so that shouldn't be too much of a problem.
