### ISSUE TITLE
Broken preview pane escape code handling 

### ISSUE THREAD

**Issue by Necronian** [gokcehan/lf#52]
The highlight -O ansi command correctly colors the preview pane text. However img2txt -f ansi and also elinks -dump 1 -dump-color-mode 1 both print the escape codes to the screen instead of displaying the colored output.

I believe the problem was introduced in commit 217d89ff961d664a28c7b84e5bbe771ccd7b47cb
The previous commit works fine for me.

**Comment by gokcehan** [comment]
@Necronian Thanks for reporting and locating the commit.

I had tried to handle escape characters that are not used as ansi escape codes (e.g. in vimscript files) since they were crashing lf. One of the things I had changed was to bound the lookahead to find the end character for the escape codes. It looks like we weren't looking ahead enough for some cases. I have increased that lookahead length now. It works with img2txt but I couldn't try it with elinks as I don't know how it works but it is pretty likely the same error so it should work.

I'm closing this issue now. Feel free to open again if the problem persists.
