### ISSUE TITLE
File copy enhancements.

### ISSUE THREAD

**Issue by nativepapaya** [gokcehan/lf#524]
The current behavior of the built-in cp/mv command is to rename the files if a similar-named file/folder already exist in the destination. It would be neat if lf would prompt the user if they would like to override the files instead.

I've been trying to come up with a solution of my own but I am not sure how to go about it. Using cp -i for example would prompt for every file rathe than give a "override all" prompt. Using a custom command also removes the progress indicator at the bottom which I could not recreate it even using cp-p.

That sort of leads into a question I had. Is it possible to modify the built-in lf commands? I was reading through the documentation and the only option that I saw was simply overriding it with a command of your own rather than modifying the existing one. Or simply a way of recreating the built-in command with progress indicators.

**Comment by gokcehan** [comment]
@nativepapaya You need to patch the Go code to be able to modify a built-in lf command. You can check the builtin `rename` command for an example which prompts the user in case of an overwrite, though copying is tricky since it runs in an asynchronous manner, so I'm not sure if it's possible to implement it in an easy way.
