### ISSUE TITLE
Add option to compute directory sizes through an external script

### ISSUE THREAD

**Issue by abarri** [gokcehan/lf#538]
Would you consider providing an option in lf to use an external script for computing the directory sizes?
On my machine, lf reports the size of the folder metadata (4.0K), not the size of the actual contents.
The latter may be much more complex to implement and I think it makes sense to rely on external tools.
This can be accomplished by configuring lf to call and parse the output of an external script provided by the user, say "/usr/bin/get_dir_size". This script could for example be
```
#!/usr/bin/env bash
out=$(timeout 0.5s du -sb "$1" 2> /dev/null | cut -f1)
if [ -z "$out" ]; then
    out=$(/usr/bin/duc ls -b -D "$1" 2> /dev/null | cut -d ' ' -f1)
fi
echo $out
```
which first tries `du` for 0.5s and then falls back to [duc](https://github.com/zevv/duc).

**Comment by gokcehan** [comment]
@abarri Have you search the previous issues? This has been suggested a number of times. What's the difference of this one?

**Comment by abarri** [comment]
@gokcehan There are indeed some similar issues. The main difference is the approach. In #152 , it was implied that the implementation should be done in LF itself, while this issue proposes to work with an external script provided by the user. As an advantage, the user can decide based on his current workflow how he wants to do the computation (e.g. using du with a timeout or using an external tool such as duc). On the other hand, the user is entirely responsible for his own script and any delays it might cause. In #225 it was proposed to the computation on demand, while here it is proposed to run the script automatically in real time for all directories and show the results inline.

**Comment by gokcehan** [comment]
@abarri Ok then I'm marking the issue as an enhancement.

**Comment by abarri** [comment]
Thanks! I created a pull requested.

**Comment by gokcehan** [comment]
@abarri I have left a comment to the PR. Sorry, I should have made myself clear here to avoid wasting effort. I don't think it is particularly a good idea to use external scripts to calculate directory sizes. Approaches discussed in other issues seem more plausible to me. We already have a recursive directory size calculation implementation that we use to display progress during copying. It might be more sensible to use it for this purpose as one can also cache subdirectory sizes in a map and use them accordingly instead of starting each calculation all over from the beginning.

**Comment by abarri** [comment]
No problem at all. The code works well enough for my purposes, so I don't see it as a waste of effort. But I agree that there are cleaner, more efficient solutions.
