### ISSUE TITLE
Under Windows 10, lf does not seem to completely close with quit (q) command

### ISSUE THREAD

**Issue by njascgil** [gokcehan/lf#557]
Hi!
Maybe I'm missing something here, but at least on my Win10 x64 machine it seems that **lf** (r18) keeps running in the background after exiting using _quit_ (or q) command.
I noticed it because I couldn't delete the **lf** *.server.log file. Although I couldn't find **lf** using the _Task Manager_, I managed to check it was running and closed it using _tasklist_ and _taskkill_...
Is this to be expected? I am not sure, but I think previous versions did not exhibit this behaviour.
Thanks!

**Comment by gokcehan** [comment]
@njascgil Server is daemonized to run in the background when the first client runs so this is to be expected. There was a time we weren't able to daemonize properly on Windows, so maybe you are referring to it as the previous version, though it was a long time ago. There has been some recent changes in Windows, but I don't think any of these changes should effect this behavior. Feel free to go over release notes to see if you can spot something related to this.

I remember server was listed in task manager before but I can't find it either now. I have upgraded my Windows since then so maybe there was a change about this. An easy way to close the server is to run `lf -remote quit` from the command line. You can also define a custom command for this purpose so the client and server quits at the same time.

I have been meaning to change the behavior to exit the server when the last client finishes but I'm quite busy these days. You might want to watch #177 to track any changes related to this.

**Comment by njascgil** [comment]
Thanks for taking the time to reply to this question.
The use of a custom command is a nice suggestion!
I'lll go through the release notes and if I indeed find a version which automatically exits the server I'll let you know.
