### ISSUE TITLE
content shifts up when a shell-pipe command contains a newline character

### ISSUE THREAD

**Issue by gotroyb127** [gokcehan/lf#565]
**Steps to reproduce:** 
While running `lf` execute `%echo 1`.

Everything shifts up and `1` appeares above the last line of the terminal.

Quick and dirty hack I use for now:
````diff
diff --git a/ui.go b/ui.go
index 61c9952..a951cab 100644
--- a/ui.go
+++ b/ui.go
@@ -797,6 +797,7 @@ func (ui *ui) draw(nav *nav) {
                ui.wins[woff+i].printDir(ui.screen, nav.dirs[doff+i], nav.selections, nav.saves, ui.styles, ui.icons)
        }

+       ui.msg = strings.ReplaceAll(ui.msg, "\n", "")
        switch ui.cmdPrefix {
        case "":
                ui.drawStatLine(nav)
````

**Comment by gokcehan** [comment]
@gotroyb127 The culprit for this regression is https://github.com/gokcehan/lf/commit/d6c5590ad0f099d32a9bef8cd8d03cfc240abd44 in which I tried to handle combining unicode characters to fix #496. Tab characters were broken with this commit so I tried to fix it in https://github.com/gokcehan/lf/commit/2af2c6de3188f19061b7d15937a586d433aa93e0. It seems that we need to handle newline characters as well. Instead of going through such exceptions I now pushed a commit to check for exactly combining character classes. It seems like an important bug. Thanks for reporting. I should really quit breaking `%` commands. It might be worth pushing out a new release in the upcoming days. Let's wait a while to see if the fix is stable or not.
