### ISSUE TITLE
cmd passes �  instead of х and Р (cyrillic) to the shell commands, map ... $command work fine

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [gokcehan/lf#572]
## The problem

<details>
  <summary> Demo </summary>

https://user-images.githubusercontent.com/14999778/106356272-86abd700-630f-11eb-98d6-2ed74da8d940.mp4

</details>

I want to make directories / files with spaces without entering quotes, so i need to escape spaces / quote the name - hence, i need custom cmd.

From the [Tips](https://github.com/gokcehan/lf/wiki/Tips#commandmapping-to-create-new-directories):

Works fine:

```sh
map A push %mkdir<space>
```

(But doesn't quote the name).

Sends gibberish to mkdir instead of `х` and `Р` (cyrillic; could be more in other alphabets):

```sh
cmd mkdir2 %IFS=" "; mkdir -- "$*"
map a push :mkdir2<space>
```

## How to reproduce

As above or e.g.

```sh
cmd test ${{
    echo $* | less
}}

map t push :test<space>

```

Press t and paste `абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ`.

You'll see:

<details>
  <summary> Demo 2 </summary>

https://user-images.githubusercontent.com/14999778/106356317-d4284400-630f-11eb-9c59-8541b3560c0d.mp4

</details>

## Workaround

For now i just use this hacky "solution" to make things work

```sh
cmd mkdir %{{
    printf 'mkdir: '
    read -r name
    if [ -n "$name" ]; then
        mkdir -p -- "$name"
        lf -remote "send $id select \"$name\""
    fi
}}

map M mkdir
```

## Version

I am on arch linux, latest updates, r19.

Also i just tested master, r10 and even r2, and got the same results, so it seems it always did this.

Works with empty (except for the above parts) lfrc.

**Comment by gokcehan** [comment]
@MahouShoujoMivutilde It seems that tokenization in our scanner was somehow confused with this input. I have now changed our scanner to use ascii only space and digit characters. It seems to fix this issue though I'm not entirely sure why. Thanks for reporting.

**Comment by MahouShoujoMivutilde** [comment]
Thank you!

**Comment by ericonr** [comment]
@gokcehan it likely got confused, because you're passing it bytes, even though unicode is a multi-byte encoding. You might need to split the strings into runes and use those directly instead, but I don't know how to do that (and this would also force you to somehow deal with cases where the string can't be converted, since most file systems don't enforce valid utf-8 for filenames).

**Comment by gokcehan** [comment]
@ericonr Yes, I think you're right, the issue was casting `byte` to `rune` to be able to use `unicode.IsSpace`. Some multibyte characters were split into bytes that clashes with non-ascii space characters (i.e. NEL and NBSP). But I think we are now safe since we only check ascii space characters. As far as I understand, ascii is compatible with utf-8 in the sense that all multibyte characters have their higher bits set so that no ascii byte (i.e. <128) can exists in a multibyte character.

Regarding the string split, if we were to process by runes instead of bytes, I think we would be tied to only utf-8. Processing by bytes actually makes us somewhat encoding independent, at least for 8859 encodings, not sure about utf-16 though. Note that encodings other than utf-8 might not be supported well in other parts of the program. For example, we don't register any other encodings for tcell since that would increase the size of the binary. I think it is fair to recommend utf-8 these days for users who have trouble with a different encoding.

Let me know if you come across an issue similar to this one and we can investigate it further.
