### ISSUE TITLE
lf did not read alias in .bashrc

### ISSUE THREAD

**Issue by kexul** [gokcehan/lf#577]
I've set `alias python=python3` in my .bashrc, but when I type python --version in lf command, it shows 2.7.

**Comment by kdkasad** [comment]
lf runs shell commands using a the following command line:
```sh
$SHELL -c "<your command here>" --
```

By default, bash and zsh do not source the configuration files when invoked with the `-c` option, since they aren't usually useful for non-interactive shells. I'm not sure of a way to force the shell to source the configuration file in command mode.

However, the behavior you're seeing is completely expected. It's just a result of using the `-c` option. You can test by running the following from a shell:
```sh
bash -c "python --version" --
```
It should show the same result as when typing
```
!python --version
```
within lf.

**Comment by kexul** [comment]
Yeah, you are absolutely right. The result of  `bash -c "python --version" is 2.7 too. So, is there any way to set alias in lf?

**Comment by kdkasad** [comment]
I don't know about aliases in lf, but try setting the `BASH_ENV` environment variable to your bashrc. Bash will source it even when run non-interactively.

E.g.
```sh
export BASH_ENV="$HOME/.bashrc"
lf
```

Obviously you could then set this environment variable in your `~/.profile` or `~/.bashrc` to make it persistent.

**Comment by kexul** [comment]
I tried setting it, unfortunately, it did not work.

**Comment by gokcehan** [comment]
@kexul Maybe you can try `source ~/.bashrc` in your command although I would simply type `python3` instead.

**Comment by gokcehan** [comment]
@kexul I guess my suggestion for sourcing may not work well for manually typed commands. I don't know a good solution for this.

There was a discussion about `zsh` related to this in #467 . Maybe there is a better solution there.

**Comment by kdkasad** [comment]
> I tried setting it in my .bashrc, unfortunately, it did not work. Interestingly, when I use `echo $BASH_ENV` in lf, it showed the path I've set in .bashrc, then I tried echo some other environment variables in .bashrc, it also printed the correct value.

So it turns out the problem is actually that bash does not expand aliases in command mode (with `-c` option). It does source the `$BASH_ENV` file, which I tested by doing the following:

Contents of `~/.bashrc`:
```bash
echo bashrc was sourced
alias thisisatest='echo hi'
```

Command run:
```bash
$ BASH_ENV="$HOME/.bashrc" bash -c 'thisisatest'
bashrc was sourced
bash: line 1: thisisatest: command not found
```

So I don't think it'll be possible to use aliases in commands run from lf. Your best bet might be to create a script named `python` which just contains the following:
```sh
#!/bin/sh
exec python3 "$@"
```

Or you could symlink `python` to `python3`, but this could cause breakage in some python scripts.

**Comment by kexul** [comment]
Thanks for your suggestion, it helped a lot.

**Comment by Dimfred** [comment]
For me the expansion of aliases works, you just have to `shopt -s expand_aliases` at the beginning of the function. I guess its because the call to bash is considered a non-interactive shell and there alias expansion is disabled per default. I trying to do the same for `zsh` (`setopt aliases`), however this kinda does not work so far.
