### ISSUE TITLE
initializing screen: character set not supported

### ISSUE THREAD

**Issue by Toasterbirb** [gokcehan/lf#578]
Release: lf-linux-amd64.tar.gz
Error: `2021/02/06 18:04:25 initializing screen: character set not supported`

This might have something to do with my locale, my system recognizes the language etc. but is missing some characters that have nothing to do with English.

One thing I noticed is, that the $TERM variable has something to do with this. If I have it at default ("st-256color" in my case, I get the error above, but if I set $TERM variable to "" (nothing) it prints out error `creating screen: exit status 1`

Edit: Just to clarify, lf doesn't open at all. The error is all output it prints out and crashes immidiately

Here's some system information if that helps
Kernel: linux-5.8.3
WM: dwm
Terminal: st
Shell: bash
Distro: lfs (Linux from scratch)

**Comment by gokcehan** [comment]
@Toasterbirb We don't register character sets other than ascii and utf-8 with tcell since they would bloat the binary size for little or no reason. Is there a reason you're not using utf-8? I think 8859 encodings are legacy these days and I don't know any reason why they should be preferred over utf-8. If for some reason, you can't switch to utf-8, you can still use the ascii encoding though non-ascii characters will not be displayed properly. For example:

    LANG=en_US.UTF-8  lf  # works
    LANG=en_US.8859-1 lf  # character set not supported
    LANG=en_US.ascii  lf  # works

Also you can always hack `lf` to register your encoding with tcell and rebuild from the source. I don't think you would need more than a few lines of additional code.

**Comment by Toasterbirb** [comment]
Setting LANG to `LANG=en_US.UTF-8` fixed the issue. This just gets me wondering where have I set it to 8859-1, since in /etc/locale I have set it to UTF-8 but that's an issue on my side.

Thanks for the help, I'm closing the issue
