### ISSUE TITLE
Can I edit file when letting lf in foreground? 

### ISSUE THREAD

**Issue by kexul** [gokcehan/lf#588]
Sometimes I need to copy and paste file name and path to vim editor.  It would be convenient to have this feature. 
Here is my idea, the upper part is the lf window, the lower part is the vim editor. 

![image](https://user-images.githubusercontent.com/5920217/110465629-a2c14600-810f-11eb-9054-60cd7dd618d7.png)

**Comment by gokcehan** [comment]
@kexul Sorry, I don't really understand what you are suggesting. Can you describe what you are trying to do and fail, and then what you expect to see instead more clearly?

**Comment by kexul** [comment]
Hi @gokcehan , thanks for the attention. When we edit a file with vim editor, it would take up the entire screen, the lf is then running in background. What I want is to run lf and vim in the same time, both in a window.

**Comment by kdkasad** [comment]
> Hi @gokcehan , thanks for the attention. When we edit a file with vim editor, it would take up the entire screen, the lf is then running in background. What I want is to run lf and vim in the same time, both in a window.

If you want them in separate terminal windows, you can use something like the following in your `lfrc`:
```conf
cmd open &$TERMINAL -e vim "$f"
```
Then as long as `$TERMINAL` is set to your terminal emulator, it should open a new window with vim open to the selected file. Since the command starts with a `&` instead of a `$`, it runs in the background without blocking lf.

**Comment by kexul** [comment]
Hi, @kdkasad , I'm using lf in my centos server via ssh connection, without x11 environment. It seems like nothing changed after I used above setting.

**Comment by kdkasad** [comment]
> Hi, @kdkasad , I'm using lf in my centos server via ssh connection, without x11 environment. It seems like nothing changed after I used above setting.

I see. Did you mean you want lf to open vim in the preview pane while keeping lf in the foreground? If so, I don't think that's possible (yet). I assumed "window" meant GUI terminal window.

However, you might be able to accomplish what you want using tmux. Instead of calling a terminal, you could call `tmux split-window`. This would only work inside a tmux session, though.
```conf
cmd open &tmux split-window -v vim "$f"
```
Replace `-v` with `-h` to split the window in half vertically, so you'd get two panes next to each other rather than two panes above/below each other.

**Comment by kexul** [comment]
Hi @kdkasad , thanks for your suggestion. But the command seems not working correctly, when I set `cmd open &tmux split-window -v vim "$f"` and type `:open`, nothing happened. Then I tried `cmd open &{{tmux split-window && vim $f}}`, now a split window appeared but no file opened.

**Comment by kdkasad** [comment]
> Hi @kdkasad , thanks for your suggestion. But the command seems not working correctly, when I set `cmd open &tmux split-window -v vim "$f"` and type `:open`, nothing happened.

That's weird. I copied/pasted the line into my `lfrc` and it works fine. Not sure what the problem is. Maybe try using `$` instead of `&`. It shouldn't make a difference since `tmux split-window` exits immediately.

> Then I tried `cmd open &{{tmux split-window && vim $f}}`, now a split window appeared but no file opened.

That's expected. It's running two separate commands, one to split the tmux window, and a separate one to open vim. In this case, vim must be opened within the new split, which should happen with this command:
```sh
tmux split-window -v vim
```
Try running that from within lf (using both `&` and `!` to execute it) and see if it works that way.

**Comment by kexul** [comment]
Hi, @kdkasad , I've found the problem, my tmux was too old (1.xxx), after upgrade my tmux, it worked perfectly! Thanks for your answer.
