### ISSUE TITLE
Cannot use WSL as shell on lf installed on windows; perhaps allow customizing the /c flag added to commands to allow using WSL shell?

### ISSUE THREAD

**Issue by prscns** [gokcehan/lf#597]
`set shell wsl` and `map w $wsl` in my **lfrc** do get to the WSL shell (this is with WSL2), but then it gets confused and throws out `zsh:1: no such file or directory: /c`.

With `set shell powershell` the binding `map w $wsl` does work, but that's only some of the way there as I can't type commands with `:$` and (using the default binding) `<enter>`. I was told (and it makes sense that) customizing the /c flag added to commands on windows would fix this, which would be a neat feature.

**Comment by gokcehan** [comment]
@prscns I think we might have talked about this already in our chat. I have now added the mentioned option `shellflag` to customize the behavior. If you build from source you can try it on master, otherwise you might want to wait for the next release. The default value is `/c` on windows and you should change it into whatever `wsl` uses. Feel free to tell if it doesn't work.
