### ISSUE TITLE
Option/key to quit `lf` and have the `pwd` be the same in terminal as the last directory in `lf`

### ISSUE THREAD

**Issue by pengux** [gokcehan/lf#6]
Maybe a key like `Q` could execute a `cd` to current working directory in `lf` so that when `lf` quits, the terminal remains at the same folder?

**Comment by gokcehan** [comment]
There is [lf.sh](https://github.com/gokcehan/lf/blob/master/etc/lf.sh) (provided in etc folder) for this purpose. Is that what you ask?

You need to set this up in your shell as there is no way to change the working directory of a parent process otherwise.

**Comment by pengux** [comment]
Ah, that will work too, but how does it work, do you have to press `CTRL+o` in terminal for the dir to change to the last dir in `lf`?

**Comment by gokcehan** [comment]
When you source that file (or just put the contents in your shell rc file) typing `lf` in your terminal will call that function instead of the regular command. That function automatically changes the directory on quit. You don't need to do anything. Keybinding is optional in case you don't like to type `lf` in your terminal.

**Comment by pengux** [comment]
That's great!

**Comment by pengux** [comment]
A word of caution though, I wouldn't recommend anyone to source the file `lf.sh` directly from the git repo, but instead copy the code in your terminal script to avoid security issues.

**Comment by gokcehan** [comment]
Good advice indeed, thanks.
