### ISSUE TITLE
Scrolling preview

### ISSUE THREAD

**Issue by 4volodin** [gokcehan/lf#610]
Scrolling preview would be a cool feature like in fzf preview (Ctrl-n)

**Comment by gokcehan** [comment]
@4volodin If we add preview single line preview scrolling, we would still be missing other navigation commands provided by a pager (e.g. scrolling half/full page, go top/bottom). I think it is easier to simply launch a pager when you start reading the content. Pagers provide many more commands along with useful information. Preview pane is only there to preview a file.

**Comment by 4volodin** [comment]
Ok most likely you are right
but
Maybe Is there a possibility to make hotkeys to increase/decrease font size for the Preview pane?
thanks

**Comment by gokcehan** [comment]
@4volodin You should be able to change your terminal font size using hotkeys and `lf` should draw accordingly. There was a bug to keep the same number of lines in the file preview when the height is increased with a resize event but I have pushed a fix for it now.

**Comment by 4volodin** [comment]
I meant to have а hotkey to change font size only for preview to watch more count of strings (i.e less size in preview and normal font size in other part )

**Comment by gokcehan** [comment]
@4volodin We are using the terminal to draw the ui including the preview pane. We don't really determine the font size ourselves. We simply use whatever the terminal uses. And I don't think there is a way to change the font size of a specific portion of the terminal. So I don't think it's possible if I understood you correctly.

**Comment by slavistan** [comment]
A couple of weeks ago I've had the urge to implement preview scrolling, including pagination for PDFs and e-books and browsing through frames of a video, and I can now safely say that this was a complete waste of time. Not once did a situation arise when it wasn't more convenient to simply press a single button to open vim/zathura/mpv and to navigate my file using an application written for that specific task. It was so pointless, I didn't even save it anywhere.

But since somebody seems to be interested in it, here you go @volodin.

![demo](https://user-images.githubusercontent.com/35600954/115956502-71ed7280-a4fd-11eb-9d9c-af94ee77ed27.gif)

Scrolling for file previews is fairly straightforward to implement with a little shell scripting. See [here](https://github.com/slavistan/lf-gadgets/tree/master/lf-scrollingpreview) for a simple but illustrative example configuration. Provided you have a very basic understanding of shell scripting you'll have no trouble weaving that into your `lf` configuration

**Comment by smackesey** [comment]
I feel quite differetntly than @slavistan and think preview scrolling would we well worth integration into `lf`. Ranger has preview scrolling and it's one of the few areas where it beats lf. I find it useful because I frequently am surveying the contents of large repositories and want to cross reference the content of a flie with contents of its containing directory, or want to very quickly scroll down in a preview. Wiping the whole screen to show the pager is very jarring UX if you are scanning over files quickly.

**Comment by gokcehan** [comment]
@smackesey I understand this could be useful but having an integrated pager was always a non-feature from the start and I think for fair reasons. Implementing a pager is no easy feat and it is well worth being a separate project. As I mentioned previously, if we add simple line scrolling, some users will then request page scrollings, and then top and bottom commands, and then maybe searching etc. There is not a natural place we could draw the line to say no to requests before adding all commands in `less` to `lf`. Not to mention, scrolling is not compatible with our current caching strategy for file previews. Also, there's no shame calling `$ranger` when it is more appropriate for the task at hand. I still keep my `ranger` installed on my machine.
