### ISSUE TITLE
windows : sync: unexpected option to copy file(s):

### ISSUE THREAD

**Issue by rsrini7** [gokcehan/lf#612]
Getting below error when launching lf
sync: unexpected option to copy file(s):

**Comment by gokcehan** [comment]
@rsrini7 Can you try this without a configuration file to locate the issue?

**Comment by rsrini7** [comment]
@gokcehan havent used seperate config file to start the lf. But the same version working fine in another windows.

**Comment by gokcehan** [comment]
@rsrini7 What version are you referring to? I don't have such an issue on my windows. It would help if you can locate the issue on your machines. On windows we are using the socket `127.0.0.1:12345` for server communication. Maybe another process is trying to write to this address?

**Comment by rsrini7** [comment]
![image](https://user-images.githubusercontent.com/5178105/116647307-da25d380-a997-11eb-8c26-1573200a8b10.png)

![image](https://user-images.githubusercontent.com/5178105/116647170-861aef00-a997-11eb-8a46-8f43c3b9a94e.png)

May be my corp antivirus causing this issue. No issues found on my personal laptop. But once started navigating this error disappears.

**Comment by AtifChy** [comment]
the latest commit doesn't have this issue.

**Comment by AddictArts** [comment]
Probably any OS, but for Ubuntu I ran into the error because I had made the `share/lf/files` empty.

It appears to need `move` as an entry, which I mistakenly thought should not be there. I had marked and tagged and was trying to clear things, possible other actions.

Went and looked at the source https://github.com/gokcehan/lf/blob/219ebe5c31778ab96a74a3eecfe8cb82cc205474/app.go#L125 to resolve it.
