### ISSUE TITLE
linux: what is this?

### ISSUE THREAD

**Issue by d7eeem** [gokcehan/lf#613]
[the number 1 thingy](https://imgur.com/gALgVkb)

**Comment by d7eeem** [comment]
it appeared after the latest update.

**Comment by gokcehan** [comment]
@d7eeem It shows the number of cut elements when non-zero. There are similar things for selected and copied files as well each with the same color used in the file list. I have added these as visual cues to avoid accidental operations since our selections work in multiple directories and directories with selection may not always be shown in the ui.

**Comment by d7eeem** [comment]
Aha thank you very much. What an awesome software btw.
