### ISSUE TITLE
Is there a way to `cd` to the current directory I'm in in `lf`, in my shell? 

### ISSUE THREAD

**Issue by Dhamma-valence** [gokcehan/lf#631]
For example, say I'm looking at ~/src/lf while in `lf` but in my shell I'm in ~/ . I want to have a keybinding/function that will let me move my shell's cd to ~/src/lf so when I exit `lf` I'll be there in my shell too. I've tried so many different things but I'm just still unsure if that exists, or if such an integration is even possible.

**Comment by thepenguinthatwants** [comment]
check the lfcd function

**Comment by thepenguinthatwants** [comment]
https://github.com/gokcehan/lf/issues/520

**Comment by h3ndry** [comment]
add this function to your .zshrc. I am not sure if is going to work in .bashrc.

it basical does what you ask, just that you press <Ctrl-o> to open lf  while you're in your terminal, when you quiet of it will cd to that dir.
`
# USE LF TO SWITCH DIRECTORIES AND BIND IT TO CTRL-O
lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^o' 'lfcd\n'

`
source: [https://www.youtube.com/watch?v=eLEo4OQ-cuQ](url)

**Comment by gokcehan** [comment]
We have `lfcd` functions for all common shells in our [etc](https://github.com/gokcehan/lf/tree/master/etc) directory in the repository.

**Comment by thepenguinthatwants** [comment]
I've added this to my bashrc to get it work. Wondering if it's possible to do sourcing from lfrc instead?

LFCD="/home/john/.config/lf/lfcd.sh"
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi

**Comment by gokcehan** [comment]
@thepenguinthatwants I don't think that's possible. You need to get the shell involved somehow to be able to change its working directory.

**Comment by samholmes** [comment]
I'm trying to work out a cmd for this. So far I have

```sh
lfpwd () {
  tmp="$(mktemp)";
  LF_LAST_DIR_PATH=$tmp lf -last-dir-path="$tmp" "$@";
}
```

This will make sure the last dir path is written to a directory after closing lf.

Now, I can write a cmd:

```
cmd wq ${{
  tmp=$LF_LAST_DIR_PATH
  lf -remote "send $id quit"
  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp"
    if [ -d "$dir" ]; then
      if [ "$dir" != "$(pwd)" ]; then
        cd "$dir"
      fi
    fi
  fi
}}
```

This will attempt to read the file after sending a quit command to the running lf process. Though, the lf wont write to the `--last-dir-path` until after process exits, and there is a race condition where the file is empty before the rest of the command finishes.

I need a way to get the last directory from the cmd instead of relying on a file configured by `--last-dir-path` to have the path written to it. How do I get the last-dir-path from within the cmd?

**Comment by lahwaacz** [comment]
@samholmes You can't `cd` in the _outer_ shell from within `lf` as it runs the commands in a separate shell instance. If it worked the way you think, you wouldn't need the temporary file at all, since "lf changes the working directory of the process to the current directory so that shell commands always work in the displayed directory" (quoted from the documentation).

**Comment by samholmes** [comment]
> @samholmes You can't `cd` in the _outer_ shell from within `lf` as it runs the commands in a separate shell instance. If it worked the way you think, you wouldn't need the temporary file at all, since "lf changes the working directory of the process to the current directory so that shell commands always work in the displayed directory" (quoted from the documentation).

I later understood that. I edited my comment to show how I was able to do what I wanted to do. I still have a file that is written before and after exiting lf, however it is used to determine the last directory and allow the commands to act accordingly.

The final part I'd wish to know is how can I add a red waring prompt in lf where the command is written instead of using `echo` and `read` to show the message printed?

**Comment by samholmes** [comment]
Looks like I can [Pipe Shell Commands](https://pkg.go.dev/github.com/gokcehan/lf#hdr-Piping_Shell_Commands), but how do I clear or reset the prompt line at the bottom of the UI?

**Comment by kevindirect** [comment]
I can do this outside of lf with [samedir](https://github.com/MyOS-ArchLinux/samedir) and sxhd to set the keybind. Samedir works with any window in X and works for the lf current directory too.

**Comment by mo-st** [comment]
I was wondering if it is possible to assign the "exit to tempfile" command within the regular `lf.` For example, press `ctrl + o` within `lf` to `cd` to current directory and quit (`lfcd` behaviour) but keep the regular behaviour on `q`. It would be convenient to have both options available with different bindings before invoking either`lfcd` or regular `cd`. Sorry if this is a stupid question, I don't understand enough about the implementation details of `lf` to tell. Thank you.

**Comment by mroavi** [comment]
> 

Nice that you found a workaround. I'm trying to do the same. Could you share how you assigned the action of spawning a new window to a keyboard shortcut using Alacritty?

**Comment by mo-st** [comment]
Sure, I hope this is still on topic enough as a workaround to the main issue (which is still unresolved imo):
You want to assign the `CreateNewWindow` action within alacritty to a key combination within your `alacritty.yml` config file under the `key_bindings` section. 

I currently work with MacOS so adapt this example line to your own environment:
```
key_bindings:
...
 - { key: Return, mods: Command, action: CreateNewWindow }
...
```
I'm going to experiment around with assigning closing the old window to the same shortcut a bit, I'll update this comment if I find anything useful.

**Comment by mroavi** [comment]
@mo-st Thanks a lot!

> I'm going to experiment around with assigning closing the old window to the same shortcut a bit, I'll update this comment if I find anything useful.

That would really fix the issue for those of us using Alacritty!

**Comment by mo-st** [comment]
I don't think the `SpawnNewInstance` action is what we're looking for in this context, here are the descriptions from the alacritty sample yml :
```
- SpawnNewInstance
       Spawn a new instance of Alacritty.
- CreateNewWindow
       Create a new Alacritty window from the current process.
```
Spawning a completely new alacritty instance would reset your working directory from the one we'd like to go to out of `lf`. Hope this made things a bit clearer.
