### ISSUE TITLE
Hide all files?

### ISSUE THREAD

**Issue by recallthis** [gokcehan/lf#642]
Hi,

I'm trying to convert a script from ranger which uses --show-only-dirs

Is there a way to hide all files and not directories? I tried set hidden! and various hiddenfiles globs but I'm not sure what I'm doing.

Thanks in advance.

**Comment by gokcehan** [comment]
@recallthis I don't think this is possible in `lf` and if it is possible I don't know how. What is the use case for this?

**Comment by mtoohey31** [comment]
Hello! I have a use case for this: using `lf` as a [qutebrowser fileselect folder command](https://qutebrowser.org/doc/help/settings.html#fileselect.folder.command). I don't know go rn so I'm not able to contribute myself, but I figured I'd mention the use-case.

**Comment by mtoohey31** [comment]
Actually, looking at the source code it doesn't seem too complicated to fix, there are two options I'm considering:

1. A `dironly` option that just hides everything that's not a directory when enabled.
2. Appending `/`'s to the ends of names for directories in the `isHidden` function is `os.go`, that way directories can be ignored with `set hiddenfiles *:!*/`.

I'm leaning towards the first because with the second it becomes extremely complicated if you want to do other things at the same time, such as hiding directories beginning with a `.`, such as `.config`, though the second is elegant in that it aligns with the behaviour of most shells with globs (see `echo */`). The first may also make the handling of the `hidden` variable more complicated, and we'd have to determine how those would interact.

Let me know what you think, I'd be happy to implement either in my spare time.

**Comment by gokcehan** [comment]
@mtoohey31 Thanks for the use case and possible solutions. I agree first solution seems to be simpler than the other. On the other hand, we have something similar to the second solution in our color/icon configuration (i.e. dirs have trailing `/`). It might be worthwhile to implement something similar here but I don't know if there are any complications and/or corner cases. I can't really say which approach is better at this point. If you are going to work on this, maybe it is better for you to decide.
