### ISSUE TITLE
Selector color

### ISSUE THREAD

**Issue by cycloss** [gokcehan/lf#655]
I've looked in the color section of the documentation but I can't seem to find what i'm looking for. Is there a way of setting the highlight color of the selector in only the middle column? For example in the image below, i'd like to be able to have the middle column selector which is currently on `Library` have a white highlight to it instead of the mint green. It's a small thing, but it would be a nice visual reminder of the 'active' middle column.

![screenshot](https://user-images.githubusercontent.com/50776059/123064792-7f907d00-d406-11eb-9880-2c0ccba07ab8.png)

**Comment by Raytle** [comment]
I like your idea: it would be subtle yet useful.

**Comment by gokcehan** [comment]
@lucas979797 I don't configure colors myself so color support is still rudimentary. I think we should first implement the support for color/icon configuration in separate files before adding such detailed configuration mechanisms. Environment variables are only there to import colors from existing configurations.

**Comment by Yekutiel** [comment]
@lucas979797 made a very good suggestion which almost certainly belongs on a reasonable road map.

> I don't configure colors myself so color support is still rudimentary.

That's irrelevant and, well, self-centered. Put simply: who cares if you configure colors or not? Your opinion is not very important in this matter. What's important is this: what will make lf better for a large percentage of users.

**Comment by lucas979797** [comment]
Alright guys let's keep it civil. @gokcehan has made an excellent utility which we all use and enjoy for free. @Yekutiel thanks, I think it would be a nice addition. Hopefully @gokcehan might consider it at some point.

**Comment by Yekutiel** [comment]
@lucas979797 This ain't my first rodeo. Almost all FOSS developers I've dealt with have been both ignorant and arrogant. It's a caustic combination. When I detect even a hint of either ignorance or arrogance I go straight after them. Why? Because if there attitude is, "It's my way or the highway" then, well, I'll be looking for the entrance to the freeway.

You and I both made crystal clear, irrefutably good suggestions. Mine would take less merely a minute or two to implement. Sooooo, how did @gokcehan respond? Yeah. Ummm. Well. I'll be very blunt. He resonded like a typical ignorant and arrogant FOSS developer.

I guess I'll probably using nnn or even Ranger. I have very little confidence is @gokcehan at this point. Like most FOSS projects, this one seems light a shooting star that will sun fizzle and disappear into the inky blackness of the night.

**Comment by joelim-work** [comment]
> Is there a way of setting the highlight color of the selector in only the middle column? 

To answer the original question, this can be achieved using the `cursoractivefmt` option.
