### ISSUE TITLE
Immitate ranger behavior

### ISSUE THREAD

**Issue by hanako923** [gokcehan/lf#725]
I have been working with ranger for quite some years now and I keep coming back to lf to give it another try whenever I have to work with large numbers of files, since that is one thing what lf is clearly better at.

However, I still prefer the commands and behavior of ranger over that of lf and I am pretty sure that I am not the only one who finds it hard to migrate because of that. 

There are some resources to make lf behave more like ranger but they still do not make it easy to get the full ranger behavior in lf as it is right now.

Theres https://github.com/gokcehan/lf/wiki/Ranger which lists the scope config, but not the slightest clue how to implement it. That is probably easy to fix for anyone who has a deeper understanding of the lf config, therefore it would be great if that wiki page could include the actual instructions required to use those scripts.

There is also https://github.com/westofer/lf-ranger-keybingings but it does not make lf behave like ranger but rather seems to implement some custom behavior.

It would probably help a lot of people to get used to lf with a example configuration for default ranger keybindings as well as scope/rifle setup instructions that are easy to follow.

**Comment by gokcehan** [comment]
@hanako923 I agree ranger wiki page should have been much more useful than it is right now. Hopefully, this issue might encourage more users. Note everyone, wiki pages are publically editable and maintained by the community. I rarely follow any updates in wiki pages myself.

**Comment by desbma** [comment]
@hanako923
Care to explain exactly what you are trying to imitate from ranger?

I'm  coming from ranger myself, and switched mostly for 2 reasons: poor performance, and dated color handling (due to Python old Ncurses version).
lf is much more barebones than ranger out of the box, but that is a design decision, and a good thing IMO.

For key bindings, I think most people don't use 5% of what Ranger provides. It makes more sense to identify the few bindings you are missing and add then in lf.

lf is also easier to extend (shell fragments vs Python for ranger), although shell escaping can be really tricky and annoying to setup.

To replace scope.sh/rifle provided with ranger, I wrote my own tool [`rsop`](https://github.com/desbma/rsop), because I did not find any existing tool that was both simple and consistent.

**Comment by hanako923** [comment]
> @hanako923 Care to explain exactly what you are trying to imitate from ranger?
> 

There are a number of things I run into whenever I give lf a change. I could list the keybindings for deleting files or simply changing directory by typing cd. Using the commands I got used to by using ranger will do different things in lf and while I could probably manage to identify and fix all those commands I want to use by try and error, I have neither the patience nor the time to do that at the moment and Im probably not the only one who went back to ranger because of this.

Thats why I believe a full set of ranger-command settings (as far as they are already implemented in lf) would help a lot of people to migrate.

**Comment by desbma** [comment]
I use the del key to delete files and I thought ranger had a similar binding, but maybe you are using another one.

Unfortunately I doubt anyone is willing to do the work of writing a full ranger-like config. That would be a lot of work for a fraction of users only using a fraction of said config.

This is a tool targeting somewhat power users, I think it's safe to say you will only fully benefit from if you take some time to learn and configure it.

**Comment by slavistan** [comment]
@hanako923 Which behaviors and keybindings would you like to configure specifically? I've never used ranger but I've hacked lf to the moon and back and I'll happily help you set up your config to get that ranger look-and-feel.

**Comment by hanako923** [comment]
@slavistan I believe it would be a good start if this page https://github.com/gokcehan/lf/wiki/Ranger would be updated with actual instructions how to use the mentioned scripts in lf. Integrating rifle into lf should probably be easy to manage but I have not yet found the time to look into it myself. https://github.com/ranger/ranger/wiki/Official-User-Guide#rifle

As for the keybindings, I believe it would be sufficient to have the basic behavior for file management implemented, things like "dD" which in ranger deleted the marked/highlighted file. This could then be used to implement additional ranger keybindings.

**Comment by nikinbaidarr** [comment]
> @hanako923 I've hacked lf to the moon and back and I'll happily help you set up your config to get that ranger look-and-feel.

Hey! I've started to use lf just today and migrated from ranger. I've one question for you. In ranger or any other terminal program really, pressing <C-z> will suspend that program. But not lf. How can I get lf to behave that way? If you've ever managed to fix that?

**Comment by slavistan** [comment]
@nikinbaidarr I assume you mean Ctrl-Z :-) I had a quick glance at the code and it seems that this behavior is defined inside the TUI libraries used by lf and ranger which are tcell and curses, respectively. This means that you're out of luck, unfortunately.

As seen [here](https://github.com/ranger/ranger/blob/7cbdd92a66e5f0d08672b4b9fc36492a7dc1eed6/ranger/gui/ui.py#L110), ranger configures the terminal to [rare mode](https://en.wikipedia.org/wiki/Terminal_mode), which handles Ctrl-Z in the conventional Unix manner by suspending the process. Conversely, to tcell Ctrl-Z is just a regular key chord which is not handled by default. I'm sure it would be very easy to emulate the Unix Ctrl-Z behavior with tcell and I do agree that this is a canonical Unix behavior, although I very rarely use it. Maybe @gokcehan can chime in and give us his assessment.

As for now, try `map <c-z> $$SHELL`, which gives you a shell upon Ctrl-Z. Instead of *fg*, however, you need to `exit` or press *Ctrl-D* to terminate the shell and get back to lf.

**Comment by nikinbaidarr** [comment]
> @nikinbaidarr I assume you mean Ctrl-Z :-) I had a quick glance at the code and it seems that this behavior is defined inside the TUI libraries used by lf and ranger which are tcell and curses, respectively. This means that you're out of luck, unfortunately.
> 
> As seen [here](https://github.com/ranger/ranger/blob/7cbdd92a66e5f0d08672b4b9fc36492a7dc1eed6/ranger/gui/ui.py#L110), ranger configures the terminal to [rare mode](https://en.wikipedia.org/wiki/Terminal_mode), which handles Ctrl-Z in the conventional Unix manner by suspending the process. Conversely, to tcell Ctrl-Z is just a regular key chord which is not handled by default. I'm sure it would be very easy to emulate the Unix Ctrl-Z behavior with tcell and I do agree that this is a canonical Unix behavior, although I very rarely use it. Maybe @gokcehan can chime in and give us his assessment.
> 
> As for now, try `map <c-z> $$SHELL`, which gives you a shell upon Ctrl-Z. Instead of _fg_, however, you need to `exit` or press _Ctrl-D_ to terminate the shell and get back to lf.

Yes I meant `<C-z>`. Perhaps I forgot the back ticks. Thanks for looking into this, ranger had problems suspending things too so it's fine.

**Comment by slavistan** [comment]
@nikinbaidarr I added an email address to my profile :+1: Thanks for the hint.

**Comment by gokcehan** [comment]
@nikinbaidarr @slavistan At some point, someone came up with the following command to emulate the `<c-z>` behavior (which is available in the [tips](https://github.com/gokcehan/lf/wiki/Tips#put-lf-into-background) wiki):

```
map <c-z> $ kill -STOP $PPID
```

I thought this was a good enough solution so I didn't look into this further. I might be wrong but as far as I'm aware, tcell only uses raw terminal mode as cbreak mode is only specific to unix terminals and it may not have an equivalent concept in windows terminals.

**Comment by nikinbaidarr** [comment]
> map <c-z> $ kill -STOP $PPID

Hey that's cool. Thank you so much.
