### ISSUE TITLE
Using `lf` as a notes manager

### ISSUE THREAD

**Issue by UtkarshVerma** [gokcehan/lf#731]
Thank you for such a good software.
I'm planning to use `lf` as a notes manager. To do so, I have a few doubts:

- Is it possible to tell `lf` to not allow traversing up a directory. For example, I want to be unable to navigate above `~/notes` folder.
- Create new files with a default extension, like `.md`.

Please let me know if this is possible.

**Comment by mbpowers** [comment]
You can add commands in lfrc.
The directory one causes the screen to flicker and some error codes but otherwise works as intended.
As far as create file with default extension, I assumed you wanted to open it in an editor, if not you can replace `$EDITOR` with touch.
```
cmd ud ${{
    [ "$(dirname $fx)" != "$HOME/vimwiki" ] && lf -remote "send $id cd .."
}}

map h ud
map v push :!$EDITOR<space>.md<left><left><left>
```
You could also run lf with a different config file `lf -config /path/to/config' so that you don't mess up the normal functionality if you want to use lf in other circumstances. Then you could alias that to something easier to type in your shell config for quick access.

Btw, what note taking app are you using?

**Comment by UtkarshVerma** [comment]
Thanks for the suggestions. I'll try these out and let you know.
I used to use `joplin-cli` until I lost few of my important notes because of a [bug it had](https://github.com/laurent22/joplin/issues/5533).

Now that I have some time at my hands, I thought of setting up a generic note-taking workflow using `lf`, `rclone`, `glow`, and `nvim`.  I'll try to mimic `joplin`'s bindings in `lf` as I've gotten used to them.
In the end, I feel I'll have a better note-taking system as `lf` is way faster than `joplin-cli`(NodeJS).

> As I'm learning `vim`, if there are some good suggestions for Markdown extensions for note-taking, please let me know.

**Comment by mbpowers** [comment]
If you are learning vim and want markdown notes, I would take a look at vimwiki. I just started using it myself after trying joplin and obsidian. 

It has a setting to automatically set file extensions to markdown. Here's the vimwiki section of my vim config (pretty sure the extensions part is the `let g:vimwiki_list` command but I got this from Luke Smith's dotfiles so I couldn't tell ya).
```
" Vimwiki
let g:vimwiki_ext2syntax = {'.Rmd': 'markdown', '.rmd': 'markdown','.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
map <leader>v :VimwikiIndex
let g:vimwiki_list = [{'path': '~/vimwiki', 'syntax': 'markdown', 'ext': '.md'}]

" rgrep search through tags
autocmd BufRead,BufNewFile ~/vimwiki/* nnoremap <Leader>wt :Rg ::<Left>
```

**Comment by UtkarshVerma** [comment]
@mbpowers Thanks for suggesting `vimwiki`. It is just so good. I guess I won't need to put in any extra effort and just use `vimwiki` for note-taking.
