### ISSUE TITLE
Preview doesn't keep batcat terminal width

### ISSUE THREAD

**Issue by Adamkadaban** [gokcehan/lf#735]
This is my `pv.sh`:
```bash
#!/bin/bash
if file --mime "$1" | grep "executable" >/dev/null
then
    file -b "$1" | fold -sw "$2"
    echo ""
    (/usr/local/bin/checksec --file "$1" | fold -sw "$2") 2>&1 | tail -n +2
else 
    case "$1" in
        *.tar*) tar tf "$1";;
        *.zip) unzip -l "$1";;
        *.rar) unrar l "$1";;
        *.7z) 7z l "$1";;
        *.pdf) pdftotext "$1" -;;
        *.jpg) viu "$1";;
        *.jpeg) viu "$1";;
        *.png) viu "$1";;
        *.doc) catdoc < "$1";;
        *.docx) docx2txt < "$1";;
        *) /bin/batcat --paging=never --terminal-width="$2" --color=always --theme=base16  "$1" | tail -n +3;;
    esac
fi
```
This line is the main problem:
` /bin/batcat --paging=never --terminal-width="$2" --color=always --theme=base16  "$1" | tail -n +3;;`
Although this wraps in my terminal, it doesn't in the lf preview

**Comment by coskunkut** [comment]
It may be due to prefix characters that bat adds (like line numbers and chars for grid). I simply subtract a number from $2 to match to the preview size:

`text/* | */xml | application/json) bat --theme=base16 --style=numbers --terminal-width $(($2-5)) -f "$1" ;;`

**Comment by joelim-work** [comment]
> It may be due to prefix characters that bat adds (like line numbers and chars for grid).

No, `bat` actually does consider the prefix characters for the purposes of `--terminal-width`, so its behavior is correct.

The reason why the wrapping displays incorrectly is because `lf` starts printing from the third cell (zero-based index of 2) of the preview window. This is easier to see if you have the `drawbox` option enabled. https://github.com/gokcehan/lf/blob/dddf437c42a5e61afefaae6bb39f0c484cd2f0e0/ui.go#L270-L276

This means the effective size of the preview window is reduced by two cells, and you need to use `--terminal-width $(($2-2))` in your preview script.

---

I think the reason why the first two columns are skipped is to maintain consistency with displaying directory previews, which reserve those two spaces to display the selection marker and the tag. I don't think this behavior is likely to change since it could potentially break the previews of other users, and I'm not sure if it's worth introducing some kind of `previewoffset` option either, so I will close this issue, although feel free to reopen if you wish to discuss this further.
