### ISSUE TITLE
lf -server is always killed regardless of autoquit setting

### ISSUE THREAD

**Issue by freed00m** [gokcehan/lf#742]
Hello,

I've just notice that when all clients are closed, lf -server is killed also.

I have `set autoquit off` which should be default anyway and it ain't working.

I use r26 packaged by Manjaro distribution.

Related to #177

**Comment by gokcehan** [comment]
@freed00m Unfortunately, there is no such thing as `set autoquit off`. It should either be `set autoquit` or `set noautoquit`. When you do `set autoquit off`, the evaluator considers this as `set autoquit` and enables the option. As you say, this option is disabled by default so you don't need to add anything yourself or you can explicitly disable it with `set noautoquit`.

FYI, I have been considering a change in the boolean option syntax for a while. I'm hoping to write a detailed proposal for this change in a separate issue to inform users and also get some feedback since it is quite a breaking change.

**Comment by freed00m** [comment]
@gokcehan ah I see, you're right. I have a diferent issue and got confused along the way. When I  do `/usr/bin/lf -server` no server is actually started :/ regardles if I do set autoquit/noautoquit.

Regarding feedback I am fine with having just autoquit/noautoquit but man pages got me confused as well

```
           autoquit       bool      (default off)
       
       Automatically quit server when there are no clients left connected.
```

**Comment by gokcehan** [comment]
@freed00m Assuming you're on unix, there could be a stale unix socket file left from before with no running server process attached (e.g. `/tmp/lf.${USER}.sock`). If not, you can try to have a look at the error from the server log file (e.g. `/tmp/lf.${USER}.server.log`). When the server is launched automatically, we also automatically try to remove previous stale socket files. Maybe we should show the error in stdout in addition to log file for these cases where a user runs the server manually. I might take a look at it as part of #739 .

Regarding the documentation, you are absolutely right. I think we can also do some error checking to report these extra tokens.  I will try to mention this in the proposition.

**Comment by freed00m** [comment]
Yep, stall sock it was. I feel so dumb.
Thx I am closing this.

I was looking at `$XDG_RUNTIME_DIR` for the socket instead of `/tmp` :D 

would be cool to change the socket path, unless we already can do that.

**Comment by gokcehan** [comment]
@freed00m You might be able to change socket path by setting `TMPDIR` which is not ideal and there's an ongoing discussion to use `XDG_RUNTIME_DIR` instead in #726 which you might be interested to follow. I expect it to be changed soon along with #739 . That's a fair assumption so there's no need to feel dumb at all, cheers.
