### ISSUE TITLE
Add new command `exec`

### ISSUE THREAD

**Issue by subnut** [gokcehan/lf#752]
From `man 3p exec` -
<pre>
<b>DESCRIPTION</b>
       The exec family of functions shall replace the current process image
       with a new process image.
</pre>

Useful for, say, running `vim` in the current directory, and exiting vim to find the shell directly without `Press any key to continue` and <kbd>q</kbd>

**EDIT:** I've never used Go, but after a bit of googling, it seems that the `syscall.Exec` function provides this functionality.

**Comment by gokcehan** [comment]
@subnut From the description you provided, I think you are using something like `!vim .` Have you also considered using `$vim .` so you don't have the `Press any key` prompt?

**Comment by gokcehan** [comment]
@subnut Also for the other `q` key, I think you can define a command to avoid to do it automatically:

```
map a :{{
    $vim .
    quit
}}
```

**Comment by subnut** [comment]
> From the description you provided, I think you are using something like !vim . Have you also considered using $vim . so you don't have the Press any key prompt?

No, sorry I hadn't. Thanks for pointing that out!

---

> Also for the other q key, I think you can define a command to do it automatically [...]

But that doesn't work when the command to be run is, say `vim '+set buftype=nowrite' +GV'` or `zsh` or 'bat --l python ./manager'. It is not possible to define mappings for all possible commands!  

And IIRC, there is no way for custom commands to get the arguments supplied, is there?  
I tried this -
`.config/lf/lfrc`
```
cmd exec :{{
	!
	quit
}}
```
And then tried to run `:exec vim`. It doesn't work.

**Comment by kmarius** [comment]
@subnut You can only pass arguments to shell commands. I think something like

    cmd exec ${{
    	"$@"
    	lf -remote "send $id quit"
    }}

is what you want.

**Comment by subnut** [comment]
Yep. `cmd exec $lf -remote "send $id quit" && exec "$@"` looks like what I wanted.

**Comment by subnut** [comment]
Just nitpicking :sweat_smile: -

The above solution _looks_ like what I wanted, but isn't exactly what I wanted. `exec()` _replaces_ the current program with the new program. The above solution _spawns_ the new program, and then exits when the spawned program exits.

But since there is no difference in the UI front, I have deemed it close enough.

**Comment by kmarius** [comment]
@subnut If you don't like `lf` running in the background you will have to create a wrapper script or a shell function that executes the command _after_ `lf` exits.

**Comment by danielrode** [comment]
There appears to be a decent level of interest in this feature: #1899 and #2060, as well as all the issues that were eventually solved by `lfcd`. I know some devs have mentioned that this feature cannot be implemented because it is incompatible with Windows (valid, considering `lf` is a cross-platform program). I wonder if it would acceptable to add some commands that are platform-specific, as long as it was made very clear that they do not work on all platforms (for instance, the command requested in this issue could be called `unix_exec`). This would allow `lf` to provide optional integration with each system's specific features while communicating up-front that some commands are system-specific.

**Comment by CatsDeservePets** [comment]
@danielrode What problem would it actually solve for you? Is it about running programs without the need of spawning a shell first?
- https://github.com/gokcehan/lf/issues/1627

**Comment by danielrode** [comment]
Primarily, it would solve the whole shell/lf nesting issue in a way I think is more ergonomic and efficient than lfcd (on Unix-like systems, that is). For me in particular though, it would allow me to use lf as a menu for launching terminal programs without having the parent shell and lf process sticking around in the background. I have a folder structure with many scripts in it, and it would be nice if I could use lf to navigate these directories as sub-menus, then I press enter to select a script and have it fully take over the terminal. Once the program exits, the terminal would close. I know I could just map the selection (ENTER) key to spawn the script, and then have lf exit upon return, but it would be nice to simply replace the lf instance once I select the script I want to launch, as at that point I don't need lf anymore in that session.

It would also better support my use of multiple shells. I like switching between Nushell, Fish, Ash, Bash, and even using IPython as an interactive shell, depending on what project/task I am working on. `lfcd` allows the user to return to the original shell they were using, but it would be nice to be able to have different keys mapped so that I can simply spawn my shell of interest in lf's current directory, without having the parent lf and its parent shell process sticking around accumulating an ugly nested chain. Then if I decide I need lf again, I can simply `exec lf` from whatever shell I am working in.

**Comment by CatsDeservePets** [comment]
If you want to use `lf` as a selection menu, isn't [-print-selection](https://github.com/gokcehan/lf/blob/master/doc.md#shell-integration) the right tool? It quits `lf` when pressing `l` (or `<enter>` if you want) and returns the selected item(s). You only need a small wrapper script which launches `lf` with the correct parameters and then handles the return values. No `lf` instance running in the background after opening/launching the selection.

You could have something like this in your script to make it look nice and temporarily map `<enter>` to `open`:
```sh
lf -command 'set nopreview; set ratios 1; set drawbox; map <enter> open; set promptfmt "Select files [%w] %S q: cancel, <enter>: confirm"' -print-selection
```
<img width="799" height="555" alt="Image" src="https://github.com/user-attachments/assets/d31442a5-f3ac-4ea9-848a-1dcead024b5b" />

**Comment by danielrode** [comment]
@CatsDeservePets Oh, nice! I was unaware of that flag. That would certainly be a good solution to the first use case I mentioned.

**Comment by CatsDeservePets** [comment]
Your second use-case is out of `lf`'s scope and something highly specific to your workflow. This is something better handled by `tmux` sessions or similar tools.

However, if you really wanted to switch the shell using `lf`, you could write another wrapper for `lf` (a modified version of `lfcd`) that on exit checks for the existence of a file or env var which contains the shell name you want to switch to. If it does, switch to the shell specified. Inside `lf`, you could do something like this:
```sh
# Make sure to delete older files on startup
cmd on-init &{{
    rm -f ~/.local/share/lf/shell
}}

cmd switch-shell &{{
    if [ "$#" -ne 1 ]; then
        lf -remote "send $id echoerr switch-shell: requires an argument"
        exit 1
    fi
    printf '%s\n' "$1" > ~/.local/share/lf/shell
    lf -remote "send $id quit"
}}
```
