### ISSUE TITLE
new builtin cmd scrollup/down with <c-y> and <c-e> like in vim

### ISSUE THREAD

**Issue by sbinnee** [gokcehan/lf#761]
Hi! I found my fingers keep using \<c-y\> and \<c-e\>, expecting scrollup/down behavior in vim (in vim docs they are called "scroll window upward/downward"). I am a noob to golang but I figured that it shouldn't be that hard to implement, so I did and I think that it is working. But I am not sure about all the edge cases that might happen. If you think this new builtin cmds are good features, I am going to make a pull request of my implementation. 

Thanks for the awesome software!

Edited: escape \<, \> to be displayed

**Comment by sbinnee** [comment]
I use scrolloff setting both in vim and lf. Something I had not noticed in vim when I used c-y and c-e was that at the edge of screen it actually jumps to make sure scorlloff value to be respected. So I mimicked that behavior too, because I thought that it would be natural even if I hadn't noticed it before.

@seantwie03 Thank you for showing your interest,

**Comment by gokcehan** [comment]
@sbinnee Thank you for your interest in contributing. I don't have any objections for adding such commands. There might be some complications due to differences between text editors and file managers though. For example, we don't show `~` for empty lines and I think it is better to show all files at all times when the number of files is less than the number of lines, otherwise it can be confusing in file managers. Also note there was an attempt to add some scroll commands before in #458 which unfortunately didn't make it through the codebase but it might somehow help with the discussion here.

Do you have the implementation in somewhere public? Feel free to send it as a PR so other people can possibly leave some feedback as well.
