### ISSUE TITLE
`ratios` option is not sanitized

### ISSUE THREAD

**Issue by dumblob** [gokcehan/lf#77]
~~~~
set ratios "10:0"
~~~~
yields a weird ratio (the right column has a non-zero size; ratios "9:0" also yields a nonzero right column width, but smaller than with "10:0" - that's really weird behavior from the user's point of view as intuitively one expects that if zero is not zero, then it should be something very close to zero - e.g. a `lim -> 0`)
___
~~~~
set ratios "0"
set ratios "1"
set ratios "9"
...
~~~~
panics:
~~~~
panic: runtime error: index out of range

goroutine 1 [running]:
main.(*ui).draw(0xc42000ad00, 0xc420023020)
        /tmp/packerbuild-1000/lf-git/lf-git/src/lf/ui.go:573 +0x958
main.(*app).handleInp(0xc420132980, 0xc420023080)
        /tmp/packerbuild-1000/lf-git/lf-git/src/lf/app.go:85 +0x1f1
main.client()
        /tmp/packerbuild-1000/lf-git/lf-git/src/lf/client.go:75 +0x6f1
main.main()
        /tmp/packerbuild-1000/lf-git/lf-git/src/lf/main.go:113 +0x279
~~~~
___
~~~~
set ratios "0:0"
~~~~
panics with a different error:
~~~~
panic: runtime error: integer divide by zero

goroutine 1 [running]:
main.getWidths(0x8a, 0x0, 0xc4200519f8, 0x43fdfc)
        /tmp/packerbuild-1000/lf-git/lf-git/src/lf/ui.go:355 +0x12e
main.getWins(0x586f00, 0xc420190008, 0x1)
        /tmp/packerbuild-1000/lf-git/lf-git/src/lf/ui.go:368 +0x4b
main.(*setExpr).eval(0xc42017c520, 0xc4201329a0, 0x0, 0x0, 0x0)
        /tmp/packerbuild-1000/lf-git/lf-git/src/lf/eval.go:120 +0xbc2
main.(*app).handleInp(0xc4201329a0, 0xc4200230e0)
        /tmp/packerbuild-1000/lf-git/lf-git/src/lf/app.go:83 +0x1b2
main.client()
        /tmp/packerbuild-1000/lf-git/lf-git/src/lf/client.go:75 +0x6f1
main.main()
        /tmp/packerbuild-1000/lf-git/lf-git/src/lf/main.go:113 +0x279
~~~~

**Comment by gokcehan** [comment]
In general, I'm not very satisfied with our `ratios` option. So before we add sanity checks we should first decide on how should this option behave in the first place.

#19 suggests that we should have a way to enable/disable info for each column. One of the suggestion is to use a separate option for this purpose (e.g. `set infoOn "0:1"`). The issue with this approach is that users are expected to keep `ratios` and `infoOn` options same length. Since there is no way to set two options at the same time, we also need to decide what should happen when they are not of the same length which can get confusing.

Another suggestion was to combine `ratios` and `infoOn` options under the same name. In this approach sign of values can represent whether information should be shown or not in the column (e.g. `set ratios "-1:2:-3"` shows info only in the middle column). This can be a little weird at first but I think it is better for sanity checks and configuration. It was also suggested to change the name from `ratios` to `layout` when these are combined into a single option.

Another related option is `preview`. Since we need to show at least one column for files, `ratios` option can not have only a single number when `preview` option is on (as you described in your second issue). Therefore I would like to also merge `preview` option with `ratios` somehow. After reading your trials, I thought maybe we should use `0` to denote that preview is disabled (e.g. `set ratios "1:0"` should display a single column without preview). In this scenario, we should do a sanity check for always having at least two numbers in `ratios`.

Any other suggestions?

**Comment by dumblob** [comment]
Maybe an option `column idx ratio kind info` where `idx` is an integer `0..inf`, `ratio` an integer `0..inf`, `kind` is one of `list` `focus` `preview` (`list` is just a plain list of files and dirs, `focus` is the column where the cursor can be moved up and down - there can be only one column of this kind, `preview` is the preview column), `info` a `boolean`, and possibly other options in the future which are column-specific. `idx` would not be an index in an array, but rather a relative position in a list of all columns (thus addition and removal of columns can be done for any index disregarding its position in the list) - pretty much like tabs in *tmux*. Each `column` command which would have `ratio` equal `0` would throw away (remove) the column identified by the `idx`. An example configuration for 4 columns might look like this:
~~~~
# column idx ratio kind info
column 0 1 list no
column 5 3 focus no
column 1 2 list no  # the order of execution of column commands doesn't matter; this column will fit after the very first column
column 6 3 preview no
~~~~
Or maybe we might treat `list` `focus` `preview` as strings and not literals in the config.

I agree though, that the numbers are not so intuitive, so we might think of a more complicated syntax - e.g. `column idx=5 ratio=3 kind=focus info=no`.

**Comment by gokcehan** [comment]
@dumblob I think you also meant to have a `set` keyword before `column`. Since set syntax expects an option name and a single value, we would also need to wrap arguments in a quote (e.g. `set column "0 1 list no"`). Also I don't think it is very meaningful to have `focus` on a column other than the last one. In any case, this is unlike any of our other option syntax. Is there any advantage of using this? If not, I would rather have a brief syntax for this purpose, preferably setting every value in a single command.

**Comment by dumblob** [comment]
>I think you also meant to have a set keyword before column. Since set syntax expects an option name and a single value, we would also need to wrap arguments in a quote (e.g. set column "0 1 list no").

Yep, the example was just to understand the concept. How exactly will it be fitted into the existing syntax is minor issue.

>Also I don't think it is very meaningful to have focus on a column other than the last one.

You meant probably the last but one column as the very last column is currently a preview column. Anyway, there are good use cases - e.g. I would like to have more preview columns (both showing the same file, but differently). Also there are right-to-left languages and the users think of things from right to left (they would like to have columns in an opposite order), so that's another use case. And there will be more **useful** (not just "because we can") ones - we just aren't used to them as it's currently not possible. Even from the implementation point of view, there shouldn't be any obstacle.

>In any case, this is unlike any of our other option syntax. Is there any advantage of using this? If not, I would rather have a brief syntax for this purpose, preferably setting every value in a single command.

As I wrote, I'm not concerned much with syntax. I'm rather concerned with the concept which is "set each column individually". This is also a very good thing for future (I myself am expecting requests for column-specific features).

**Comment by gokcehan** [comment]
@dumblob This issue started off as a sanity check and now you list all these different feature requests. If you like those features then you should create issues for them with details and proper use cases. At the moment, they don't have their semantic equivalent in the current implementation so I don't see any point in designing the option syntax for them.

**Comment by dumblob** [comment]
>If you like those features then you should create issues for them with details and proper use cases.

The point is, that currently these feature proposals are not urgent for me. But because we were discussing the option of backwards-incompatibly changing the syntax, I described a proposal backed up with current and new features. You can easily skip the new features and just implement the new syntax and the features later if someone (e.g. me :wink:) creates separate Issues for them and you and others will find them useful.

**Comment by ipstone** [comment]
Hi @gokcehan, the front page of project github (README.md) shows a gif of 'two-pannel' lf: my question is how it is created?

Is it a tmux window (split)? If then, how can you show `lf` with just one pannel?
Or `lf` truely has a 2-columns/pannels view such as midnight-commander?

thanks!
