### ISSUE TITLE
default color bottom line / file info

### ISSUE THREAD

**Issue by grammoboy2** [gokcehan/lf#878]
default color bottom line / file info is white. In nnn it's blue, in Ranger it starts with a different color then white (purple here). A different color for the bottom line, makes reading more pleasant.

**Comment by camoz** [comment]
I disagree: white is a safe default for readability. Reason: Many terminal programs only use 8/16 colors, as a result many users have tweaked their terminal colors. This often results in not-ideal or poor readability of some color combinations. `nnn` uses normal blue on black, which is not ideal either.

Example, from top to bottom:

- `nnn`
- `lf`
- `ranger`
- `ls -lh`

![slurp_2022-11-11_022044](https://user-images.githubusercontent.com/6276613/201240347-625d280f-d3aa-483f-a2f2-2b2734b9db8a.png)

FWIW I like ranger's output the most. Selective use of colors (similar to syntax highlighting) makes is more readable. Also, its output is very similar to `ls -lh`, which many people are familiar with.

There is no point in changing the color for the complete text, IMO. The statusline is already simple to read/locate since it's located at the bottom of the screen.

**Comment by latipun7** [comment]
I like ranger format too. I hope statusline can be configured something like `statusfmt`.

PS: I think owner and count would be fixed in the next release thru https://github.com/gokcehan/lf/pull/829, which not in the release yet.
