### ISSUE TITLE
How to set the default application for a file type?

### ISSUE THREAD

**Issue by kurkii** [gokcehan/lf#890]
When I open a PNG file, it gets opened with Librewolf, I want it to open with sxiv. I already set sxiv as default with mimeopen, yet lf doesnt seem to follow this. 

Thanks

**Comment by lahwaacz** [comment]
lf's default opener on Linux is xdg-open, not mimeopen. See https://pkg.go.dev/github.com/gokcehan/lf#hdr-Opening_Files

**Comment by kurkii** [comment]
> lf's default opener on Linux is xdg-open, not mimeopen. See https://pkg.go.dev/github.com/gokcehan/lf#hdr-Opening_Files

how could i make lf open with mimeos defaults?

**Comment by pc00per** [comment]
I've `cmd open &xdg-open $f` to open with xdg-open (as per the above documentation link), but `l` keybind still doesn't follow xdg-open.

**Comment by deepaknegilachu** [comment]
Hey,  I have this cmd open:-
cmd open ${{
    case "$f" in
        *.html|*.htm|*.xml) firefox $fx  >/dev/null 2>&1 &;;
        *.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus) mpv $fx >/dev/null 2>&1 &;;
        *.bmp|*.jpg|*.jpeg|*.png|*.gif|*.xpm) swayimg $fx >/dev/null 2>&1 &;;
        *.pdf) zathura $fx >/dev/null 2>&1 &;;
        *.xopp) xournalpp.AppImage $fx >/dev/null 2>&1 &;;
        *.odt|*.doc|*.docx|*.xls|*.xlsx|*.odp|*.pptx) libreoffice $fx >/dev/null 2>&1 &;; 
        *) foot kak $fx >/dev/null 2>&1 &;;
        #*) $OPENER $fx >/dev/null 2>&1 &;;
      esac
}}
#where dev null keep disable send error null file
and & keep application alive even after we close lf.
first u need to setup 
set ifn "\n"  need fx (mutiple file open).

**Comment by joelim-work** [comment]
There is already an `open` command defined in the example config file: https://github.com/gokcehan/lf/blob/534710dcc7593a8076f153501a85dac2e87634ec/etc/lfrc.example#L40-L49

It is deliberately minimal so that users can specify their own default applications. However I think it is fine to add defaults for common formats like images/videos/pdfs if anyone is willing to contribute.

Will close since this is not an actual issue.
