### ISSUE TITLE
`open-file` stack overflow

### ISSUE THREAD

**Issue by KenjiTakahashi** [gokcehan/lf#9]
The macOS has unfortunate default opener named `open`, so I've tried

```
cmd open-file open $fx
```

which made `lf` crash and burn, because it tried to call it's own `open` cmd. Of course, it can be fixed by using `$open` instead, but perhaps we'd like to detect such cases and not die so hard.

**Comment by gokcehan** [comment]
In fact this happens for all recursive commands (e.g. `cmd foo foo` or `cmd foo :down; foo;`). Since we don't have conditionals I guess all recursive calls can be considered errors. But then there is still the case you mention and other arbitrary mutual calls (e.g. `cmd foo bar` and `cmd bar foo`). I'm not sure if there is a straightforward way to detect and handle these. Almost all programming languages have this though. Even though `lf` is not a programming language, it is still a language with recursive constructs. It is unfortunate that this example does look very innocent from the outside but now at least this issue might pop up in the search results to those people having the same problem.

**Comment by KenjiTakahashi** [comment]
Surely it happens for all such commands, this one is just an "ugly" example that many macOS will probably bump into.
I don't think there's a different way than "static analysis", i.e. going through the commands and checking that their parts do not interfere with other commands. That might quickly become infeasible, though. Especially when user defines many own, possibly more complicated, commands.

Anyway, it doesn't really bother me, just felt like letting you know it might be happening.

**Comment by gokcehan** [comment]
I have now added a default file opener on all platforms which includes `open` on mac. New users should not need to configure a file opener until they get used to the syntax. It is unlikely that we may add something else regarding this issue. Closing this issue for now. Feel free to leave comments as you like.
