### ISSUE TITLE
Automatic nightly builds

### ISSUE THREAD

**Issue by Alok** [gokcehan/lf#90]
these don't appear to have been built in a while

**Comment by TeddyDD** [comment]
I'm not sure but maybe travis could be used to build binaries and upload them as releases (for example for tagged commits)

**Comment by gokcehan** [comment]
@Alok Actually I have just updated these the other day and there hasn't been any commits since then. That is why it does not show you how many commits the release lags behind. I have added a note about this to the release page. Hopefully it should be more clear now.

@TeddyDD I don't like to manually update these as well but the last time I checked I couldn't find how to automatically do it with travis. I will check that again when I have some time. Let's keep this issue open for this purpose.

**Comment by TeddyDD** [comment]
@gokcehan link for reference: https://docs.travis-ci.com/user/deployment/releases/

**Comment by gokcehan** [comment]
@TeddyDD It looks like travis have a cli tool to automate preparing the configuration file. I tried to use it but some of the things you have in the example was missing. Thanks for the help.

Now it seems that travis is deploying binaries when a tag is pushed. This is such a relief. I have to try a few more times to see how things work when the nightly tag is force updated.

**Comment by gokcehan** [comment]
Ok so I have added version numbers to the deployment as part of #95. It seems that nightly builds are now redundant and it is best to get rid of it. Closing this issue now.
