### ISSUE TITLE
Show custom description for mappings

### ISSUE THREAD

**Issue by TeddyDD** [gokcehan/lf#91]
lf show mapped commands directly when you press first key in combinatrion. It's ok for simeple, one line commands like
```
map gh cd ~
map gp cd ~/Pictures
```
but it becomes annoying for multi-line bindings:
```
# sort by time
map st :{{
        set sortby time
        set info time
}}
```
lf will show whole command when you press `s`.
My suggestion is to show comment before mapping as description.

**Workaround** don't map long commands to keys directly. Wrap them in cmd:
```
cmd sort-by-time :{{
    set sortby time
    set info time
}}
map st :sort-by-time
```

**Comment by gokcehan** [comment]
Ok so to be clear, I checked it again now and it seems that builtin and shell command behave differently. Builtin commands are wrapped to a single line but shell commands are not since whitespace could be significant. So your example:

    map st :{{
        set sortby time
        set info time
    }}

is shown as:

    st      :{{ set sortby time; set info time; }}

But a shell example such as:

    map rr ${{
        if [ -e $1 ]; then
            lf -remote "send $id echo file exists"
        else
            mv $f $1
        fi
    }}

is shown as:

    rr      $
            if [ -e $1 ]; then
                lf -remote "send $id echo file exists"
            else
                mv $f $1
            fi

I think we might need to do something about the shell command case.

**Comment by gokcehan** [comment]
For completeness, single line shell commands look like this:

    map rr $mv $f $1                 rr     $ mv $f $1
    map rr ${{ mv $f $1 }}           rr     $  mv $f $1

Currently our scanner just skips comments but does not touch anything in shell commands. Instead of changing our scanner, maybe we can only show the first line for shell commands with `...` when it is multiline and people can put the comment to the first line in their shell commands kind of like python docstrings. So the previous example can be written as:

    cmd rr ${{
        # rename current file without overwrite
        if [ -e $1 ]; then
            lf -remote "send $id echo file exists"
        else
            mv $f $1
        fi
    }}

And it may look like this in the end:

    rr      ${{  # rename current file without overwrite... }}

That would be much easier to implement and for single line commands it would just show the command itself. What do you think @TeddyDD ?

**Comment by TeddyDD** [comment]
Looks great, especially if it's easier!

**Comment by gokcehan** [comment]
For the following cases:

    map m1 $mv $f $1

    map m2 ${{ mv $f $1 }}

    map m3 ${{
        if [ -e $1 ]; then
            lf -remote "send $id echo file exists"
        else
            mv $f $1
        fi
    }}

    map m4 ${{
        # rename without overwrite
        if [ -e $1 ]; then
            lf -remote "send $id echo file exists"
        else
            mv $f $1
        fi
    }}

Bindings now show:

    keys    command                                                                   
    m1      ${{ mv $f $1 }}
    m2      ${{ mv $f $1 }}
    m3      ${{ if [ -e $1 ]; then ... }}
    m4      ${{ # rename without overwrite ... }}

I'm still not sure about `{{` and `}}`. Maybe we should drop them from both builtin and shell commands since everything is shown as a single line now.

**Comment by TeddyDD** [comment]
Works great! Not sure about `{{` `}}` but I think `$ & : !` should be displayed so user will know how if command is async or not.
