### ISSUE TITLE
Unable to clean up Chinese

### ISSUE THREAD

**Issue by fengwk** [gokcehan/lf#911]
I use lf on windows terminal, but if Chinese appears, it cannot be cleared in time unless the position where chinese appears is occupied by other English characters.

example: Image1 has chinese. I press j to get to the position in image2, the chinese character remains. 

image1:

![image1](https://user-images.githubusercontent.com/25793618/185440289-53b1bcbe-ed6c-4868-b8dd-bf4fa13066c0.png)

image2:

![image2](https://user-images.githubusercontent.com/25793618/185441249-fdf7c80c-2ccd-4513-b6ed-3dcde3cd1fc0.png)

**Comment by wongsingfo** [comment]
may be duplicate of #644?

**Comment by fengwk** [comment]
> may be duplicate of #644?

OK

**Comment by joelim-work** [comment]
Probably because the widths are not calculated properly for CJK characters by the [`go-runewidth`](https://github.com/mattn/go-runewidth) library. This has recently been updated to support the latest version of Unicode (15.1.0 at time of writing), see https://github.com/gokcehan/lf/commit/534710dcc7593a8076f153501a85dac2e87634ec.

Hopefully this should fix the issue - if not feel free to reopen with a minimal and properly reproducible example.
