### ISSUE TITLE
video thumbnail preview not updating image

### ISSUE THREAD

**Issue by plasmoduck** [gokcehan/lf#947]
I've got lf setup to show video thumbnail previews using ffmpeg in my scope file, but it just shows the same image for every movie. If I clear the thumbnail image from ~/.cache/lf, then it will the always show the image of the first movie I select for everything and not update to show different images for different video files. Here is a snippet of my scope file.

video/* )
                 CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i
\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
                 [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
                 image "$CACHE" "$2" "$3" "$4" "$5"
                 ;;

**Comment by DusanLesan** [comment]
@plasmoduck I see no issues here. Works fine for me

**Comment by DusanLesan** [comment]
> I forgot to mention I'm using FreeBSD and uberzug

Oh, ok. I cannot test that. Good luck. 
You could try [ctpv](https://github.com/NikitaIvanovV/ctpv)

**Comment by cv1618** [comment]
ffmpeg and ffmpegthumbnailer are two different programs, do you have ffmpegthumbnailer installed?
If all else fails I would recommend just git cloning this guys files:
https://github.com/cirala/lfimg

**Comment by joelim-work** [comment]
The script snippet also looks fine to me too. Without knowing anything else, the only other thing I can think of is the `previewer` script not being called at all because the preview is 'cached' as a result of returning successfully, see https://github.com/gokcehan/lf/blob/master/doc.md#previewer-string-default--not-filtered-if-empty

>  If the previewer returns a non-zero exit code, then the preview cache for the given file is disabled. This means that if the file is selected in the future, the previewer is called once again.

Failing that, you should probably inspect the variables using something like `notify-send` or `echo "$some_variable" >> /path/to/log` to see what is being passed to `ffmpegthumbnailer`.

Will close this as I highly doubt that this is an issue with `lf` itself.
