### ISSUE TITLE
The installation instruction is not very newbie friendly - not even medium-user friendly

### ISSUE THREAD

**Issue by emilBeBri** [gokcehan/lf#948]
So it's not as if I'm a complete linux noob - but I'm not a hardcore user either, and I don't now how to use this instructions:

> env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest

could you make it a little more elaborated? That would be hugely appreciated. Thank you for making this piece of software, it;s amazing.

on Manjaro with i3

**Comment by john-soda** [comment]
you can use the update script in the wiki section to install **lf** only thing you have to know is for which architecture you want to install it and adapt the update script.

**Comment by ilyagr** [comment]
The full instructions would be along the lines of:

1. Install go (`sudo apt install golang` on Debian, more instructions on http://golang.org).
2. Open terminal
3. Enter `env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest`
4. Make sure the resulting `lf` binary is in your PATH (I'm not actually sure where it goes).

I find the following alternative simpler (since I didn't set up PATH the way Go wants):

```
git clone github.com/gokcehan/lf@latest
cd lf
go build   # Assumes go is installed
cp lf somewhere/in/PATH
``` 

You can use `env CGO_ENABLED=0 go build -ldflags="-s -w"` instead of `go build` if you want a more portable and stripped binary.

I'm unfamiliar with the update script @john-soda mentioned, but it may also be a good option.

**Comment by lahwaacz** [comment]
The newbie-friendly installation instruction should be something like `pacman -S lf` for Arch Linux (...and Manjaro too...)

**Comment by ilyagr** [comment]
The instructions above are for building the development version.

If you just want the latest release, you can check if your distribution has a package. On Arch, the `pacman -S lf` command may already work, since someone created an [Arch package](https://archlinux.org/packages/community/x86_64/lf/). Packaging for various distributions is outside the scope of this project. Someone familiar with each distribution's guidelines has to do it. 

If a recent enough release of `lf` is not packaged for your distribution, you can download it from https://github.com/gokcehan/lf/releases or use the [updater script](https://github.com/gokcehan/lf/wiki/Updater-script).

**Comment by emilBeBri** [comment]
> The newbie-friendly installation instruction should be something like `pacman -S lf` for Arch Linux (...and Manjaro too...)

Right - some time ago, it was remvoed from the AUR, so I could not update it that way.

@ilyagr 
True, you could argue that. I must have overlooked that update script, I agree that probably if you don't have that level of proffiency then LF is not much use. I was not thinking of newbie, more like 'intermediate', like me. But the wiki I did not look at, I think, I can remember right now. 

Thank you for the responses

**Comment by ilyagr** [comment]
My suggestion, @emilBeBri , would be to download [lf-linux-amd64.tar.gz](https://github.com/gokcehan/lf/releases/download/r27/lf-linux-amd64.tar.gz) from the releases page, unpack the archive, and put the binary somewhere in your PATH. I'd worry about the updater script once you run into a problem it would solve. The `git clone ` instructions should also work easily if you are willing to install Go (which is trivial if your distribution packages Go).

Then, it's up to you whether you like the default settings of `lf`, whether you want to put in the energy to configure it to how you like it, or whether, in its current state, dealing with `lf` is more trouble to you than it's worth.

**Comment by emilBeBri** [comment]
I def think it's more worth than trouble  - Been using it for half a year and i love it, it's my main browser by now :) thank you for the solution.

**Comment by lpanebr** [comment]
I found the `lf` binary at `./go/bin/lf`!

```bash
 find ./ -name lf
./go/pkg/mod/cache/download/github.com/gokcehan/lf
./go/bin/lf
```
