### ISSUE TITLE
keybinding (open file) issue on mac os x

### ISSUE THREAD

**Issue by ipstone** [gokcehan/lf#98]
Hello,

In the helpfile, it indicates on mac, the default open file behavior is mapped to:     
   cmd open-file &open "$f"      # mac

However, this is not default behavior on mac, though we can easily fix it in the lfrc file.
Not sure this is a documentation issue, if yes, we can fix it by stating on mac, the open-file can be redefined such as etc. etc.

Thanks
Isaac

**Comment by gokcehan** [comment]
@ipstone Thanks for reporting this. These default are added about 2 months ago. Can you confirm you have the latest version?

To be honest, I wasn't able to test this since I don't have a mac machine. It seemed simple enough that I thought this would simply work. Corresponding line is in [os.go](https://github.com/gokcehan/lf/blob/master/os.go#L115) which defines `open-file` command as `&open "$f"`. So how exactly do you fix this in lfrc?

I'm adding help wanted tag to this issue so hopefully someone with a mac can patch the correct behavior.

**Comment by ipstone** [comment]
@gokcehan Great work! I confirm using an outdated version of lf. 

Once updating to the latest, and removing my old lfrc in the folder of .config/lf/lfrc, lf opens mac file properly. I think my previous lfrc has settings overiding the default setting. So this is not a bug.

Thank you for the great job on lf. 

One quick question for lf configuration file, is currently a way for the binary to generate a default lfrc file, other than manually download from the repo?
