### ISSUE TITLE
Chinese characters cannot refresh completly 

### ISSUE THREAD

**Issue by scorpionxyz** [gokcehan/lf#985]
When change the directory, the chinese characters will not refreshed completly if there is no english characters cover it.

**Comment by ilyagr** [comment]
This sounds like a difficult bug to diagnose and fix. It could be a bug in your terminal, in lf, or in a library that lf is using.

- Try to compile the version of `lf` from the master branch. We updated some libraries we depend on, it may help.
- Try different terminals. If you use tmux, try to reproduce the bug without tmux.
- If nothing helps, we would need more details, and even then we may or may not be able to help. You could do more research on what the problem could be and share that. You could also share a detailed enough bug report that we can try to reproduce it. Find the simplest directory structure where you can reproduce the bug, zip it up, attach it to a bug, and explain exactly what we need to do to see it. (There are many ways to "change the directory").

**Comment by gokcehan** [comment]
Possible duplicate #644

**Comment by joelim-work** [comment]
Probably because the widths are not calculated properly for CJK characters by the [`go-runewidth`](https://github.com/mattn/go-runewidth) library. This has recently been updated to support the latest version of Unicode (15.1.0 at time of writing), see https://github.com/gokcehan/lf/commit/534710dcc7593a8076f153501a85dac2e87634ec.

Hopefully this should fix the issue - if not feel free to reopen with a minimal and properly reproducible example.
