### ISSUE TITLE
Version is empty when using 'go get' to install

### ISSUE THREAD

**Issue by ipstone** [gokcehan/lf#99]
Currently I obtained lf through go get command, but lf -version only returns empty strings.
Is there a way that we can embed the versioning in the go get build?

Thanks!

**Comment by gokcehan** [comment]
@ipstone I understand this is a problem and I am not very satisfied with our current version implementation either. In fact, I have written a blog post about this a few weeks ago along with some other minor installation issues that I think worth addressing:

https://gokcehan.github.io/posts/installation-with-go-language-can-be-simpler.html

In the post, you can see the full installation instruction as such:

    env CGO_ENABLED=0 go get -u -ldflags="-s -w -X main.gVersion=$(git -C $GOPATH/src/github.com/gokcehan/lf describe --tags)" github.com/gokcehan/lf

This should get you a static stripped binary with the proper version string included. For the time being, I try to avoid writing a makefile or shell script for this purpose since they conflict with `go get`. It is possible that the current effort for `vgo` can make this easier though I do not know much about its extent. Regarding the other two problems (static and stripped binaries), I do not think my post had much of an impact. Maybe I can add the post to [experience reports](https://github.com/golang/go/wiki/ExperienceReports) page to make it more visible so they may come up with a solution for go2, though my expectation is not very high.

**Comment by ipstone** [comment]
Thank you @gokcehan ! The details are very helpful. I will explore vgo to see if there's an easy way to add version as well.
