### ISSUE TITLE
feature  request: Do not redraw screen screen between preview

### ISSUE THREAD

**Issue by sucrecacao** [gokcehan/lf#990]
Hi, 

between two preview lf redraw the screen with a 'loading...' message. 

Even by commenting ui.go line 266, lf will still redraw a blank window.

This create an annoying flickering effets, as mentioned in previous issues. 

Where and how can I hack lf so it doesn't redraw the screen between preview?

**Comment by joelim-work** [comment]
Since #1154, `lf` will now wait 100 milliseconds before displaying a `loading...` message, which should generally be enough time for an image preview to be displayed,

When navigating to a new file, the `cleaner` script will be run immediately - if you want to retain the previous image, you can add some logic in the `cleaner` script to skip clearing if the next file is also an image, see the discussion in #626 for more details.

**Comment by joelim-work** [comment]
@asklow I'm not sure if I understand your comment, but the 100ms affects only how long it takes for the `loading...` message to be displayed. It has no effect on image preview itself - during the time it takes to load the new preview, the decision of whether to retain the previous image or clear it immediately is determined by your `cleaner` script.

Also, the `tcell` library doesn't support distinguishing between key press and key release events, according to the [documentation](https://pkg.go.dev/github.com/gdamore/tcell/v2#EventKey):

> EventKey represents a key press. Usually this is a key press followed by a key release, but since terminal programs don't have a way to report key release events, we usually get just one event. If a key is held down then the terminal may synthesize repeated key presses at some predefined rate. We have no control over that, nor visibility into it.
